.align 256
track_0:
.addr pattern_0
.addr pattern_1
.addr pattern_1
.addr pattern_1
track_1:
.addr pattern_2
.addr pattern_9
.addr pattern_0
.addr pattern_0
.addr pattern_3
.addr pattern_10
.addr pattern_1
.addr pattern_1
.addr pattern_4
.addr pattern_9
.addr pattern_1
.addr pattern_1
.addr pattern_3
.addr pattern_10
.addr pattern_1
.addr pattern_1
.addr pattern_5
.addr pattern_9
.addr pattern_1
.addr pattern_1
.addr pattern_6
.addr pattern_10
.addr pattern_1
.addr pattern_1
.addr pattern_7
.addr pattern_9
.addr pattern_1
.addr pattern_1
.addr pattern_8
.addr pattern_10
.addr pattern_1
.addr pattern_1
.addr pattern_4
.addr pattern_9
.addr pattern_14
.addr pattern_17
.addr pattern_3
.addr pattern_10
.addr pattern_15
.addr pattern_18
.addr pattern_4
.addr pattern_9
.addr pattern_14
.addr pattern_17
.addr pattern_3
.addr pattern_10
.addr pattern_15
.addr pattern_18
.addr pattern_5
.addr pattern_9
.addr pattern_14
.addr pattern_17
.addr pattern_6
.addr pattern_10
.addr pattern_15
.addr pattern_18
.addr pattern_7
.addr pattern_12
.addr pattern_14
.addr pattern_17
.addr pattern_11
.addr pattern_13
.addr pattern_16
.addr pattern_19
.addr pattern_20
.addr pattern_26
.addr pattern_28
.addr pattern_31
.addr pattern_21
.addr pattern_27
.addr pattern_29
.addr pattern_32
.addr pattern_22
.addr pattern_26
.addr pattern_30
.addr pattern_31
.addr pattern_1
.addr pattern_27
.addr pattern_29
.addr pattern_32
.addr pattern_23
.addr pattern_26
.addr pattern_30
.addr pattern_31
.addr pattern_24
.addr pattern_27
.addr pattern_29
.addr pattern_32
.addr pattern_25
.addr pattern_26
.addr pattern_30
.addr pattern_31
.addr pattern_25
.addr pattern_27
.addr pattern_29
.addr pattern_32
.addr pattern_20
.addr pattern_26
.addr pattern_30
.addr pattern_31
.addr pattern_21
.addr pattern_27
.addr pattern_29
.addr pattern_32
.addr pattern_22
.addr pattern_26
.addr pattern_30
.addr pattern_31
.addr pattern_1
.addr pattern_27
.addr pattern_29
.addr pattern_32
.addr pattern_23
.addr pattern_26
.addr pattern_30
.addr pattern_31
.addr pattern_24
.addr pattern_27
.addr pattern_29
.addr pattern_32
.addr pattern_25
.addr pattern_26
.addr pattern_30
.addr pattern_31
.addr pattern_25
.addr pattern_27
.addr pattern_29
.addr pattern_32
.addr pattern_2
.addr pattern_26
.addr pattern_36
.addr pattern_31
.addr pattern_33
.addr pattern_27
.addr pattern_37
.addr pattern_32
.addr pattern_2
.addr pattern_26
.addr pattern_36
.addr pattern_31
.addr pattern_33
.addr pattern_27
.addr pattern_37
.addr pattern_32
.addr pattern_34
.addr pattern_26
.addr pattern_36
.addr pattern_31
.addr pattern_6
.addr pattern_27
.addr pattern_37
.addr pattern_32
.addr pattern_7
.addr pattern_26
.addr pattern_36
.addr pattern_31
.addr pattern_11
.addr pattern_35
.addr pattern_38
.addr pattern_32
.addr pattern_39
.addr pattern_26
.addr pattern_40
.addr pattern_46
.addr pattern_39
.addr pattern_27
.addr pattern_41
.addr pattern_18
.addr pattern_39
.addr pattern_26
.addr pattern_42
.addr pattern_17
.addr pattern_39
.addr pattern_27
.addr pattern_43
.addr pattern_18
.addr pattern_39
.addr pattern_26
.addr pattern_40
.addr pattern_46
.addr pattern_39
.addr pattern_27
.addr pattern_41
.addr pattern_18
.addr pattern_39
.addr pattern_26
.addr pattern_44
.addr pattern_17
.addr pattern_39
.addr pattern_27
.addr pattern_45
.addr pattern_18
.addr pattern_47
.addr pattern_52
.addr pattern_54
.addr pattern_61
.addr pattern_48
.addr pattern_53
.addr pattern_55
.addr pattern_18
.addr pattern_49
.addr pattern_52
.addr pattern_56
.addr pattern_61
.addr pattern_50
.addr pattern_53
.addr pattern_57
.addr pattern_18
.addr pattern_47
.addr pattern_52
.addr pattern_58
.addr pattern_61
.addr pattern_48
.addr pattern_53
.addr pattern_55
.addr pattern_18
.addr pattern_49
.addr pattern_52
.addr pattern_59
.addr pattern_61
.addr pattern_51
.addr pattern_53
.addr pattern_60
.addr pattern_18
.addr pattern_62
.addr pattern_63
.addr pattern_65
.addr pattern_46
.addr pattern_62
.addr pattern_64
.addr pattern_66
.addr pattern_18
.addr pattern_62
.addr pattern_63
.addr pattern_67
.addr pattern_17
.addr pattern_62
.addr pattern_64
.addr pattern_68
.addr pattern_18
.addr pattern_62
.addr pattern_63
.addr pattern_69
.addr pattern_46
.addr pattern_62
.addr pattern_64
.addr pattern_70
.addr pattern_18
.addr pattern_62
.addr pattern_63
.addr pattern_71
.addr pattern_17
.addr pattern_62
.addr pattern_64
.addr pattern_72
.addr pattern_18
.addr pattern_73
.addr pattern_52
.addr pattern_81
.addr pattern_61
.addr pattern_74
.addr pattern_53
.addr pattern_82
.addr pattern_18
.addr pattern_75
.addr pattern_52
.addr pattern_83
.addr pattern_61
.addr pattern_76
.addr pattern_53
.addr pattern_84
.addr pattern_18
.addr pattern_77
.addr pattern_52
.addr pattern_85
.addr pattern_61
.addr pattern_78
.addr pattern_53
.addr pattern_86
.addr pattern_18
.addr pattern_79
.addr pattern_52
.addr pattern_87
.addr pattern_61
.addr pattern_80
.addr pattern_53
.addr pattern_88
.addr pattern_18
.addr pattern_89
.addr pattern_26
.addr pattern_1
.addr pattern_98
.addr pattern_21
.addr pattern_27
.addr pattern_91
.addr pattern_98
.addr pattern_90
.addr pattern_26
.addr pattern_92
.addr pattern_98
.addr pattern_1
.addr pattern_27
.addr pattern_93
.addr pattern_98
.addr pattern_23
.addr pattern_26
.addr pattern_94
.addr pattern_98
.addr pattern_24
.addr pattern_27
.addr pattern_95
.addr pattern_98
.addr pattern_25
.addr pattern_26
.addr pattern_96
.addr pattern_98
.addr pattern_25
.addr pattern_27
.addr pattern_97
.addr pattern_99
.addr pattern_20
.addr pattern_26
.addr pattern_100
.addr pattern_46
.addr pattern_21
.addr pattern_27
.addr pattern_1
.addr pattern_18
.addr pattern_22
.addr pattern_26
.addr pattern_0
.addr pattern_17
.addr pattern_1
.addr pattern_27
.addr pattern_1
.addr pattern_18
.addr pattern_23
.addr pattern_26
.addr pattern_1
.addr pattern_46
.addr pattern_24
.addr pattern_27
.addr pattern_1
.addr pattern_18
.addr pattern_25
.addr pattern_1
.addr pattern_1
.addr pattern_17
.addr pattern_25
.addr pattern_1
.addr pattern_1
.addr pattern_18
track_2:
.addr pattern_101
.addr pattern_105
.addr pattern_109
.addr pattern_110
.addr pattern_102
.addr pattern_106
.addr pattern_109
.addr pattern_111
.addr pattern_103
.addr pattern_107
.addr pattern_109
.addr pattern_112
.addr pattern_104
.addr pattern_108
.addr pattern_109
.addr pattern_113
.addr pattern_101
.addr pattern_116
.addr pattern_119
.addr pattern_110
.addr pattern_114
.addr pattern_117
.addr pattern_120
.addr pattern_111
.addr pattern_115
.addr pattern_118
.addr pattern_120
.addr pattern_112
.addr pattern_104
.addr pattern_117
.addr pattern_121
.addr pattern_113
.addr pattern_122
.addr pattern_126
.addr pattern_119
.addr pattern_110
.addr pattern_123
.addr pattern_127
.addr pattern_120
.addr pattern_111
.addr pattern_124
.addr pattern_128
.addr pattern_120
.addr pattern_112
.addr pattern_125
.addr pattern_129
.addr pattern_121
.addr pattern_113
.addr pattern_130
.addr pattern_133
.addr pattern_109
.addr pattern_110
.addr pattern_101
.addr pattern_134
.addr pattern_137
.addr pattern_111
.addr pattern_131
.addr pattern_135
.addr pattern_138
.addr pattern_112
.addr pattern_132
.addr pattern_136
.addr pattern_138
.addr pattern_113
.addr pattern_139
.addr pattern_143
.addr pattern_109
.addr pattern_110
.addr pattern_140
.addr pattern_144
.addr pattern_137
.addr pattern_111
.addr pattern_141
.addr pattern_145
.addr pattern_138
.addr pattern_112
.addr pattern_142
.addr pattern_143
.addr pattern_138
.addr pattern_113
.addr pattern_146
.addr pattern_148
.addr pattern_152
.addr pattern_110
.addr pattern_147
.addr pattern_149
.addr pattern_120
.addr pattern_111
.addr pattern_124
.addr pattern_150
.addr pattern_120
.addr pattern_112
.addr pattern_124
.addr pattern_151
.addr pattern_121
.addr pattern_113
track_3:
.addr pattern_0
.addr pattern_153
.addr pattern_157
.addr pattern_159
.addr pattern_1
.addr pattern_154
.addr pattern_158
.addr pattern_160
.addr pattern_1
.addr pattern_155
.addr pattern_157
.addr pattern_159
.addr pattern_1
.addr pattern_156
.addr pattern_158
.addr pattern_160
.addr pattern_161
.addr pattern_165
.addr pattern_157
.addr pattern_159
.addr pattern_162
.addr pattern_166
.addr pattern_158
.addr pattern_160
.addr pattern_163
.addr pattern_167
.addr pattern_157
.addr pattern_159
.addr pattern_164
.addr pattern_168
.addr pattern_158
.addr pattern_160
.addr pattern_169
.addr pattern_173
.addr pattern_157
.addr pattern_159
.addr pattern_170
.addr pattern_174
.addr pattern_158
.addr pattern_160
.addr pattern_171
.addr pattern_175
.addr pattern_157
.addr pattern_159
.addr pattern_172
.addr pattern_176
.addr pattern_158
.addr pattern_160
.addr pattern_177
.addr pattern_181
.addr pattern_157
.addr pattern_159
.addr pattern_178
.addr pattern_182
.addr pattern_158
.addr pattern_160
.addr pattern_179
.addr pattern_183
.addr pattern_157
.addr pattern_159
.addr pattern_180
.addr pattern_1
.addr pattern_158
.addr pattern_160
.addr pattern_184
.addr pattern_188
.addr pattern_157
.addr pattern_159
.addr pattern_185
.addr pattern_189
.addr pattern_158
.addr pattern_160
.addr pattern_186
.addr pattern_190
.addr pattern_157
.addr pattern_159
.addr pattern_187
.addr pattern_1
.addr pattern_158
.addr pattern_160
.addr pattern_191
.addr pattern_195
.addr pattern_157
.addr pattern_159
.addr pattern_192
.addr pattern_196
.addr pattern_158
.addr pattern_130
.addr pattern_193
.addr pattern_197
.addr pattern_157
.addr pattern_159
.addr pattern_194
.addr pattern_0
.addr pattern_158
.addr pattern_130
.addr pattern_198
.addr pattern_1
.addr pattern_157
.addr pattern_159
.addr pattern_199
.addr pattern_1
.addr pattern_158
.addr pattern_130
.addr pattern_198
.addr pattern_1
.addr pattern_157
.addr pattern_159
.addr pattern_193
.addr pattern_1
.addr pattern_158
.addr pattern_130
.addr pattern_1
.addr pattern_200
.addr pattern_157
.addr pattern_159
.addr pattern_1
.addr pattern_201
.addr pattern_158
.addr pattern_160
.addr pattern_1
.addr pattern_200
.addr pattern_157
.addr pattern_159
.addr pattern_1
.addr pattern_202
.addr pattern_158
.addr pattern_160
.addr pattern_198
.addr pattern_0
.addr pattern_157
.addr pattern_159
.addr pattern_199
.addr pattern_1
.addr pattern_158
.addr pattern_130
.addr pattern_198
.addr pattern_1
.addr pattern_157
.addr pattern_159
.addr pattern_193
.addr pattern_1
.addr pattern_158
.addr pattern_130
.addr pattern_1
.addr pattern_203
.addr pattern_157
.addr pattern_159
.addr pattern_1
.addr pattern_204
.addr pattern_158
.addr pattern_160
.addr pattern_1
.addr pattern_203
.addr pattern_157
.addr pattern_159
.addr pattern_1
.addr pattern_205
.addr pattern_158
.addr pattern_160
.addr pattern_206
.addr pattern_153
.addr pattern_157
.addr pattern_159
.addr pattern_207
.addr pattern_154
.addr pattern_158
.addr pattern_130
.addr pattern_206
.addr pattern_155
.addr pattern_157
.addr pattern_159
.addr pattern_208
.addr pattern_156
.addr pattern_158
.addr pattern_130
.addr pattern_209
.addr pattern_165
.addr pattern_157
.addr pattern_159
.addr pattern_210
.addr pattern_166
.addr pattern_158
.addr pattern_160
.addr pattern_211
.addr pattern_167
.addr pattern_157
.addr pattern_159
.addr pattern_212
.addr pattern_168
.addr pattern_158
.addr pattern_160
.addr pattern_169
.addr pattern_173
.addr pattern_157
.addr pattern_159
.addr pattern_170
.addr pattern_174
.addr pattern_158
.addr pattern_160
.addr pattern_171
.addr pattern_175
.addr pattern_157
.addr pattern_159
.addr pattern_172
.addr pattern_176
.addr pattern_158
.addr pattern_160
.addr pattern_177
.addr pattern_181
.addr pattern_157
.addr pattern_159
.addr pattern_178
.addr pattern_182
.addr pattern_158
.addr pattern_160
.addr pattern_179
.addr pattern_183
.addr pattern_157
.addr pattern_159
.addr pattern_180
.addr pattern_1
.addr pattern_158
.addr pattern_160
track_4:
.addr pattern_213
.addr pattern_1
.addr pattern_218
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_219
.addr pattern_1
.addr pattern_214
.addr pattern_1
.addr pattern_220
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_221
.addr pattern_1
.addr pattern_215
.addr pattern_1
.addr pattern_222
.addr pattern_1
.addr pattern_214
.addr pattern_1
.addr pattern_223
.addr pattern_1
.addr pattern_216
.addr pattern_1
.addr pattern_224
.addr pattern_1
.addr pattern_217
.addr pattern_1
.addr pattern_225
.addr pattern_1
.addr pattern_213
.addr pattern_1
.addr pattern_218
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_219
.addr pattern_1
.addr pattern_214
.addr pattern_1
.addr pattern_220
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_221
.addr pattern_1
.addr pattern_215
.addr pattern_1
.addr pattern_222
.addr pattern_1
.addr pattern_214
.addr pattern_1
.addr pattern_226
.addr pattern_1
.addr pattern_216
.addr pattern_1
.addr pattern_227
.addr pattern_1
.addr pattern_217
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_213
.addr pattern_228
.addr pattern_218
.addr pattern_1
.addr pattern_1
.addr pattern_229
.addr pattern_219
.addr pattern_1
.addr pattern_214
.addr pattern_230
.addr pattern_236
.addr pattern_1
.addr pattern_1
.addr pattern_231
.addr pattern_237
.addr pattern_1
.addr pattern_215
.addr pattern_232
.addr pattern_238
.addr pattern_1
.addr pattern_214
.addr pattern_233
.addr pattern_239
.addr pattern_1
.addr pattern_216
.addr pattern_234
.addr pattern_240
.addr pattern_1
.addr pattern_217
.addr pattern_235
.addr pattern_241
.addr pattern_1
.addr pattern_213
.addr pattern_242
.addr pattern_250
.addr pattern_1
.addr pattern_1
.addr pattern_243
.addr pattern_250
.addr pattern_1
.addr pattern_214
.addr pattern_244
.addr pattern_236
.addr pattern_1
.addr pattern_1
.addr pattern_245
.addr pattern_221
.addr pattern_1
.addr pattern_215
.addr pattern_246
.addr pattern_251
.addr pattern_1
.addr pattern_214
.addr pattern_247
.addr pattern_252
.addr pattern_1
.addr pattern_216
.addr pattern_248
.addr pattern_253
.addr pattern_1
.addr pattern_217
.addr pattern_249
.addr pattern_254
.addr pattern_1
.addr pattern_255
.addr pattern_259
.addr pattern_0
.addr pattern_1
.addr pattern_256
.addr pattern_260
.addr pattern_1
.addr pattern_1
.addr pattern_257
.addr pattern_261
.addr pattern_1
.addr pattern_1
.addr pattern_258
.addr pattern_262
.addr pattern_1
.addr pattern_1
.addr pattern_213
.addr pattern_263
.addr pattern_267
.addr pattern_1
.addr pattern_1
.addr pattern_264
.addr pattern_268
.addr pattern_1
.addr pattern_214
.addr pattern_263
.addr pattern_269
.addr pattern_1
.addr pattern_1
.addr pattern_264
.addr pattern_270
.addr pattern_1
.addr pattern_215
.addr pattern_232
.addr pattern_238
.addr pattern_1
.addr pattern_214
.addr pattern_263
.addr pattern_271
.addr pattern_1
.addr pattern_216
.addr pattern_265
.addr pattern_272
.addr pattern_1
.addr pattern_217
.addr pattern_266
.addr pattern_273
.addr pattern_1
.addr pattern_213
.addr pattern_242
.addr pattern_277
.addr pattern_1
.addr pattern_1
.addr pattern_274
.addr pattern_278
.addr pattern_1
.addr pattern_214
.addr pattern_275
.addr pattern_279
.addr pattern_1
.addr pattern_1
.addr pattern_276
.addr pattern_280
.addr pattern_1
.addr pattern_215
.addr pattern_246
.addr pattern_251
.addr pattern_1
.addr pattern_214
.addr pattern_247
.addr pattern_252
.addr pattern_1
.addr pattern_216
.addr pattern_248
.addr pattern_253
.addr pattern_1
.addr pattern_217
.addr pattern_249
.addr pattern_254
.addr pattern_1
.addr pattern_217
.addr pattern_281
.addr pattern_0
.addr pattern_1
.addr pattern_1
.addr pattern_282
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_283
.addr pattern_286
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_190
.addr pattern_284
.addr pattern_100
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_287
.addr pattern_1
.addr pattern_1
.addr pattern_285
.addr pattern_288
.addr pattern_1
.addr pattern_190
.addr pattern_281
.addr pattern_100
.addr pattern_1
.addr pattern_289
.addr pattern_282
.addr pattern_294
.addr pattern_1
.addr pattern_290
.addr pattern_283
.addr pattern_295
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_237
.addr pattern_1
.addr pattern_291
.addr pattern_1
.addr pattern_94
.addr pattern_1
.addr pattern_292
.addr pattern_1
.addr pattern_296
.addr pattern_1
.addr pattern_293
.addr pattern_1
.addr pattern_297
.addr pattern_1
.addr pattern_197
.addr pattern_1
.addr pattern_298
.addr pattern_1
.addr pattern_299
.addr pattern_281
.addr pattern_100
.addr pattern_1
.addr pattern_300
.addr pattern_282
.addr pattern_294
.addr pattern_1
.addr pattern_301
.addr pattern_283
.addr pattern_295
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_237
.addr pattern_1
.addr pattern_302
.addr pattern_1
.addr pattern_94
.addr pattern_1
.addr pattern_303
.addr pattern_1
.addr pattern_296
.addr pattern_1
.addr pattern_304
.addr pattern_1
.addr pattern_297
.addr pattern_1
.addr pattern_305
.addr pattern_1
.addr pattern_306
.addr pattern_1
.addr pattern_307
.addr pattern_281
.addr pattern_100
.addr pattern_1
.addr pattern_308
.addr pattern_282
.addr pattern_294
.addr pattern_1
.addr pattern_309
.addr pattern_283
.addr pattern_295
.addr pattern_1
.addr pattern_310
.addr pattern_1
.addr pattern_237
.addr pattern_1
.addr pattern_311
.addr pattern_1
.addr pattern_314
.addr pattern_1
.addr pattern_312
.addr pattern_1
.addr pattern_315
.addr pattern_1
.addr pattern_313
.addr pattern_1
.addr pattern_316
.addr pattern_1
.addr pattern_190
.addr pattern_1
.addr pattern_100
.addr pattern_1
.addr pattern_213
.addr pattern_1
.addr pattern_317
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_214
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_215
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_214
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_216
.addr pattern_1
.addr pattern_0
.addr pattern_1
.addr pattern_217
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_213
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_214
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_215
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_214
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_216
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_217
.addr pattern_1
.addr pattern_1
.addr pattern_1
track_5:
.addr pattern_318
.addr pattern_325
.addr pattern_332
.addr pattern_1
.addr pattern_319
.addr pattern_326
.addr pattern_333
.addr pattern_1
.addr pattern_318
.addr pattern_325
.addr pattern_332
.addr pattern_1
.addr pattern_320
.addr pattern_327
.addr pattern_333
.addr pattern_1
.addr pattern_321
.addr pattern_328
.addr pattern_334
.addr pattern_1
.addr pattern_322
.addr pattern_329
.addr pattern_335
.addr pattern_1
.addr pattern_323
.addr pattern_330
.addr pattern_336
.addr pattern_1
.addr pattern_324
.addr pattern_331
.addr pattern_337
.addr pattern_1
.addr pattern_318
.addr pattern_339
.addr pattern_332
.addr pattern_1
.addr pattern_319
.addr pattern_340
.addr pattern_333
.addr pattern_1
.addr pattern_318
.addr pattern_341
.addr pattern_332
.addr pattern_1
.addr pattern_320
.addr pattern_342
.addr pattern_333
.addr pattern_1
.addr pattern_321
.addr pattern_343
.addr pattern_334
.addr pattern_1
.addr pattern_322
.addr pattern_344
.addr pattern_335
.addr pattern_1
.addr pattern_323
.addr pattern_345
.addr pattern_336
.addr pattern_1
.addr pattern_338
.addr pattern_346
.addr pattern_337
.addr pattern_1
.addr pattern_318
.addr pattern_339
.addr pattern_332
.addr pattern_1
.addr pattern_319
.addr pattern_348
.addr pattern_333
.addr pattern_1
.addr pattern_318
.addr pattern_341
.addr pattern_332
.addr pattern_1
.addr pattern_320
.addr pattern_342
.addr pattern_333
.addr pattern_1
.addr pattern_321
.addr pattern_349
.addr pattern_334
.addr pattern_1
.addr pattern_322
.addr pattern_350
.addr pattern_335
.addr pattern_1
.addr pattern_323
.addr pattern_345
.addr pattern_336
.addr pattern_1
.addr pattern_347
.addr pattern_351
.addr pattern_337
.addr pattern_1
.addr pattern_352
.addr pattern_360
.addr pattern_332
.addr pattern_1
.addr pattern_353
.addr pattern_361
.addr pattern_368
.addr pattern_1
.addr pattern_354
.addr pattern_362
.addr pattern_334
.addr pattern_1
.addr pattern_355
.addr pattern_363
.addr pattern_369
.addr pattern_1
.addr pattern_356
.addr pattern_364
.addr pattern_370
.addr pattern_1
.addr pattern_357
.addr pattern_365
.addr pattern_371
.addr pattern_1
.addr pattern_358
.addr pattern_366
.addr pattern_372
.addr pattern_1
.addr pattern_359
.addr pattern_367
.addr pattern_373
.addr pattern_1
.addr pattern_374
.addr pattern_377
.addr pattern_0
.addr pattern_1
.addr pattern_374
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_375
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_376
.addr pattern_1
.addr pattern_378
.addr pattern_1
.addr pattern_374
.addr pattern_1
.addr pattern_379
.addr pattern_1
.addr pattern_374
.addr pattern_1
.addr pattern_379
.addr pattern_1
.addr pattern_375
.addr pattern_1
.addr pattern_380
.addr pattern_1
.addr pattern_376
.addr pattern_1
.addr pattern_381
.addr pattern_1
.addr pattern_374
.addr pattern_383
.addr pattern_391
.addr pattern_1
.addr pattern_374
.addr pattern_384
.addr pattern_379
.addr pattern_1
.addr pattern_375
.addr pattern_385
.addr pattern_380
.addr pattern_1
.addr pattern_376
.addr pattern_386
.addr pattern_392
.addr pattern_1
.addr pattern_374
.addr pattern_387
.addr pattern_379
.addr pattern_1
.addr pattern_374
.addr pattern_388
.addr pattern_379
.addr pattern_1
.addr pattern_375
.addr pattern_389
.addr pattern_380
.addr pattern_1
.addr pattern_382
.addr pattern_390
.addr pattern_393
.addr pattern_1
.addr pattern_394
.addr pattern_400
.addr pattern_391
.addr pattern_1
.addr pattern_394
.addr pattern_401
.addr pattern_379
.addr pattern_1
.addr pattern_395
.addr pattern_402
.addr pattern_380
.addr pattern_1
.addr pattern_396
.addr pattern_403
.addr pattern_392
.addr pattern_1
.addr pattern_397
.addr pattern_400
.addr pattern_379
.addr pattern_1
.addr pattern_397
.addr pattern_401
.addr pattern_379
.addr pattern_1
.addr pattern_398
.addr pattern_402
.addr pattern_380
.addr pattern_1
.addr pattern_399
.addr pattern_404
.addr pattern_393
.addr pattern_1
.addr pattern_405
.addr pattern_407
.addr pattern_391
.addr pattern_1
.addr pattern_405
.addr pattern_408
.addr pattern_379
.addr pattern_1
.addr pattern_375
.addr pattern_409
.addr pattern_380
.addr pattern_1
.addr pattern_376
.addr pattern_410
.addr pattern_392
.addr pattern_1
.addr pattern_374
.addr pattern_411
.addr pattern_379
.addr pattern_1
.addr pattern_374
.addr pattern_408
.addr pattern_379
.addr pattern_1
.addr pattern_375
.addr pattern_409
.addr pattern_380
.addr pattern_1
.addr pattern_406
.addr pattern_412
.addr pattern_393
.addr pattern_1
.addr pattern_405
.addr pattern_413
.addr pattern_391
.addr pattern_1
.addr pattern_405
.addr pattern_414
.addr pattern_379
.addr pattern_1
.addr pattern_375
.addr pattern_415
.addr pattern_380
.addr pattern_1
.addr pattern_376
.addr pattern_416
.addr pattern_381
.addr pattern_1
.addr pattern_405
.addr pattern_377
.addr pattern_417
.addr pattern_1
.addr pattern_405
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_375
.addr pattern_1
.addr pattern_0
.addr pattern_1
.addr pattern_376
.addr pattern_1
.addr pattern_418
.addr pattern_1
.addr pattern_374
.addr pattern_419
.addr pattern_391
.addr pattern_1
.addr pattern_374
.addr pattern_420
.addr pattern_379
.addr pattern_1
.addr pattern_375
.addr pattern_421
.addr pattern_380
.addr pattern_1
.addr pattern_376
.addr pattern_422
.addr pattern_381
.addr pattern_1
.addr pattern_374
.addr pattern_423
.addr pattern_391
.addr pattern_1
.addr pattern_374
.addr pattern_424
.addr pattern_379
.addr pattern_1
.addr pattern_375
.addr pattern_425
.addr pattern_380
.addr pattern_1
.addr pattern_376
.addr pattern_426
.addr pattern_381
.addr pattern_1
.addr pattern_394
.addr pattern_429
.addr pattern_391
.addr pattern_1
.addr pattern_394
.addr pattern_430
.addr pattern_379
.addr pattern_1
.addr pattern_395
.addr pattern_431
.addr pattern_380
.addr pattern_1
.addr pattern_396
.addr pattern_346
.addr pattern_392
.addr pattern_1
.addr pattern_427
.addr pattern_432
.addr pattern_379
.addr pattern_1
.addr pattern_427
.addr pattern_433
.addr pattern_379
.addr pattern_1
.addr pattern_395
.addr pattern_434
.addr pattern_380
.addr pattern_1
.addr pattern_428
.addr pattern_435
.addr pattern_393
.addr pattern_1
.addr pattern_436
.addr pattern_441
.addr pattern_391
.addr pattern_1
.addr pattern_436
.addr pattern_442
.addr pattern_379
.addr pattern_1
.addr pattern_437
.addr pattern_443
.addr pattern_446
.addr pattern_1
.addr pattern_438
.addr pattern_444
.addr pattern_381
.addr pattern_1
.addr pattern_439
.addr pattern_441
.addr pattern_379
.addr pattern_1
.addr pattern_439
.addr pattern_442
.addr pattern_379
.addr pattern_1
.addr pattern_437
.addr pattern_443
.addr pattern_446
.addr pattern_1
.addr pattern_440
.addr pattern_445
.addr pattern_447
.addr pattern_1
.addr pattern_405
.addr pattern_407
.addr pattern_391
.addr pattern_1
.addr pattern_405
.addr pattern_408
.addr pattern_379
.addr pattern_1
.addr pattern_375
.addr pattern_409
.addr pattern_380
.addr pattern_1
.addr pattern_376
.addr pattern_410
.addr pattern_392
.addr pattern_1
.addr pattern_374
.addr pattern_411
.addr pattern_379
.addr pattern_1
.addr pattern_374
.addr pattern_408
.addr pattern_379
.addr pattern_1
.addr pattern_375
.addr pattern_409
.addr pattern_380
.addr pattern_1
.addr pattern_406
.addr pattern_412
.addr pattern_393
.addr pattern_1
.addr pattern_405
.addr pattern_413
.addr pattern_391
.addr pattern_1
.addr pattern_405
.addr pattern_414
.addr pattern_379
.addr pattern_1
.addr pattern_375
.addr pattern_415
.addr pattern_380
.addr pattern_1
.addr pattern_376
.addr pattern_416
.addr pattern_381
.addr pattern_1
.addr pattern_448
.addr pattern_377
.addr pattern_417
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_449
.addr pattern_450
.addr pattern_451
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_1
.addr pattern_1
track_6:
.addr pattern_452
.addr pattern_458
.addr pattern_464
.addr pattern_1
.addr pattern_453
.addr pattern_459
.addr pattern_465
.addr pattern_1
.addr pattern_454
.addr pattern_460
.addr pattern_466
.addr pattern_1
.addr pattern_455
.addr pattern_461
.addr pattern_467
.addr pattern_1
.addr pattern_456
.addr pattern_462
.addr pattern_468
.addr pattern_1
.addr pattern_457
.addr pattern_463
.addr pattern_469
.addr pattern_1
.addr pattern_470
.addr pattern_473
.addr pattern_479
.addr pattern_1
.addr pattern_471
.addr pattern_474
.addr pattern_480
.addr pattern_1
.addr pattern_472
.addr pattern_475
.addr pattern_481
.addr pattern_1
.addr pattern_455
.addr pattern_476
.addr pattern_482
.addr pattern_1
.addr pattern_456
.addr pattern_477
.addr pattern_483
.addr pattern_1
.addr pattern_457
.addr pattern_478
.addr pattern_484
.addr pattern_1
.addr pattern_470
.addr pattern_473
.addr pattern_485
.addr pattern_1
.addr pattern_471
.addr pattern_474
.addr pattern_1
.addr pattern_1
.addr pattern_472
.addr pattern_475
.addr pattern_486
.addr pattern_1
.addr pattern_455
.addr pattern_476
.addr pattern_487
.addr pattern_1
.addr pattern_456
.addr pattern_477
.addr pattern_466
.addr pattern_1
.addr pattern_457
.addr pattern_478
.addr pattern_488
.addr pattern_1
.addr pattern_470
.addr pattern_473
.addr pattern_295
.addr pattern_1
.addr pattern_471
.addr pattern_474
.addr pattern_1
.addr pattern_1
.addr pattern_472
.addr pattern_475
.addr pattern_489
.addr pattern_1
.addr pattern_455
.addr pattern_476
.addr pattern_487
.addr pattern_1
.addr pattern_456
.addr pattern_477
.addr pattern_490
.addr pattern_1
.addr pattern_457
.addr pattern_478
.addr pattern_491
.addr pattern_1
.addr pattern_470
.addr pattern_473
.addr pattern_492
.addr pattern_1
.addr pattern_471
.addr pattern_474
.addr pattern_493
.addr pattern_1
.addr pattern_472
.addr pattern_475
.addr pattern_494
.addr pattern_1
.addr pattern_455
.addr pattern_476
.addr pattern_495
.addr pattern_1
.addr pattern_456
.addr pattern_477
.addr pattern_496
.addr pattern_1
.addr pattern_457
.addr pattern_478
.addr pattern_497
.addr pattern_1
.addr pattern_470
.addr pattern_473
.addr pattern_485
.addr pattern_1
.addr pattern_471
.addr pattern_474
.addr pattern_1
.addr pattern_1
.addr pattern_472
.addr pattern_475
.addr pattern_486
.addr pattern_1
.addr pattern_455
.addr pattern_476
.addr pattern_498
.addr pattern_1
.addr pattern_456
.addr pattern_477
.addr pattern_499
.addr pattern_1
.addr pattern_457
.addr pattern_478
.addr pattern_500
.addr pattern_1
.addr pattern_470
.addr pattern_473
.addr pattern_501
.addr pattern_1
.addr pattern_471
.addr pattern_474
.addr pattern_502
.addr pattern_1
.addr pattern_472
.addr pattern_475
.addr pattern_503
.addr pattern_1
.addr pattern_455
.addr pattern_476
.addr pattern_504
.addr pattern_1
.addr pattern_456
.addr pattern_477
.addr pattern_505
.addr pattern_1
.addr pattern_457
.addr pattern_478
.addr pattern_506
.addr pattern_1
.addr pattern_470
.addr pattern_473
.addr pattern_501
.addr pattern_1
.addr pattern_471
.addr pattern_474
.addr pattern_502
.addr pattern_1
.addr pattern_472
.addr pattern_475
.addr pattern_503
.addr pattern_1
.addr pattern_455
.addr pattern_476
.addr pattern_504
.addr pattern_1
.addr pattern_456
.addr pattern_477
.addr pattern_505
.addr pattern_1
.addr pattern_457
.addr pattern_478
.addr pattern_507
.addr pattern_1
.addr pattern_470
.addr pattern_473
.addr pattern_509
.addr pattern_1
.addr pattern_471
.addr pattern_474
.addr pattern_510
.addr pattern_1
.addr pattern_472
.addr pattern_475
.addr pattern_511
.addr pattern_1
.addr pattern_508
.addr pattern_476
.addr pattern_512
.addr pattern_1
.addr pattern_456
.addr pattern_477
.addr pattern_513
.addr pattern_1
.addr pattern_457
.addr pattern_478
.addr pattern_514
.addr pattern_1
.addr pattern_470
.addr pattern_473
.addr pattern_295
.addr pattern_1
.addr pattern_471
.addr pattern_474
.addr pattern_1
.addr pattern_1
.addr pattern_472
.addr pattern_475
.addr pattern_515
.addr pattern_1
.addr pattern_455
.addr pattern_476
.addr pattern_516
.addr pattern_1
.addr pattern_456
.addr pattern_477
.addr pattern_466
.addr pattern_1
.addr pattern_457
.addr pattern_478
.addr pattern_517
.addr pattern_1
.addr pattern_518
.addr pattern_473
.addr pattern_526
.addr pattern_1
.addr pattern_519
.addr pattern_524
.addr pattern_527
.addr pattern_1
.addr pattern_520
.addr pattern_476
.addr pattern_528
.addr pattern_1
.addr pattern_521
.addr pattern_475
.addr pattern_529
.addr pattern_1
.addr pattern_522
.addr pattern_525
.addr pattern_499
.addr pattern_1
.addr pattern_523
.addr pattern_478
.addr pattern_530
.addr pattern_1
.addr pattern_470
.addr pattern_473
.addr pattern_526
.addr pattern_1
.addr pattern_531
.addr pattern_524
.addr pattern_527
.addr pattern_1
.addr pattern_532
.addr pattern_476
.addr pattern_528
.addr pattern_1
.addr pattern_533
.addr pattern_475
.addr pattern_529
.addr pattern_1
.addr pattern_534
.addr pattern_525
.addr pattern_499
.addr pattern_1
.addr pattern_457
.addr pattern_478
.addr pattern_535
.addr pattern_1
.addr pattern_470
.addr pattern_473
.addr pattern_536
.addr pattern_1
.addr pattern_531
.addr pattern_524
.addr pattern_537
.addr pattern_1
.addr pattern_532
.addr pattern_476
.addr pattern_538
.addr pattern_1
.addr pattern_533
.addr pattern_475
.addr pattern_539
.addr pattern_1
.addr pattern_534
.addr pattern_525
.addr pattern_540
.addr pattern_1
.addr pattern_457
.addr pattern_478
.addr pattern_541
.addr pattern_1
.addr pattern_470
.addr pattern_473
.addr pattern_295
.addr pattern_1
.addr pattern_471
.addr pattern_474
.addr pattern_1
.addr pattern_1
.addr pattern_472
.addr pattern_475
.addr pattern_1
.addr pattern_1
.addr pattern_455
.addr pattern_476
.addr pattern_542
.addr pattern_1
.addr pattern_456
.addr pattern_477
.addr pattern_466
.addr pattern_1
.addr pattern_457
.addr pattern_478
.addr pattern_517
.addr pattern_1
.addr pattern_518
.addr pattern_473
.addr pattern_547
.addr pattern_1
.addr pattern_543
.addr pattern_474
.addr pattern_548
.addr pattern_1
.addr pattern_544
.addr pattern_475
.addr pattern_549
.addr pattern_1
.addr pattern_545
.addr pattern_476
.addr pattern_550
.addr pattern_1
.addr pattern_546
.addr pattern_477
.addr pattern_499
.addr pattern_1
.addr pattern_523
.addr pattern_478
.addr pattern_551
.addr pattern_1
.addr pattern_470
.addr pattern_473
.addr pattern_547
.addr pattern_1
.addr pattern_471
.addr pattern_474
.addr pattern_548
.addr pattern_1
.addr pattern_472
.addr pattern_475
.addr pattern_549
.addr pattern_1
.addr pattern_455
.addr pattern_476
.addr pattern_550
.addr pattern_1
.addr pattern_456
.addr pattern_477
.addr pattern_499
.addr pattern_1
.addr pattern_457
.addr pattern_478
.addr pattern_552
.addr pattern_1
.addr pattern_470
.addr pattern_473
.addr pattern_553
.addr pattern_1
.addr pattern_471
.addr pattern_474
.addr pattern_221
.addr pattern_1
.addr pattern_472
.addr pattern_475
.addr pattern_554
.addr pattern_1
.addr pattern_455
.addr pattern_476
.addr pattern_555
.addr pattern_1
.addr pattern_456
.addr pattern_477
.addr pattern_556
.addr pattern_1
.addr pattern_457
.addr pattern_478
.addr pattern_557
.addr pattern_1
.addr pattern_470
.addr pattern_458
.addr pattern_560
.addr pattern_1
.addr pattern_471
.addr pattern_459
.addr pattern_1
.addr pattern_1
.addr pattern_472
.addr pattern_460
.addr pattern_1
.addr pattern_1
.addr pattern_558
.addr pattern_461
.addr pattern_0
.addr pattern_1
.addr pattern_559
.addr pattern_462
.addr pattern_1
.addr pattern_1
.addr pattern_457
.addr pattern_463
.addr pattern_1
.addr pattern_1
tracks_end:
; size = 256
.align 256
macro_26:
.byt .lobyte(61)
.byt .lobyte(61)
.byt .lobyte(190)
.byt .lobyte(190)
.byt .lobyte(190)
.byt .lobyte(190)
.byt .lobyte(190)
.byt .lobyte(190)
.byt .lobyte(190)
.byt .lobyte(190)
.byt .lobyte(190)
.byt .lobyte(189)
.byt .lobyte(189)
.byt .lobyte(189)
.byt .lobyte(189)
.byt .lobyte(188)
.byt .lobyte(188)
.byt .lobyte(188)
.byt .lobyte(188)
.byt .lobyte(187)
.byt .lobyte(187)
.byt .lobyte(187)
.byt .lobyte(187)
.byt .lobyte(187)
.byt .lobyte(187)
.byt .lobyte(187)
.byt .lobyte(187)
.byt .lobyte(187)
.byt .lobyte(187)
.byt .lobyte(187)
.byt .lobyte(187)
.byt .lobyte(186)
.byt .lobyte(186)
.byt .lobyte(186)
.byt .lobyte(186)
.byt .lobyte(185)
.byt .lobyte(185)
.byt .lobyte(185)
.byt .lobyte(185)
.byt .lobyte(185)
.byt .lobyte(185)
.byt .lobyte(185)
.byt .lobyte(185)
.byt .lobyte(185)
.byt .lobyte(185)
.byt .lobyte(185)
.byt .lobyte(185)
.byt .lobyte(185)
.byt .lobyte(185)
.byt .lobyte(184)
.byt .lobyte(184)
.byt .lobyte(184)
.byt .lobyte(184)
.byt .lobyte(184)
.byt .lobyte(184)
.byt .lobyte(184)
.byt .lobyte(184)
.byt .lobyte(184)
.byt .lobyte(184)
.byt .lobyte(184)
.byt .lobyte(184)
.byt .lobyte(184)
.byt .lobyte(184)
.byt .lobyte(184)
.byt .lobyte(184)
.byt .lobyte(184)
.byt .lobyte(184)
.byt .lobyte(183)
.byt .lobyte(183)
.byt .lobyte(183)
.byt .lobyte(183)
.byt .lobyte(183)
.byt .lobyte(183)
.byt .lobyte(183)
.byt .lobyte(183)
.byt .lobyte(183)
.byt .lobyte(183)
.byt .lobyte(183)
.byt .lobyte(183)
.byt .lobyte(183)
.byt .lobyte(183)
.byt .lobyte(183)
.byt .lobyte(182)
.byt .lobyte(182)
.byt .lobyte(182)
.byt .lobyte(182)
.byt .lobyte(182)
.byt .lobyte(182)
.byt .lobyte(182)
.byt .lobyte(182)
.byt .lobyte(182)
.byt .lobyte(182)
.byt .lobyte(182)
.byt .lobyte(182)
.byt .lobyte(182)
.byt .lobyte(182)
.byt .lobyte(181)
.byt .lobyte(181)
.byt .lobyte(181)
.byt .lobyte(181)
.byt .lobyte(181)
.byt .lobyte(181)
.byt .lobyte(181)
.byt .lobyte(181)
.byt .lobyte(181)
.byt .lobyte(181)
.byt .lobyte(181)
.byt .lobyte(181)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(179)
.byt .lobyte(179)
.byt .lobyte(179)
.byt .lobyte(179)
.byt .lobyte(179)
.byt .lobyte(179)
.byt .lobyte(179)
.byt .lobyte(179)
.byt .lobyte(179)
.byt .lobyte(179)
.byt .lobyte(179)
.byt .lobyte(179)
.byt .lobyte(179)
.byt .lobyte(179)
.byt .lobyte(179)
.byt .lobyte(179)
.byt .lobyte(179)
.byt .lobyte(179)
.byt .lobyte(178)
.byt .lobyte(178)
.byt .lobyte(178)
.byt .lobyte(178)
.byt .lobyte(178)
.byt .lobyte(178)
.byt .lobyte(178)
.byt .lobyte(178)
.byt .lobyte(178)
.byt .lobyte(178)
.byt .lobyte(178)
.byt .lobyte(178)
.byt .lobyte(178)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(176)
.byt .lobyte(176)
macro_4:
.byt .lobyte(121)
.byt .lobyte(123)
.byt .lobyte(124)
.byt .lobyte(187)
.byt .lobyte(186)
.byt .lobyte(185)
.byt .lobyte(184)
.byt .lobyte(183)
.byt .lobyte(182)
.byt .lobyte(181)
.byt .lobyte(180)
.byt .lobyte(179)
.byt .lobyte(178)
.byt .lobyte(178)
.byt .lobyte(179)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(179)
.byt .lobyte(178)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(178)
.byt .lobyte(178)
.byt .lobyte(178)
.byt .lobyte(178)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(176)
macro_35:
.byt .lobyte(54)
.byt .lobyte(60)
.byt .lobyte(58)
.byt .lobyte(56)
.byt .lobyte(54)
.byt .lobyte(53)
.byt .lobyte(54)
.byt .lobyte(52)
.byt .lobyte(51)
.byt .lobyte(50)
.byt .lobyte(50)
.byt .lobyte(51)
.byt .lobyte(50)
.byt .lobyte(50)
.byt .lobyte(49)
.byt .lobyte(49)
.byt .lobyte(48)
.byt .lobyte(49)
.byt .lobyte(48)
; size = 256
.align 256
macro_2:
.byt .lobyte(53)
.byt .lobyte(60)
.byt .lobyte(63)
.byt .lobyte(63)
.byt .lobyte(189)
.byt .lobyte(188)
.byt .lobyte(187)
.byt .lobyte(58)
.byt .lobyte(58)
.byt .lobyte(57)
.byt .lobyte(57)
.byt .lobyte(185)
.byt .lobyte(184)
.byt .lobyte(184)
.byt .lobyte(55)
.byt .lobyte(55)
.byt .lobyte(55)
.byt .lobyte(54)
.byt .lobyte(182)
.byt .lobyte(182)
.byt .lobyte(181)
.byt .lobyte(53)
.byt .lobyte(53)
.byt .lobyte(53)
.byt .lobyte(53)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(52)
.byt .lobyte(52)
.byt .lobyte(52)
.byt .lobyte(52)
.byt .lobyte(179)
.byt .lobyte(179)
.byt .lobyte(179)
.byt .lobyte(51)
.byt .lobyte(51)
.byt .lobyte(51)
.byt .lobyte(51)
.byt .lobyte(179)
.byt .lobyte(179)
.byt .lobyte(179)
.byt .lobyte(51)
.byt .lobyte(50)
.byt .lobyte(50)
.byt .lobyte(50)
.byt .lobyte(178)
.byt .lobyte(178)
.byt .lobyte(178)
.byt .lobyte(50)
.byt .lobyte(50)
.byt .lobyte(50)
.byt .lobyte(50)
.byt .lobyte(178)
.byt .lobyte(178)
.byt .lobyte(178)
.byt .lobyte(50)
.byt .lobyte(50)
.byt .lobyte(50)
.byt .lobyte(50)
.byt .lobyte(178)
.byt .lobyte(178)
.byt .lobyte(178)
.byt .lobyte(50)
.byt .lobyte(49)
.byt .lobyte(49)
.byt .lobyte(49)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(176)
.byt .lobyte(48)
.byt .lobyte(48)
.byt .lobyte(48)
.byt .lobyte(48)
.byt .lobyte(176)
.byt .lobyte(176)
macro_11:
.byt .lobyte(191)
.byt .lobyte(191)
.byt .lobyte(191)
.byt .lobyte(190)
.byt .lobyte(189)
.byt .lobyte(188)
.byt .lobyte(187)
.byt .lobyte(186)
.byt .lobyte(185)
.byt .lobyte(184)
.byt .lobyte(183)
.byt .lobyte(183)
.byt .lobyte(184)
.byt .lobyte(185)
.byt .lobyte(186)
.byt .lobyte(187)
.byt .lobyte(187)
.byt .lobyte(187)
.byt .lobyte(188)
.byt .lobyte(188)
.byt .lobyte(188)
.byt .lobyte(187)
.byt .lobyte(187)
.byt .lobyte(186)
.byt .lobyte(186)
.byt .lobyte(185)
.byt .lobyte(184)
.byt .lobyte(183)
.byt .lobyte(182)
.byt .lobyte(181)
.byt .lobyte(181)
.byt .lobyte(181)
.byt .lobyte(182)
.byt .lobyte(182)
.byt .lobyte(183)
.byt .lobyte(183)
.byt .lobyte(183)
.byt .lobyte(184)
.byt .lobyte(184)
.byt .lobyte(184)
.byt .lobyte(184)
.byt .lobyte(183)
.byt .lobyte(183)
.byt .lobyte(182)
.byt .lobyte(182)
.byt .lobyte(181)
.byt .lobyte(181)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(179)
.byt .lobyte(179)
.byt .lobyte(179)
.byt .lobyte(179)
.byt .lobyte(179)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(180)
.byt .lobyte(179)
.byt .lobyte(179)
.byt .lobyte(179)
.byt .lobyte(178)
.byt .lobyte(178)
.byt .lobyte(178)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(177)
.byt .lobyte(176)
macro_7:
.byt .lobyte(185)
.byt .lobyte(187)
.byt .lobyte(188)
.byt .lobyte(123)
.byt .lobyte(122)
.byt .lobyte(121)
.byt .lobyte(120)
.byt .lobyte(119)
.byt .lobyte(118)
.byt .lobyte(117)
.byt .lobyte(116)
.byt .lobyte(115)
.byt .lobyte(114)
.byt .lobyte(114)
.byt .lobyte(115)
.byt .lobyte(116)
.byt .lobyte(116)
.byt .lobyte(116)
.byt .lobyte(115)
.byt .lobyte(114)
.byt .lobyte(113)
.byt .lobyte(113)
.byt .lobyte(113)
.byt .lobyte(114)
.byt .lobyte(114)
.byt .lobyte(114)
.byt .lobyte(114)
.byt .lobyte(113)
.byt .lobyte(113)
.byt .lobyte(112)
macro_33:
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(2)
.byt .lobyte(3)
.byt .lobyte(-3)
.byt .lobyte(-2)
.byt .lobyte(-2)
.byt .lobyte(-3)
.byt .lobyte(3)
.byt .lobyte(2)
macro_10:
.byt .lobyte(115)
.byt .lobyte(120)
.byt .lobyte(60)
.byt .lobyte(57)
.byt .lobyte(55)
.byt .lobyte(54)
.byt .lobyte(54)
.byt .lobyte(53)
.byt .lobyte(53)
.byt .lobyte(53)
.byt .lobyte(53)
.byt .lobyte(52)
.byt .lobyte(52)
.byt .lobyte(52)
.byt .lobyte(52)
.byt .lobyte(52)
.byt .lobyte(52)
.byt .lobyte(52)
.byt .lobyte(51)
.byt .lobyte(51)
.byt .lobyte(51)
.byt .lobyte(51)
.byt .lobyte(51)
.byt .lobyte(50)
macro_12:
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(1)
.byt .lobyte(1)
.byt .lobyte(-1)
.byt .lobyte(-1)
.byt .lobyte(-1)
.byt .lobyte(-1)
.byt .lobyte(1)
.byt .lobyte(1)
pattern_344:
.byt 16
.byt 4, 64
; size = 256
.align 256
macro_24:
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(1)
.byt .lobyte(2)
.byt .lobyte(-2)
.byt .lobyte(-1)
.byt .lobyte(-1)
.byt .lobyte(-2)
.byt .lobyte(2)
.byt .lobyte(1)
macro_37:
.byt .lobyte(56)
.byt .lobyte(54)
.byt .lobyte(54)
.byt .lobyte(53)
.byt .lobyte(53)
.byt .lobyte(53)
.byt .lobyte(52)
.byt .lobyte(52)
.byt .lobyte(51)
.byt .lobyte(51)
.byt .lobyte(51)
.byt .lobyte(50)
.byt .lobyte(50)
.byt .lobyte(50)
.byt .lobyte(49)
.byt .lobyte(49)
.byt .lobyte(49)
.byt .lobyte(48)
square2_instrument_hi:
.byt .hibyte(square2_instrument_0_arpeggio)
.byt .hibyte(square2_instrument_1_arpeggio)
.byt .hibyte(square2_instrument_2_arpeggio)
.byt .hibyte(square2_instrument_3_arpeggio)
.byt .hibyte(square2_instrument_4_arpeggio)
.byt .hibyte(square2_instrument_5_arpeggio)
.byt .hibyte(square2_instrument_6_arpeggio)
.byt .hibyte(square2_instrument_7_arpeggio)
.byt .hibyte(square2_instrument_8_arpeggio)
.byt .hibyte(square2_instrument_9_arpeggio)
.byt .hibyte(square2_instrument_10_arpeggio)
.byt .hibyte(square2_instrument_11_arpeggio)
.byt .hibyte(square2_instrument_12_arpeggio)
.byt .hibyte(square2_instrument_13_arpeggio)
.byt .hibyte(square2_instrument_14_arpeggio)
.byt .hibyte(square2_instrument_15_arpeggio)
.byt .hibyte(square2_instrument_16_arpeggio)
.byt .hibyte(square2_instrument_17_arpeggio)
square2_instrument_lo:
.byt .lobyte(square2_instrument_0_arpeggio)
.byt .lobyte(square2_instrument_1_arpeggio)
.byt .lobyte(square2_instrument_2_arpeggio)
.byt .lobyte(square2_instrument_3_arpeggio)
.byt .lobyte(square2_instrument_4_arpeggio)
.byt .lobyte(square2_instrument_5_arpeggio)
.byt .lobyte(square2_instrument_6_arpeggio)
.byt .lobyte(square2_instrument_7_arpeggio)
.byt .lobyte(square2_instrument_8_arpeggio)
.byt .lobyte(square2_instrument_9_arpeggio)
.byt .lobyte(square2_instrument_10_arpeggio)
.byt .lobyte(square2_instrument_11_arpeggio)
.byt .lobyte(square2_instrument_12_arpeggio)
.byt .lobyte(square2_instrument_13_arpeggio)
.byt .lobyte(square2_instrument_14_arpeggio)
.byt .lobyte(square2_instrument_15_arpeggio)
.byt .lobyte(square2_instrument_16_arpeggio)
.byt .lobyte(square2_instrument_17_arpeggio)
macro_30:
.byt .lobyte(190)
.byt .lobyte(190)
.byt .lobyte(190)
.byt .lobyte(191)
.byt .lobyte(191)
.byt .lobyte(191)
.byt .lobyte(191)
.byt .lobyte(191)
.byt .lobyte(191)
.byt .lobyte(190)
.byt .lobyte(189)
.byt .lobyte(188)
.byt .lobyte(187)
.byt .lobyte(184)
.byt .lobyte(181)
.byt .lobyte(178)
.byt .lobyte(177)
.byt .lobyte(176)
macro_28:
.byt .lobyte(126)
.byt .lobyte(126)
.byt .lobyte(126)
.byt .lobyte(63)
.byt .lobyte(63)
.byt .lobyte(63)
.byt .lobyte(63)
.byt .lobyte(63)
.byt .lobyte(63)
.byt .lobyte(62)
.byt .lobyte(61)
.byt .lobyte(60)
.byt .lobyte(59)
.byt .lobyte(56)
.byt .lobyte(53)
.byt .lobyte(50)
.byt .lobyte(49)
.byt .lobyte(48)
pattern_8:
.byt 255
.byt 0, 0
.byt 1, 28
.byt 0, 0
.byt 1, 28
.byt 1, 30
.byt 0, 0
.byt 1, 28
.byt 0, 0
pattern_434:
.byt 255
.byt 4, 72
.byt 0, 0
.byt 4, 68
.byt 0, 0
.byt 4, 64
.byt 0, 0
.byt 4, 72
.byt 4, 78
pattern_432:
.byt 255
.byt 4, 58
.byt 0, 0
.byt 4, 68
.byt 0, 0
.byt 4, 72
.byt 0, 0
.byt 4, 54
.byt 4, 52
pattern_3:
.byt 255
.byt 0, 0
.byt 1, 30
.byt 0, 0
.byt 1, 30
.byt 1, 30
.byt 0, 0
.byt 1, 30
.byt 0, 0
square1_instrument_hi:
.byt .hibyte(square1_instrument_0_arpeggio)
.byt .hibyte(square1_instrument_1_arpeggio)
.byt .hibyte(square1_instrument_2_arpeggio)
.byt .hibyte(square1_instrument_3_arpeggio)
.byt .hibyte(square1_instrument_4_arpeggio)
.byt .hibyte(square1_instrument_5_arpeggio)
.byt .hibyte(square1_instrument_6_arpeggio)
.byt .hibyte(square1_instrument_7_arpeggio)
.byt .hibyte(square1_instrument_8_arpeggio)
.byt .hibyte(square1_instrument_9_arpeggio)
.byt .hibyte(square1_instrument_10_arpeggio)
.byt .hibyte(square1_instrument_11_arpeggio)
.byt .hibyte(square1_instrument_12_arpeggio)
.byt .hibyte(square1_instrument_13_arpeggio)
.byt .hibyte(square1_instrument_14_arpeggio)
.byt .hibyte(square1_instrument_15_arpeggio)
.byt .hibyte(square1_instrument_16_arpeggio)
square1_instrument_lo:
.byt .lobyte(square1_instrument_0_arpeggio)
.byt .lobyte(square1_instrument_1_arpeggio)
.byt .lobyte(square1_instrument_2_arpeggio)
.byt .lobyte(square1_instrument_3_arpeggio)
.byt .lobyte(square1_instrument_4_arpeggio)
.byt .lobyte(square1_instrument_5_arpeggio)
.byt .lobyte(square1_instrument_6_arpeggio)
.byt .lobyte(square1_instrument_7_arpeggio)
.byt .lobyte(square1_instrument_8_arpeggio)
.byt .lobyte(square1_instrument_9_arpeggio)
.byt .lobyte(square1_instrument_10_arpeggio)
.byt .lobyte(square1_instrument_11_arpeggio)
.byt .lobyte(square1_instrument_12_arpeggio)
.byt .lobyte(square1_instrument_13_arpeggio)
.byt .lobyte(square1_instrument_14_arpeggio)
.byt .lobyte(square1_instrument_15_arpeggio)
.byt .lobyte(square1_instrument_16_arpeggio)
pattern_6:
.byt 255
.byt 0, 0
.byt 1, 34
.byt 0, 0
.byt 1, 34
.byt 1, 34
.byt 0, 0
.byt 1, 34
.byt 0, 0
square1_instrument_11_vol_duty:
    jsr square1_instrument_assign_return
    cpy #2
    bcc :+
    ldy #1
:   lda macro_17, y
    jmp square1_vol_duty_return
pattern_421:
.byt 69
.byt 4, 40
.byt 0, 0
.byt 4, 40
pattern_1:
.byt 0
; size = 256
.align 256
square2_instrument_6_pitch:
    jsr square2_instrument_6_vol_duty
    cpx #15
    bcc :+
    ldx #7
:   lda macro_3, x
    jmp square2_pitch_return
triangle_instrument_3_vol_duty:
    jsr triangle_instrument_assign_return
    cpy #2
    bcc :+
    ldy #1
:   lda macro_32, y
    jmp triangle_vol_duty_return
pattern_127:
.byt 127
.byt 2, 36
.byt 0, 0
.byt 2, 36
.byt 0, 0
.byt 2, 36
.byt 0, 0
.byt 4, 36
square1_instrument_10_pitch:
    jsr square1_instrument_10_vol_duty
    cpx #1
    bcc :+
    ldx #0
:   lda macro_1, x
    jmp square1_pitch_return
triangle_instrument_2_pitch:
    jsr triangle_instrument_2_vol_duty
    cpx #15
    bcc :+
    ldx #7
:   lda macro_3, x
    jmp triangle_pitch_return
square1_instrument_15_vol_duty:
    jsr square1_instrument_assign_return
    cpy #5
    bcc :+
    ldy #4
:   lda macro_20, y
    jmp square1_vol_duty_return
square1_instrument_11_pitch:
    jsr square1_instrument_11_vol_duty
    cpx #1
    bcc :+
    ldx #0
:   lda macro_1, x
    jmp square1_pitch_return
triangle_instrument_2_vol_duty:
    jsr triangle_instrument_assign_return
    cpy #76
    bcc :+
    ldy #69
:   lda macro_2, y
    jmp triangle_vol_duty_return
square1_instrument_12_vol_duty:
    jsr square1_instrument_assign_return
    cpy #2
    bcc :+
    ldy #1
:   lda macro_17, y
    jmp square1_vol_duty_return
square1_instrument_12_pitch:
    jsr square1_instrument_12_vol_duty
    cpx #1
    bcc :+
    ldx #0
:   lda macro_1, x
    jmp square1_pitch_return
square1_instrument_13_vol_duty:
    jsr square1_instrument_assign_return
    cpy #6
    bcc :+
    ldy #5
:   lda macro_18, y
    jmp square1_vol_duty_return
square1_instrument_13_pitch:
    jsr square1_instrument_13_vol_duty
    cpx #1
    bcc :+
    ldx #0
:   lda macro_1, x
    jmp square1_pitch_return
square1_instrument_14_vol_duty:
    jsr square1_instrument_assign_return
    cpy #6
    bcc :+
    ldy #5
:   lda macro_19, y
    jmp square1_vol_duty_return
square1_instrument_14_pitch:
    jsr square1_instrument_14_vol_duty
    cpx #1
    bcc :+
    ldx #0
:   lda macro_1, x
    jmp square1_pitch_return
triangle_instrument_5_vol_duty:
    jsr triangle_instrument_assign_return
    cpy #2
    bcc :+
    ldy #1
:   lda macro_16, y
    jmp triangle_vol_duty_return
square1_instrument_6_vol_duty:
    jsr square1_instrument_assign_return
    cpy #24
    bcc :+
    ldy #23
:   lda macro_10, y
    jmp square1_vol_duty_return
square2_instrument_8_pitch:
    jsr square2_instrument_8_vol_duty
    cpx #24
    bcc :+
    ldx #16
:   lda macro_12, x
    jmp square2_pitch_return
macro_0:
.byt .lobyte(48)
; size = 256
.align 256
square1_instrument_3_vol_duty:
    jsr square1_instrument_assign_return
    cpy #5
    bcc :+
    ldy #4
:   lda macro_6, y
    jmp square1_vol_duty_return
square1_instrument_3_pitch:
    jsr square1_instrument_3_vol_duty
    cpx #15
    bcc :+
    ldx #7
:   lda macro_3, x
    jmp square1_pitch_return
square1_instrument_4_vol_duty:
    jsr square1_instrument_assign_return
    cpy #30
    bcc :+
    ldy #29
:   lda macro_7, y
    jmp square1_vol_duty_return
pattern_106:
.byt 127
.byt 1, 42
.byt 0, 0
.byt 4, 36
.byt 0, 0
.byt 2, 36
.byt 0, 0
.byt 2, 42
square1_instrument_4_pitch:
    jsr square1_instrument_4_vol_duty
    cpx #4
    bcc :+
    ldx #0
:   lda macro_5, x
    jmp square1_pitch_return
square1_instrument_5_vol_duty:
    jsr square1_instrument_assign_return
    cpy #4
    bcc :+
    ldy #3
:   lda macro_8, y
    jmp square1_vol_duty_return
triangle_instrument_4_pitch:
    jsr triangle_instrument_4_vol_duty
    cpx #1
    bcc :+
    ldx #0
:   lda macro_15, x
    jmp triangle_pitch_return
triangle_instrument_4_vol_duty:
    jsr triangle_instrument_assign_return
    cpy #2
    bcc :+
    ldy #1
:   lda macro_13, y
    jmp triangle_vol_duty_return
square1_instrument_5_pitch:
    jsr square1_instrument_5_vol_duty
    cpx #10
    bcc :+
    ldx #4
:   lda macro_9, x
    jmp square1_pitch_return
square2_instrument_6_vol_duty:
    jsr square2_instrument_assign_return
    cpy #24
    bcc :+
    ldy #23
:   lda macro_10, y
    jmp square2_vol_duty_return
square1_instrument_6_pitch:
    jsr square1_instrument_6_vol_duty
    cpx #15
    bcc :+
    ldx #7
:   lda macro_3, x
    jmp square1_pitch_return
square1_instrument_7_vol_duty:
    jsr square1_instrument_assign_return
    cpy #75
    bcc :+
    ldy #74
:   lda macro_11, y
    jmp square1_vol_duty_return
square1_instrument_7_pitch:
    jsr square1_instrument_7_vol_duty
    cpx #24
    bcc :+
    ldx #16
:   lda macro_12, x
    jmp square1_pitch_return
square1_instrument_8_vol_duty:
    jsr square1_instrument_assign_return
    cpy #2
    bcc :+
    ldy #1
:   lda macro_13, y
    jmp square1_vol_duty_return
pattern_118:
.byt 251
.byt 3, 30
.byt 0, 0
.byt 3, 30
.byt 3, 30
.byt 0, 0
.byt 3, 30
.byt 0, 0
square1_instrument_8_pitch:
    jsr square1_instrument_8_vol_duty
    cpx #1
    bcc :+
    ldx #0
:   lda macro_14, x
    jmp square1_pitch_return
square1_instrument_9_vol_duty:
    jsr square1_instrument_assign_return
    cpy #2
    bcc :+
    ldy #1
:   lda macro_13, y
    jmp square1_vol_duty_return
macro_14:
.byt .lobyte(-4)
; size = 256
.align 256
triangle_instrument_3_pitch:
    jsr triangle_instrument_3_vol_duty
    cpx #24
    bcc :+
    ldx #16
:   lda macro_33, x
    jmp triangle_pitch_return
square1_instrument_9_pitch:
    jsr square1_instrument_9_vol_duty
    cpx #1
    bcc :+
    ldx #0
:   lda macro_15, x
    jmp square1_pitch_return
square1_instrument_10_vol_duty:
    jsr square1_instrument_assign_return
    cpy #2
    bcc :+
    ldy #1
:   lda macro_16, y
    jmp square1_vol_duty_return
square2_instrument_12_pitch:
    jsr square2_instrument_12_vol_duty
    cpx #10
    bcc :+
    ldx #4
:   lda macro_25, x
    jmp square2_pitch_return
square2_instrument_3_pitch:
    jsr square2_instrument_3_vol_duty
    cpx #2
    bcc :+
    ldx #0
:   lda macro_22, x
    jmp square2_pitch_return
square2_instrument_14_pitch:
    jsr square2_instrument_14_vol_duty
    cpx #1
    bcc :+
    ldx #0
:   lda macro_1, x
    jmp square2_pitch_return
square2_instrument_4_vol_duty:
    jsr square2_instrument_assign_return
    cpy #4
    bcc :+
    ldy #3
:   lda macro_8, y
    jmp square2_vol_duty_return
square2_instrument_4_pitch:
    jsr square2_instrument_4_vol_duty
    cpx #10
    bcc :+
    ldx #4
:   lda macro_9, x
    jmp square2_pitch_return
square2_instrument_5_vol_duty:
    jsr square2_instrument_assign_return
    cpy #5
    bcc :+
    ldy #4
:   lda macro_6, y
    jmp square2_vol_duty_return
square2_instrument_14_vol_duty:
    jsr square2_instrument_assign_return
    cpy #4
    bcc :+
    ldy #3
:   lda macro_27, y
    jmp square2_vol_duty_return
square2_instrument_13_pitch:
    jsr square2_instrument_13_vol_duty
    cpx #10
    bcc :+
    ldx #4
:   lda macro_9, x
    jmp square2_pitch_return
square2_instrument_13_vol_duty:
    jsr square2_instrument_assign_return
    cpy #207
    bcc :+
    ldy #206
:   lda macro_26, y
    jmp square2_vol_duty_return
square2_instrument_5_pitch:
    jsr square2_instrument_5_vol_duty
    cpx #15
    bcc :+
    ldx #7
:   lda macro_3, x
    jmp square2_pitch_return
square2_instrument_3_vol_duty:
    jsr square2_instrument_assign_return
    cpy #15
    bcc :+
    ldy #14
:   lda macro_21, y
    jmp square2_vol_duty_return
square2_instrument_12_vol_duty:
    jsr square2_instrument_assign_return
    cpy #4
    bcc :+
    ldy #3
:   lda macro_8, y
    jmp square2_vol_duty_return
square2_instrument_11_pitch:
    jsr square2_instrument_11_vol_duty
    cpx #1
    bcc :+
    ldx #0
:   lda macro_1, x
    jmp square2_pitch_return
square2_instrument_11_vol_duty:
    jsr square2_instrument_assign_return
    cpy #2
    bcc :+
    ldy #1
:   lda macro_17, y
    jmp square2_vol_duty_return
macro_1:
.byt .lobyte(0)
; size = 256
.align 256
square2_instrument_10_pitch:
    jsr square2_instrument_10_vol_duty
    cpx #1
    bcc :+
    ldx #0
:   lda macro_15, x
    jmp square2_pitch_return
square2_instrument_10_vol_duty:
    jsr square2_instrument_assign_return
    cpy #2
    bcc :+
    ldy #1
:   lda macro_13, y
    jmp square2_vol_duty_return
square2_instrument_7_pitch:
    jsr square2_instrument_7_vol_duty
    cpx #24
    bcc :+
    ldx #16
:   lda macro_24, x
    jmp square2_pitch_return
square2_instrument_9_pitch:
    jsr square2_instrument_9_vol_duty
    cpx #1
    bcc :+
    ldx #0
:   lda macro_14, x
    jmp square2_pitch_return
square2_instrument_9_vol_duty:
    jsr square2_instrument_assign_return
    cpy #2
    bcc :+
    ldy #1
:   lda macro_13, y
    jmp square2_vol_duty_return
square2_instrument_8_vol_duty:
    jsr square2_instrument_assign_return
    cpy #75
    bcc :+
    ldy #74
:   lda macro_11, y
    jmp square2_vol_duty_return
square2_instrument_17_pitch:
    jsr square2_instrument_17_vol_duty
    cpx #1
    bcc :+
    ldx #0
:   lda macro_1, x
    jmp square2_pitch_return
triangle_instrument_1_pitch:
    jsr triangle_instrument_1_vol_duty
    cpx #1
    bcc :+
    ldx #0
:   lda macro_1, x
    jmp triangle_pitch_return
square1_instrument_16_vol_duty:
    jsr square1_instrument_assign_return
    cpy #15
    bcc :+
    ldy #14
:   lda macro_21, y
    jmp square1_vol_duty_return
square1_instrument_16_pitch:
    jsr square1_instrument_16_vol_duty
    cpx #2
    bcc :+
    ldx #0
:   lda macro_22, x
    jmp square1_pitch_return
square2_instrument_0_vol_duty:
    jsr square2_instrument_assign_return
    cpy #1
    bcc :+
    ldy #0
:   lda macro_0, y
    jmp square2_vol_duty_return
triangle_instrument_1_vol_duty:
    jsr triangle_instrument_assign_return
    cpy #5
    bcc :+
    ldy #4
:   lda macro_20, y
    jmp triangle_vol_duty_return
triangle_instrument_0_pitch:
    jsr triangle_instrument_0_vol_duty
    cpx #1
    bcc :+
    ldx #0
:   lda macro_1, x
    jmp triangle_pitch_return
square2_instrument_7_vol_duty:
    jsr square2_instrument_assign_return
    cpy #12
    bcc :+
    ldy #11
:   lda macro_23, y
    jmp square2_vol_duty_return
triangle_instrument_0_vol_duty:
    jsr triangle_instrument_assign_return
    cpy #1
    bcc :+
    ldy #0
:   lda macro_0, y
    jmp triangle_vol_duty_return
square2_instrument_0_pitch:
    jsr square2_instrument_0_vol_duty
    cpx #1
    bcc :+
    ldx #0
:   lda macro_1, x
    jmp square2_pitch_return
square1_instrument_15_pitch:
    jsr square1_instrument_15_vol_duty
    cpx #1
    bcc :+
    ldx #0
:   lda macro_1, x
    jmp square1_pitch_return
macro_31:
.byt .lobyte(-16)
; size = 256
.align 256
square2_instrument_1_vol_duty:
    jsr square2_instrument_assign_return
    cpy #30
    bcc :+
    ldy #29
:   lda macro_4, y
    jmp square2_vol_duty_return
square2_instrument_17_vol_duty:
    jsr square2_instrument_assign_return
    cpy #5
    bcc :+
    ldy #4
:   lda macro_20, y
    jmp square2_vol_duty_return
square2_instrument_1_pitch:
    jsr square2_instrument_1_vol_duty
    cpx #4
    bcc :+
    ldx #0
:   lda macro_5, x
    jmp square2_pitch_return
square2_instrument_2_vol_duty:
    jsr square2_instrument_assign_return
    cpy #30
    bcc :+
    ldy #29
:   lda macro_7, y
    jmp square2_vol_duty_return
square2_instrument_16_pitch:
    jsr square2_instrument_16_vol_duty
    cpx #1
    bcc :+
    ldx #0
:   lda macro_31, x
    jmp square2_pitch_return
square2_instrument_16_vol_duty:
    jsr square2_instrument_assign_return
    cpy #18
    bcc :+
    ldy #17
:   lda macro_30, y
    jmp square2_vol_duty_return
square2_instrument_15_pitch:
    jsr square2_instrument_15_vol_duty
    cpx #1
    bcc :+
    ldx #0
:   lda macro_29, x
    jmp square2_pitch_return
square2_instrument_15_vol_duty:
    jsr square2_instrument_assign_return
    cpy #18
    bcc :+
    ldy #17
:   lda macro_28, y
    jmp square2_vol_duty_return
square2_instrument_2_pitch:
    jsr square2_instrument_2_vol_duty
    cpx #4
    bcc :+
    ldx #0
:   lda macro_5, x
    jmp square2_pitch_return
square1_instrument_1_vol_duty:
    jsr square1_instrument_assign_return
    cpy #76
    bcc :+
    ldy #69
:   lda macro_2, y
    jmp square1_vol_duty_return
macro_3:
.byt .lobyte(-32)
.byt .lobyte(16)
.byt .lobyte(8)
.byt .lobyte(4)
.byt .lobyte(2)
.byt .lobyte(1)
.byt .lobyte(1)
.byt .lobyte(1)
.byt .lobyte(3)
.byt .lobyte(-3)
.byt .lobyte(-2)
.byt .lobyte(-1)
.byt .lobyte(-3)
.byt .lobyte(3)
.byt .lobyte(2)
triangle_instrument_5_pitch:
    jsr triangle_instrument_5_vol_duty
    cpx #1
    bcc :+
    ldx #0
:   lda macro_1, x
    jmp triangle_pitch_return
pattern_33:
.byt 191
.byt 0, 0
.byt 1, 38
.byt 0, 0
.byt 1, 30
.byt 1, 38
.byt 0, 0
.byt 1, 44
noise_instrument_4_vol_duty:
    jsr noise_instrument_assign_return
    cpy #18
    bcc :+
    ldy #17
:   lda macro_37, y
    jmp noise_vol_duty_return
square1_instrument_0_vol_duty:
    jsr square1_instrument_assign_return
    cpy #1
    bcc :+
    ldy #0
:   lda macro_0, y
    jmp square1_vol_duty_return
macro_21:
.byt .lobyte(122)
.byt .lobyte(120)
.byt .lobyte(119)
.byt .lobyte(118)
.byt .lobyte(118)
.byt .lobyte(117)
.byt .lobyte(117)
.byt .lobyte(117)
.byt .lobyte(117)
.byt .lobyte(116)
.byt .lobyte(116)
.byt .lobyte(115)
.byt .lobyte(114)
.byt .lobyte(113)
.byt .lobyte(112)
noise_instrument_3_vol_duty:
    jsr noise_instrument_assign_return
    cpy #15
    bcc :+
    ldy #14
:   lda macro_36, y
    jmp noise_vol_duty_return
macro_29:
.byt .lobyte(-24)
; size = 256
.align 256
square1_instrument_0_pitch:
    jsr square1_instrument_0_vol_duty
    cpx #1
    bcc :+
    ldx #0
:   lda macro_1, x
    jmp square1_pitch_return
pattern_11:
.byt 127
.byt 0, 0
.byt 1, 28
.byt 0, 0
.byt 1, 34
.byt 1, 40
.byt 1, 48
.byt 1, 54
square1_instrument_1_pitch:
    jsr square1_instrument_1_vol_duty
    cpx #15
    bcc :+
    ldx #7
:   lda macro_3, x
    jmp square1_pitch_return
noise_instrument_2_vol_duty:
    jsr noise_instrument_assign_return
    cpy #19
    bcc :+
    ldy #18
:   lda macro_35, y
    jmp noise_vol_duty_return
macro_36:
.byt .lobyte(58)
.byt .lobyte(56)
.byt .lobyte(55)
.byt .lobyte(54)
.byt .lobyte(54)
.byt .lobyte(53)
.byt .lobyte(53)
.byt .lobyte(53)
.byt .lobyte(53)
.byt .lobyte(52)
.byt .lobyte(52)
.byt .lobyte(51)
.byt .lobyte(50)
.byt .lobyte(49)
.byt .lobyte(48)
square1_instrument_2_pitch:
    jsr square1_instrument_2_vol_duty
    cpx #4
    bcc :+
    ldx #0
:   lda macro_5, x
    jmp square1_pitch_return
triangle_instrument_6_vol_duty:
    jsr triangle_instrument_assign_return
    cpy #2
    bcc :+
    ldy #1
:   lda macro_17, y
    jmp triangle_vol_duty_return
triangle_instrument_6_pitch:
    jsr triangle_instrument_6_vol_duty
    cpx #1
    bcc :+
    ldx #0
:   lda macro_1, x
    jmp triangle_pitch_return
square1_instrument_2_vol_duty:
    jsr square1_instrument_assign_return
    cpy #30
    bcc :+
    ldy #29
:   lda macro_4, y
    jmp square1_vol_duty_return
noise_instrument_1_vol_duty:
    jsr noise_instrument_assign_return
    cpy #6
    bcc :+
    ldy #5
:   lda macro_34, y
    jmp noise_vol_duty_return
triangle_instrument_7_vol_duty:
    jsr triangle_instrument_assign_return
    cpy #2
    bcc :+
    ldy #1
:   lda macro_17, y
    jmp triangle_vol_duty_return
triangle_instrument_7_pitch:
    jsr triangle_instrument_7_vol_duty
    cpx #1
    bcc :+
    ldx #0
:   lda macro_1, x
    jmp triangle_pitch_return
triangle_instrument_8_vol_duty:
    jsr triangle_instrument_assign_return
    cpy #18
    bcc :+
    ldy #17
:   lda macro_28, y
    jmp triangle_vol_duty_return
triangle_instrument_8_pitch:
    jsr triangle_instrument_8_vol_duty
    cpx #1
    bcc :+
    ldx #0
:   lda macro_29, x
    jmp triangle_pitch_return
noise_instrument_0_vol_duty:
    jsr noise_instrument_assign_return
    cpy #1
    bcc :+
    ldy #0
:   lda macro_0, y
    jmp noise_vol_duty_return
pattern_394:
.byt 95
.byt 13, 34
.byt 0, 0
.byt 13, 34
.byt 13, 34
.byt 13, 34
.byt 13, 34
pattern_405:
.byt 95
.byt 13, 10
.byt 0, 0
.byt 13, 10
.byt 13, 10
.byt 13, 10
.byt 13, 10
pattern_272:
.byt 17
.byt 3, 96
.byt 3, 100
; size = 256
.align 256
pattern_32:
.byt 215
.byt 3, 0
.byt 2, 0
.byt 1, 3
.byt 2, 7
.byt 1, 3
.byt 2, 0
pattern_436:
.byt 95
.byt 13, 58
.byt 0, 0
.byt 13, 58
.byt 13, 58
.byt 13, 58
.byt 13, 58
pattern_35:
.byt 245
.byt 3, 24
.byt 1, 24
.byt 1, 16
.byt 1, 24
.byt 1, 30
.byt 0, 0
pattern_151:
.byt 221
.byt 2, 46
.byt 4, 36
.byt 0, 0
.byt 2, 36
.byt 2, 18
.byt 0, 0
pattern_150:
.byt 221
.byt 2, 46
.byt 4, 36
.byt 0, 0
.byt 2, 36
.byt 2, 42
.byt 0, 0
pattern_71:
.byt 245
.byt 3, 86
.byt 3, 92
.byt 3, 78
.byt 0, 0
.byt 3, 68
.byt 3, 72
pattern_538:
.byt 252
.byt 3, 110
.byt 0, 0
.byt 3, 112
.byt 0, 0
.byt 3, 116
.byt 0, 0
pattern_105:
.byt 63
.byt 1, 36
.byt 0, 0
.byt 4, 36
.byt 0, 0
.byt 2, 36
.byt 0, 0
pattern_87:
.byt 245
.byt 3, 110
.byt 3, 116
.byt 3, 102
.byt 0, 0
.byt 3, 106
.byt 3, 110
pattern_117:
.byt 63
.byt 3, 30
.byt 0, 0
.byt 3, 30
.byt 3, 30
.byt 3, 30
.byt 0, 0
pattern_81:
.byt 215
.byt 3, 102
.byt 0, 0
.byt 3, 96
.byt 3, 110
.byt 3, 116
.byt 0, 0
pattern_126:
.byt 63
.byt 2, 32
.byt 0, 0
.byt 2, 32
.byt 0, 0
.byt 2, 32
.byt 0, 0
pattern_128:
.byt 245
.byt 2, 46
.byt 0, 0
.byt 2, 36
.byt 0, 0
.byt 2, 42
.byt 0, 0
macro_23:
.byt .lobyte(176)
.byt .lobyte(185)
.byt .lobyte(187)
.byt .lobyte(187)
.byt .lobyte(186)
.byt .lobyte(185)
.byt .lobyte(183)
.byt .lobyte(181)
.byt .lobyte(181)
.byt .lobyte(182)
.byt .lobyte(183)
.byt .lobyte(184)
pattern_382:
.byt 93
.byt 13, 34
.byt 13, 16
.byt 13, 20
.byt 13, 20
.byt 13, 20
pattern_389:
.byt 213
.byt 14, 48
.byt 14, 44
.byt 14, 40
.byt 14, 48
.byt 14, 54
pattern_388:
.byt 213
.byt 14, 48
.byt 0, 0
.byt 14, 44
.byt 14, 40
.byt 14, 44
pattern_416:
.byt 213
.byt 4, 92
.byt 4, 82
.byt 4, 88
.byt 4, 86
.byt 4, 78
pattern_385:
.byt 213
.byt 14, 40
.byt 14, 44
.byt 14, 40
.byt 14, 48
.byt 14, 40
pattern_384:
.byt 213
.byt 14, 40
.byt 0, 0
.byt 14, 44
.byt 14, 40
.byt 14, 38
pattern_27:
.byt 85
.byt 3, 24
.byt 1, 24
.byt 3, 24
.byt 2, 24
; size = 256
.align 256
pattern_256:
.byt 31
.byt 8, 88
.byt 9, 88
.byt 8, 88
.byt 9, 88
.byt 8, 88
pattern_260:
.byt 31
.byt 9, 96
.byt 10, 96
.byt 9, 96
.byt 10, 96
.byt 9, 96
pattern_381:
.byt 93
.byt 1, 92
.byt 5, 68
.byt 5, 68
.byt 1, 92
.byt 5, 68
pattern_391:
.byt 93
.byt 1, 82
.byt 5, 58
.byt 5, 78
.byt 1, 82
.byt 5, 58
pattern_226:
.byt 213
.byt 3, 92
.byt 3, 88
.byt 3, 82
.byt 3, 88
.byt 3, 86
pattern_393:
.byt 93
.byt 1, 82
.byt 5, 40
.byt 5, 68
.byt 1, 92
.byt 5, 68
pattern_379:
.byt 93
.byt 1, 82
.byt 5, 58
.byt 5, 58
.byt 1, 82
.byt 5, 58
pattern_395:
.byt 93
.byt 13, 40
.byt 13, 40
.byt 13, 40
.byt 13, 40
.byt 13, 40
pattern_396:
.byt 93
.byt 13, 44
.byt 13, 44
.byt 13, 44
.byt 13, 44
.byt 13, 44
pattern_397:
.byt 93
.byt 14, 34
.byt 14, 34
.byt 14, 34
.byt 14, 34
.byt 14, 34
pattern_398:
.byt 93
.byt 14, 40
.byt 14, 40
.byt 14, 40
.byt 14, 40
.byt 14, 40
pattern_399:
.byt 93
.byt 14, 58
.byt 14, 44
.byt 14, 44
.byt 14, 44
.byt 14, 44
pattern_401:
.byt 213
.byt 0, 0
.byt 14, 48
.byt 0, 0
.byt 14, 54
.byt 14, 48
pattern_406:
.byt 93
.byt 13, 34
.byt 13, 20
.byt 13, 20
.byt 13, 20
.byt 13, 20
pattern_410:
.byt 213
.byt 14, 68
.byt 14, 58
.byt 14, 64
.byt 14, 62
.byt 14, 54
pattern_431:
.byt 213
.byt 4, 72
.byt 4, 78
.byt 4, 82
.byt 4, 78
.byt 4, 72
pattern_529:
.byt 93
.byt 3, 120
.byt 0, 0
.byt 3, 112
.byt 3, 106
.byt 3, 102
pattern_508:
.byt 213
.byt 16, 54
.byt 16, 64
.byt 16, 72
.byt 16, 78
.byt 15, 92
pattern_504:
.byt 93
.byt 3, 136
.byt 0, 0
.byt 3, 136
.byt 3, 130
.byt 3, 126
pattern_479:
.byt 241
.byt 3, 102
.byt 3, 102
.byt 0, 0
.byt 3, 106
.byt 0, 0
pattern_447:
.byt 93
.byt 8, 82
.byt 5, 68
.byt 5, 68
.byt 1, 92
.byt 5, 68
pattern_446:
.byt 93
.byt 1, 88
.byt 5, 64
.byt 5, 64
.byt 1, 88
.byt 8, 58
pattern_442:
.byt 213
.byt 0, 0
.byt 4, 72
.byt 0, 0
.byt 4, 78
.byt 4, 72
pattern_418:
.byt 64
.byt 1, 68
; size = 256
.align 256
pattern_440:
.byt 93
.byt 13, 82
.byt 13, 68
.byt 13, 68
.byt 13, 68
.byt 13, 68
pattern_439:
.byt 93
.byt 13, 58
.byt 13, 58
.byt 13, 58
.byt 13, 58
.byt 13, 58
pattern_438:
.byt 93
.byt 13, 68
.byt 13, 68
.byt 13, 68
.byt 13, 68
.byt 13, 68
pattern_437:
.byt 93
.byt 13, 64
.byt 13, 64
.byt 13, 64
.byt 13, 64
.byt 13, 64
pattern_433:
.byt 213
.byt 4, 72
.byt 0, 0
.byt 4, 68
.byt 4, 64
.byt 4, 68
pattern_550:
.byt 93
.byt 3, 112
.byt 0, 0
.byt 3, 112
.byt 3, 106
.byt 3, 102
pattern_430:
.byt 213
.byt 4, 48
.byt 0, 0
.byt 4, 68
.byt 4, 64
.byt 4, 68
pattern_429:
.byt 213
.byt 4, 58
.byt 4, 64
.byt 4, 68
.byt 4, 54
.byt 4, 52
pattern_428:
.byt 93
.byt 13, 58
.byt 13, 44
.byt 13, 44
.byt 13, 44
.byt 13, 44
pattern_427:
.byt 93
.byt 13, 34
.byt 13, 34
.byt 13, 34
.byt 13, 34
.byt 13, 34
pattern_540:
.byt 94
.byt 0, 0
.byt 3, 120
.byt 0, 0
.byt 3, 116
.byt 3, 110
pattern_425:
.byt 117
.byt 4, 44
.byt 4, 40
.byt 4, 48
.byt 4, 54
.byt 4, 58
pattern_424:
.byt 117
.byt 0, 0
.byt 4, 44
.byt 4, 40
.byt 4, 44
.byt 4, 48
pattern_374:
.byt 93
.byt 13, 10
.byt 13, 10
.byt 13, 10
.byt 13, 10
.byt 13, 10
pattern_375:
.byt 93
.byt 13, 16
.byt 13, 16
.byt 13, 16
.byt 13, 16
.byt 13, 16
pattern_376:
.byt 93
.byt 13, 20
.byt 13, 20
.byt 13, 20
.byt 13, 20
.byt 13, 20
pattern_422:
.byt 213
.byt 4, 44
.byt 4, 34
.byt 4, 40
.byt 4, 38
.byt 4, 30
pattern_380:
.byt 93
.byt 1, 88
.byt 5, 64
.byt 5, 64
.byt 1, 88
.byt 5, 64
pattern_120:
.byt 93
.byt 1, 78
.byt 1, 68
.byt 1, 68
.byt 1, 78
.byt 1, 78
pattern_57:
.byt 213
.byt 3, 134
.byt 3, 130
.byt 3, 126
.byt 3, 130
.byt 0, 0
pattern_59:
.byt 213
.byt 0, 0
.byt 3, 120
.byt 3, 124
.byt 3, 126
.byt 0, 0
pattern_18:
.byt 214
.byt 2, 0
.byt 1, 3
.byt 2, 7
.byt 1, 3
.byt 2, 0
pattern_19:
.byt 118
.byt 2, 0
.byt 1, 3
.byt 2, 7
.byt 2, 7
.byt 2, 6
pattern_417:
.byt 1
.byt 1, 82
; size = 256
.align 256
pattern_22:
.byt 87
.byt 1, 54
.byt 0, 0
.byt 1, 72
.byt 1, 76
.byt 1, 78
pattern_138:
.byt 93
.byt 1, 78
.byt 1, 78
.byt 1, 78
.byt 1, 78
.byt 1, 78
pattern_79:
.byt 213
.byt 3, 62
.byt 3, 68
.byt 3, 54
.byt 3, 58
.byt 3, 62
pattern_121:
.byt 93
.byt 1, 78
.byt 1, 68
.byt 1, 68
.byt 1, 78
.byt 1, 54
pattern_136:
.byt 93
.byt 3, 30
.byt 3, 30
.byt 3, 30
.byt 3, 30
.byt 2, 42
pattern_116:
.byt 59
.byt 3, 30
.byt 0, 0
.byt 3, 30
.byt 3, 30
.byt 0, 0
pattern_113:
.byt 93
.byt 3, 15
.byt 3, 15
.byt 3, 15
.byt 3, 8
.byt 3, 8
pattern_29:
.byt 213
.byt 1, 54
.byt 1, 54
.byt 1, 68
.byt 1, 54
.byt 1, 68
pattern_99:
.byt 213
.byt 3, 12
.byt 3, 12
.byt 3, 12
.byt 3, 12
.byt 1, 3
pattern_108:
.byt 87
.byt 1, 50
.byt 0, 0
.byt 4, 36
.byt 2, 36
.byt 2, 42
pattern_107:
.byt 87
.byt 1, 46
.byt 0, 0
.byt 4, 36
.byt 2, 36
.byt 2, 46
pattern_103:
.byt 213
.byt 4, 22
.byt 5, 12
.byt 4, 12
.byt 4, 22
.byt 0, 0
pattern_102:
.byt 213
.byt 4, 18
.byt 5, 12
.byt 4, 12
.byt 4, 18
.byt 0, 0
pattern_13:
.byt 244
.byt 1, 0
.byt 1, 16
.byt 1, 24
.byt 1, 30
.byt 0, 0
pattern_44:
.byt 213
.byt 0, 0
.byt 3, 96
.byt 3, 100
.byt 3, 102
.byt 0, 0
macro_25:
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(-1)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(1)
.byt .lobyte(0)
.byt .lobyte(0)
macro_9:
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(-3)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(3)
.byt .lobyte(0)
.byt .lobyte(0)
pattern_533:
.byt 85
.byt 16, 54
.byt 16, 62
.byt 16, 72
.byt 16, 78
pattern_509:
.byt 85
.byt 3, 102
.byt 3, 110
.byt 3, 116
.byt 3, 116
pattern_534:
.byt 85
.byt 16, 72
.byt 16, 62
.byt 16, 58
.byt 16, 68
pattern_67:
.byt 85
.byt 3, 86
.byt 3, 82
.byt 3, 86
.byt 3, 92
pattern_392:
.byt 85
.byt 1, 92
.byt 5, 68
.byt 1, 88
.byt 5, 68
pattern_536:
.byt 113
.byt 3, 102
.byt 3, 116
.byt 0, 0
.byt 3, 126
pattern_66:
.byt 85
.byt 3, 96
.byt 0, 0
.byt 3, 78
.byt 3, 82
pattern_415:
.byt 69
.byt 4, 88
.byt 0, 0
.byt 4, 88
macro_15:
.byt .lobyte(4)
; size = 256
.align 256
pattern_502:
.byt 29
.byt 3, 154
.byt 3, 148
.byt 0, 0
.byt 3, 144
pattern_25:
.byt 85
.byt 1, 72
.byt 1, 68
.byt 1, 62
.byt 1, 68
pattern_26:
.byt 85
.byt 1, 24
.byt 2, 24
.byt 3, 24
.byt 1, 24
pattern_512:
.byt 85
.byt 3, 112
.byt 3, 116
.byt 3, 112
.byt 3, 106
pattern_70:
.byt 85
.byt 3, 78
.byt 0, 0
.byt 3, 96
.byt 3, 92
pattern_495:
.byt 85
.byt 3, 136
.byt 3, 140
.byt 3, 136
.byt 3, 130
pattern_492:
.byt 85
.byt 3, 126
.byt 3, 134
.byt 3, 140
.byt 3, 140
pattern_72:
.byt 85
.byt 3, 78
.byt 3, 82
.byt 3, 86
.byt 3, 96
pattern_12:
.byt 197
.byt 1, 0
.byt 2, 0
.byt 1, 0
.byt 0, 0
pattern_541:
.byt 101
.byt 3, 106
.byt 3, 110
.byt 0, 0
.byt 3, 100
pattern_524:
.byt 85
.byt 3, 30
.byt 3, 54
.byt 3, 16
.byt 3, 40
pattern_16:
.byt 116
.byt 1, 68
.byt 1, 54
.byt 1, 54
.byt 1, 54
pattern_528:
.byt 198
.byt 0, 0
.byt 3, 112
.byt 3, 116
.byt 0, 0
pattern_521:
.byt 85
.byt 16, 48
.byt 16, 62
.byt 16, 48
.byt 16, 62
pattern_20:
.byt 85
.byt 1, 72
.byt 1, 54
.byt 0, 0
.byt 1, 44
pattern_69:
.byt 85
.byt 3, 96
.byt 3, 92
.byt 3, 86
.byt 3, 92
pattern_518:
.byt 85
.byt 16, 54
.byt 16, 68
.byt 16, 54
.byt 16, 68
pattern_400:
.byt 85
.byt 14, 64
.byt 14, 62
.byt 14, 58
.byt 14, 54
pattern_517:
.byt 198
.byt 0, 0
.byt 3, 100
.byt 3, 106
.byt 0, 0
pattern_532:
.byt 85
.byt 16, 72
.byt 16, 78
.byt 16, 72
.byt 16, 64
pattern_311:
.byt 153
.byt 7, 86
.byt 0, 0
.byt 7, 78
.byt 0, 0
pattern_312:
.byt 153
.byt 7, 82
.byt 0, 0
.byt 7, 76
.byt 0, 0
pattern_313:
.byt 153
.byt 7, 72
.byt 0, 0
.byt 7, 62
.byt 0, 0
pattern_314:
.byt 85
.byt 3, 110
.byt 0, 0
.byt 3, 102
.byt 0, 0
pattern_531:
.byt 85
.byt 16, 68
.byt 16, 62
.byt 16, 54
.byt 16, 64
pattern_315:
.byt 85
.byt 3, 106
.byt 0, 0
.byt 3, 100
.byt 0, 0
pattern_316:
.byt 85
.byt 3, 96
.byt 0, 0
.byt 3, 86
.byt 0, 0
pattern_23:
.byt 85
.byt 1, 68
.byt 1, 62
.byt 1, 62
.byt 1, 68
macro_27:
.byt .lobyte(112)
.byt .lobyte(120)
.byt .lobyte(127)
.byt .lobyte(63)
; size = 256
.align 256
pattern_525:
.byt 85
.byt 3, 24
.byt 3, 48
.byt 3, 20
.byt 3, 44
pattern_53:
.byt 85
.byt 3, 16
.byt 1, 16
.byt 3, 16
.byt 2, 16
pattern_63:
.byt 85
.byt 1, 48
.byt 2, 48
.byt 3, 48
.byt 1, 48
pattern_62:
.byt 85
.byt 2, 24
.byt 2, 24
.byt 2, 24
.byt 2, 24
pattern_441:
.byt 85
.byt 4, 88
.byt 4, 86
.byt 4, 82
.byt 4, 78
pattern_61:
.byt 85
.byt 1, 3
.byt 2, 0
.byt 2, 7
.byt 2, 0
pattern_60:
.byt 85
.byt 3, 126
.byt 3, 116
.byt 3, 110
.byt 3, 116
pattern_58:
.byt 85
.byt 3, 120
.byt 3, 102
.byt 3, 116
.byt 3, 120
pattern_39:
.byt 85
.byt 2, 0
.byt 2, 0
.byt 2, 0
.byt 2, 0
pattern_56:
.byt 85
.byt 0, 0
.byt 3, 120
.byt 3, 124
.byt 3, 126
pattern_55:
.byt 85
.byt 3, 102
.byt 0, 0
.byt 3, 120
.byt 3, 102
pattern_54:
.byt 85
.byt 3, 120
.byt 3, 102
.byt 0, 0
.byt 3, 120
pattern_64:
.byt 85
.byt 3, 48
.byt 1, 48
.byt 3, 48
.byt 2, 48
pattern_52:
.byt 85
.byt 1, 16
.byt 2, 16
.byt 3, 16
.byt 1, 16
pattern_51:
.byt 85
.byt 3, 54
.byt 3, 44
.byt 3, 38
.byt 3, 44
pattern_49:
.byt 85
.byt 0, 0
.byt 3, 48
.byt 3, 52
.byt 3, 54
pattern_48:
.byt 85
.byt 3, 30
.byt 0, 0
.byt 3, 48
.byt 3, 30
pattern_426:
.byt 85
.byt 4, 64
.byt 4, 58
.byt 0, 0
.byt 4, 54
pattern_47:
.byt 85
.byt 3, 48
.byt 3, 30
.byt 0, 0
.byt 3, 48
pattern_45:
.byt 85
.byt 3, 102
.byt 3, 92
.byt 3, 86
.byt 3, 92
pattern_42:
.byt 85
.byt 0, 0
.byt 3, 96
.byt 3, 100
.byt 3, 102
pattern_40:
.byt 85
.byt 3, 96
.byt 3, 78
.byt 0, 0
.byt 3, 96
pattern_41:
.byt 85
.byt 3, 78
.byt 0, 0
.byt 3, 96
.byt 3, 78
pattern_472:
.byt 85
.byt 16, 72
.byt 16, 78
.byt 16, 72
.byt 16, 62
pattern_488:
.byt 135
.byt 3, 96
.byt 0, 0
.byt 3, 100
.byt 0, 0
pattern_386:
.byt 85
.byt 14, 44
.byt 0, 0
.byt 14, 40
.byt 14, 38
pattern_30:
.byt 85
.byt 1, 54
.byt 1, 54
.byt 1, 68
.byt 1, 54
pattern_65:
.byt 85
.byt 3, 78
.byt 3, 86
.byt 0, 0
.byt 3, 78
macro_8:
.byt .lobyte(53)
.byt .lobyte(126)
.byt .lobyte(188)
.byt .lobyte(186)
; size = 256
.align 256
pattern_478:
.byt 85
.byt 3, 20
.byt 3, 44
.byt 3, 20
.byt 3, 44
pattern_477:
.byt 85
.byt 3, 16
.byt 3, 40
.byt 3, 20
.byt 3, 44
pattern_476:
.byt 85
.byt 3, 16
.byt 3, 40
.byt 3, 16
.byt 3, 40
pattern_475:
.byt 85
.byt 3, 24
.byt 3, 48
.byt 3, 24
.byt 3, 48
pattern_474:
.byt 85
.byt 3, 30
.byt 3, 54
.byt 3, 24
.byt 3, 48
pattern_473:
.byt 85
.byt 3, 30
.byt 3, 54
.byt 3, 30
.byt 3, 54
pattern_28:
.byt 85
.byt 1, 78
.byt 1, 78
.byt 1, 68
.byt 1, 54
pattern_471:
.byt 85
.byt 16, 68
.byt 16, 62
.byt 16, 54
.byt 16, 62
pattern_470:
.byt 85
.byt 16, 54
.byt 16, 62
.byt 16, 68
.byt 16, 78
pattern_346:
.byt 85
.byt 4, 68
.byt 0, 0
.byt 4, 64
.byt 4, 62
pattern_457:
.byt 85
.byt 16, 76
.byt 16, 82
.byt 16, 76
.byt 16, 68
pattern_456:
.byt 85
.byt 16, 72
.byt 16, 64
.byt 16, 58
.byt 16, 68
pattern_455:
.byt 85
.byt 16, 54
.byt 16, 64
.byt 16, 72
.byt 16, 78
pattern_31:
.byt 85
.byt 1, 3
.byt 1, 3
.byt 2, 7
.byt 1, 3
pattern_351:
.byt 85
.byt 4, 68
.byt 0, 0
.byt 4, 72
.byt 4, 78
pattern_34:
.byt 177
.byt 0, 0
.byt 1, 34
.byt 0, 0
.byt 1, 34
pattern_222:
.byt 85
.byt 3, 102
.byt 3, 96
.byt 3, 92
.byt 3, 96
pattern_209:
.byt 85
.byt 5, 52
.byt 5, 54
.byt 5, 58
.byt 5, 54
pattern_210:
.byt 85
.byt 5, 58
.byt 5, 62
.byt 5, 64
.byt 5, 68
pattern_211:
.byt 85
.byt 5, 64
.byt 5, 62
.byt 5, 58
.byt 5, 62
pattern_139:
.byt 85
.byt 4, 18
.byt 5, 12
.byt 4, 12
.byt 5, 12
pattern_137:
.byt 29
.byt 1, 78
.byt 1, 78
.byt 1, 78
.byt 1, 78
pattern_135:
.byt 89
.byt 3, 30
.byt 3, 30
.byt 3, 30
.byt 3, 30
pattern_134:
.byt 29
.byt 3, 30
.byt 3, 30
.byt 3, 30
.byt 3, 30
pattern_132:
.byt 85
.byt 4, 12
.byt 5, 12
.byt 4, 12
.byt 4, 18
pattern_131:
.byt 85
.byt 4, 12
.byt 5, 12
.byt 4, 12
.byt 5, 12
pattern_129:
.byt 53
.byt 2, 46
.byt 0, 0
.byt 2, 36
.byt 0, 0
pattern_124:
.byt 85
.byt 4, 22
.byt 5, 12
.byt 4, 12
.byt 4, 18
macro_5:
.byt .lobyte(0)
.byt .lobyte(-1)
.byt .lobyte(0)
.byt .lobyte(1)
; size = 255
.align 256
pattern_140:
.byt 85
.byt 4, 26
.byt 5, 12
.byt 4, 12
.byt 5, 8
pattern_123:
.byt 85
.byt 4, 12
.byt 4, 12
.byt 4, 12
.byt 5, 12
pattern_224:
.byt 85
.byt 3, 78
.byt 3, 82
.byt 3, 86
.byt 3, 88
pattern_119:
.byt 85
.byt 1, 78
.byt 1, 68
.byt 1, 78
.byt 1, 54
pattern_115:
.byt 85
.byt 4, 22
.byt 5, 12
.byt 4, 12
.byt 4, 22
pattern_114:
.byt 85
.byt 4, 18
.byt 5, 12
.byt 4, 12
.byt 4, 18
pattern_232:
.byt 85
.byt 8, 112
.byt 8, 110
.byt 8, 106
.byt 8, 102
pattern_112:
.byt 89
.byt 3, 15
.byt 3, 15
.byt 3, 8
.byt 3, 15
pattern_234:
.byt 85
.byt 8, 78
.byt 8, 86
.byt 8, 92
.byt 8, 96
pattern_235:
.byt 85
.byt 8, 102
.byt 8, 96
.byt 8, 92
.byt 8, 86
pattern_236:
.byt 85
.byt 3, 92
.byt 3, 96
.byt 3, 92
.byt 3, 102
pattern_149:
.byt 209
.byt 2, 36
.byt 2, 36
.byt 4, 36
.byt 0, 0
pattern_171:
.byt 85
.byt 3, 54
.byt 0, 0
.byt 3, 54
.byt 3, 58
pattern_167:
.byt 85
.byt 5, 82
.byt 5, 78
.byt 5, 76
.byt 5, 78
pattern_166:
.byt 85
.byt 5, 76
.byt 5, 78
.byt 5, 82
.byt 5, 86
pattern_165:
.byt 85
.byt 5, 68
.byt 5, 72
.byt 5, 76
.byt 5, 72
pattern_163:
.byt 85
.byt 3, 64
.byt 3, 62
.byt 3, 58
.byt 3, 62
pattern_162:
.byt 85
.byt 3, 58
.byt 3, 62
.byt 3, 64
.byt 3, 68
pattern_161:
.byt 85
.byt 6, 52
.byt 3, 54
.byt 3, 58
.byt 3, 54
pattern_156:
.byt 85
.byt 5, 64
.byt 5, 68
.byt 5, 64
.byt 5, 62
pattern_155:
.byt 85
.byt 5, 64
.byt 5, 68
.byt 5, 72
.byt 5, 68
pattern_153:
.byt 85
.byt 5, 68
.byt 5, 64
.byt 5, 62
.byt 5, 64
pattern_111:
.byt 29
.byt 3, 15
.byt 3, 15
.byt 3, 15
.byt 3, 8
pattern_145:
.byt 85
.byt 2, 36
.byt 4, 42
.byt 2, 36
.byt 4, 32
pattern_199:
.byt 85
.byt 5, 82
.byt 5, 86
.byt 5, 92
.byt 5, 96
pattern_144:
.byt 85
.byt 2, 50
.byt 0, 0
.byt 2, 36
.byt 4, 32
pattern_201:
.byt 85
.byt 5, 58
.byt 5, 62
.byt 5, 68
.byt 5, 72
pattern_143:
.byt 85
.byt 2, 42
.byt 0, 0
.byt 2, 36
.byt 0, 0
pattern_419:
.byt 1
.byt 4, 34
; size = 255
.align 256
pattern_203:
.byt 85
.byt 5, 68
.byt 5, 64
.byt 5, 62
.byt 5, 58
pattern_204:
.byt 85
.byt 5, 54
.byt 5, 58
.byt 5, 62
.byt 5, 64
pattern_141:
.byt 85
.byt 4, 12
.byt 5, 18
.byt 4, 12
.byt 5, 8
pattern_206:
.byt 85
.byt 5, 92
.byt 5, 88
.byt 5, 86
.byt 5, 82
pattern_207:
.byt 85
.byt 5, 78
.byt 5, 82
.byt 5, 86
.byt 5, 88
pattern_2:
.byt 177
.byt 0, 0
.byt 1, 30
.byt 0, 0
.byt 1, 30
pattern_263:
.byt 85
.byt 8, 96
.byt 8, 92
.byt 8, 88
.byt 8, 86
pattern_75:
.byt 85
.byt 3, 72
.byt 3, 68
.byt 3, 72
.byt 3, 78
pattern_265:
.byt 85
.byt 8, 88
.byt 8, 92
.byt 8, 96
.byt 8, 100
pattern_266:
.byt 85
.byt 8, 102
.byt 8, 106
.byt 8, 110
.byt 8, 112
pattern_267:
.byt 85
.byt 3, 96
.byt 3, 92
.byt 3, 88
.byt 3, 86
pattern_74:
.byt 85
.byt 3, 78
.byt 0, 0
.byt 3, 48
.byt 3, 54
pattern_269:
.byt 85
.byt 3, 100
.byt 3, 102
.byt 3, 100
.byt 3, 106
pattern_186:
.byt 85
.byt 5, 24
.byt 5, 28
.byt 5, 30
.byt 5, 34
pattern_271:
.byt 85
.byt 3, 96
.byt 3, 92
.byt 3, 88
.byt 3, 92
pattern_411:
.byt 85
.byt 14, 58
.byt 0, 0
.byt 14, 64
.byt 14, 64
pattern_238:
.byt 85
.byt 3, 112
.byt 3, 110
.byt 3, 106
.byt 3, 102
pattern_274:
.byt 85
.byt 8, 92
.byt 8, 96
.byt 8, 92
.byt 8, 88
pattern_275:
.byt 85
.byt 8, 86
.byt 8, 88
.byt 8, 92
.byt 8, 96
pattern_555:
.byt 85
.byt 3, 88
.byt 3, 92
.byt 3, 88
.byt 3, 82
pattern_277:
.byt 85
.byt 3, 82
.byt 3, 88
.byt 3, 102
.byt 3, 96
pattern_553:
.byt 85
.byt 3, 78
.byt 3, 86
.byt 3, 92
.byt 3, 92
pattern_73:
.byt 85
.byt 3, 54
.byt 3, 48
.byt 0, 0
.byt 3, 68
pattern_548:
.byt 29
.byt 3, 130
.byt 3, 124
.byt 0, 0
.byt 3, 120
pattern_547:
.byt 113
.byt 3, 102
.byt 3, 102
.byt 0, 0
.byt 3, 126
pattern_545:
.byt 85
.byt 16, 40
.byt 16, 54
.byt 16, 40
.byt 16, 54
pattern_78:
.byt 85
.byt 3, 54
.byt 0, 0
.byt 3, 72
.byt 3, 68
pattern_287:
.byt 85
.byt 3, 106
.byt 3, 102
.byt 3, 100
.byt 3, 102
pattern_15:
.byt 4
.byt 1, 68
; size = 256
.align 256
pattern_104:
.byt 85
.byt 4, 26
.byt 5, 12
.byt 4, 12
.byt 4, 18
pattern_242:
.byt 85
.byt 8, 82
.byt 8, 88
.byt 8, 102
.byt 8, 96
pattern_245:
.byt 29
.byt 8, 88
.byt 8, 82
.byt 8, 88
.byt 8, 92
pattern_246:
.byt 85
.byt 8, 96
.byt 8, 92
.byt 8, 88
.byt 8, 82
pattern_248:
.byt 85
.byt 8, 96
.byt 8, 92
.byt 8, 86
.byt 8, 78
pattern_96:
.byt 85
.byt 3, 116
.byt 3, 112
.byt 3, 110
.byt 3, 112
pattern_250:
.byt 85
.byt 3, 88
.byt 3, 82
.byt 3, 78
.byt 3, 82
pattern_251:
.byt 85
.byt 3, 96
.byt 3, 92
.byt 3, 88
.byt 3, 82
pattern_88:
.byt 85
.byt 3, 106
.byt 0, 0
.byt 3, 102
.byt 3, 96
pattern_253:
.byt 85
.byt 3, 96
.byt 3, 92
.byt 3, 86
.byt 3, 78
pattern_86:
.byt 89
.byt 3, 102
.byt 0, 0
.byt 3, 120
.byt 3, 116
pattern_85:
.byt 85
.byt 3, 120
.byt 3, 116
.byt 3, 110
.byt 3, 116
pattern_83:
.byt 85
.byt 3, 120
.byt 3, 116
.byt 3, 120
.byt 3, 126
pattern_82:
.byt 85
.byt 3, 126
.byt 3, 92
.byt 3, 96
.byt 3, 102
triangle_instrument_hi:
.byt .hibyte(triangle_instrument_0_arpeggio)
.byt .hibyte(triangle_instrument_1_arpeggio)
.byt .hibyte(triangle_instrument_2_arpeggio)
.byt .hibyte(triangle_instrument_3_arpeggio)
.byt .hibyte(triangle_instrument_4_arpeggio)
.byt .hibyte(triangle_instrument_5_arpeggio)
.byt .hibyte(triangle_instrument_6_arpeggio)
.byt .hibyte(triangle_instrument_7_arpeggio)
.byt .hibyte(triangle_instrument_8_arpeggio)
triangle_instrument_lo:
.byt .lobyte(triangle_instrument_0_arpeggio)
.byt .lobyte(triangle_instrument_1_arpeggio)
.byt .lobyte(triangle_instrument_2_arpeggio)
.byt .lobyte(triangle_instrument_3_arpeggio)
.byt .lobyte(triangle_instrument_4_arpeggio)
.byt .lobyte(triangle_instrument_5_arpeggio)
.byt .lobyte(triangle_instrument_6_arpeggio)
.byt .lobyte(triangle_instrument_7_arpeggio)
.byt .lobyte(triangle_instrument_8_arpeggio)
pattern_77:
.byt 85
.byt 3, 72
.byt 3, 68
.byt 3, 62
.byt 3, 68
pattern_350:
.byt 81
.byt 4, 58
.byt 4, 62
.byt 4, 64
pattern_412:
.byt 69
.byt 14, 68
.byt 0, 0
.byt 4, 78
pattern_413:
.byt 81
.byt 4, 82
.byt 4, 88
.byt 0, 0
pattern_414:
.byt 21
.byt 4, 92
.byt 0, 0
.byt 4, 78
pattern_519:
.byt 81
.byt 16, 54
.byt 16, 40
.byt 16, 54
pattern_559:
.byt 21
.byt 16, 72
.byt 16, 64
.byt 16, 58
pattern_558:
.byt 81
.byt 16, 54
.byt 16, 72
.byt 16, 78
pattern_556:
.byt 28
.byt 3, 86
.byt 0, 0
.byt 3, 92
pattern_546:
.byt 81
.byt 16, 40
.byt 16, 44
.byt 16, 58
pattern_544:
.byt 21
.byt 16, 48
.byt 16, 62
.byt 16, 48
pattern_543:
.byt 81
.byt 16, 54
.byt 16, 48
.byt 16, 62
pattern_542:
.byt 97
.byt 3, 88
.byt 0, 0
.byt 3, 96
pattern_539:
.byt 97
.byt 3, 120
.byt 0, 0
.byt 3, 120
pattern_530:
.byt 70
.byt 0, 0
.byt 3, 116
.byt 3, 100
pattern_193:
.byt 5
.byt 5, 82
.byt 5, 86
; size = 255
.align 256
pattern_527:
.byt 28
.byt 3, 116
.byt 0, 0
.byt 3, 112
pattern_526:
.byt 97
.byt 3, 102
.byt 0, 0
.byt 3, 102
pattern_523:
.byt 21
.byt 16, 44
.byt 16, 58
.byt 16, 44
pattern_522:
.byt 81
.byt 16, 48
.byt 16, 44
.byt 16, 58
pattern_520:
.byt 21
.byt 16, 40
.byt 16, 54
.byt 16, 40
pattern_423:
.byt 81
.byt 4, 34
.byt 4, 44
.byt 4, 48
pattern_513:
.byt 28
.byt 3, 110
.byt 0, 0
.byt 3, 116
pattern_505:
.byt 21
.byt 3, 134
.byt 3, 136
.byt 3, 140
pattern_500:
.byt 70
.byt 0, 0
.byt 3, 124
.byt 3, 130
pattern_499:
.byt 21
.byt 3, 110
.byt 3, 112
.byt 3, 116
pattern_498:
.byt 81
.byt 3, 112
.byt 3, 102
.byt 3, 106
pattern_496:
.byt 28
.byt 3, 134
.byt 0, 0
.byt 3, 140
pattern_491:
.byt 224
.byt 0, 0
.byt 3, 120
.byt 3, 124
pattern_486:
.byt 224
.byt 0, 0
.byt 3, 116
.byt 0, 0
pattern_484:
.byt 7
.byt 3, 120
.byt 0, 0
.byt 3, 124
pattern_482:
.byt 145
.byt 3, 112
.byt 3, 110
.byt 0, 0
pattern_469:
.byt 7
.byt 3, 96
.byt 0, 0
.byt 3, 100
pattern_454:
.byt 81
.byt 16, 72
.byt 16, 72
.byt 16, 62
pattern_453:
.byt 21
.byt 16, 68
.byt 16, 62
.byt 16, 54
pattern_435:
.byt 69
.byt 4, 82
.byt 0, 0
.byt 4, 86
pattern_174:
.byt 21
.byt 5, 64
.byt 5, 68
.byt 5, 72
pattern_327:
.byt 81
.byt 11, 34
.byt 11, 34
.byt 11, 38
pattern_328:
.byt 81
.byt 11, 40
.byt 11, 40
.byt 11, 40
pattern_187:
.byt 84
.byt 5, 20
.byt 5, 24
.byt 5, 28
pattern_329:
.byt 81
.byt 11, 40
.byt 11, 40
.byt 0, 0
pattern_182:
.byt 21
.byt 5, 68
.byt 0, 0
.byt 5, 68
pattern_331:
.byt 81
.byt 11, 44
.byt 0, 0
.byt 4, 54
pattern_181:
.byt 21
.byt 5, 76
.byt 5, 72
.byt 5, 76
pattern_332:
.byt 81
.byt 5, 58
.byt 5, 58
.byt 5, 58
pattern_178:
.byt 21
.byt 3, 52
.byt 0, 0
.byt 3, 52
pattern_177:
.byt 21
.byt 3, 58
.byt 3, 54
.byt 3, 58
pattern_334:
.byt 81
.byt 5, 64
.byt 5, 64
.byt 5, 64
pattern_175:
.byt 81
.byt 6, 64
.byt 5, 72
.byt 5, 76
pattern_192:
.byt 81
.byt 5, 78
.byt 5, 72
.byt 5, 78
pattern_336:
.byt 81
.byt 5, 68
.byt 5, 68
.byt 5, 68
pattern_170:
.byt 21
.byt 3, 48
.byt 3, 52
.byt 3, 54
pattern_403:
.byt 64
.byt 14, 62
; size = 255
.align 256
pattern_169:
.byt 81
.byt 3, 52
.byt 3, 52
.byt 0, 0
pattern_168:
.byt 69
.byt 5, 76
.byt 5, 72
.byt 0, 0
pattern_341:
.byt 69
.byt 4, 48
.byt 0, 0
.byt 4, 48
pattern_342:
.byt 81
.byt 4, 44
.byt 4, 48
.byt 4, 54
pattern_164:
.byt 69
.byt 3, 58
.byt 3, 54
.byt 0, 0
pattern_345:
.byt 69
.byt 4, 68
.byt 0, 0
.byt 4, 64
pattern_152:
.byt 81
.byt 1, 78
.byt 1, 78
.byt 1, 54
pattern_147:
.byt 81
.byt 4, 12
.byt 4, 12
.byt 5, 12
pattern_142:
.byt 21
.byt 4, 18
.byt 5, 22
.byt 4, 12
pattern_223:
.byt 21
.byt 3, 92
.byt 3, 88
.byt 3, 82
pattern_280:
.byt 21
.byt 3, 88
.byt 3, 82
.byt 3, 92
pattern_279:
.byt 81
.byt 3, 86
.byt 3, 96
.byt 3, 92
pattern_409:
.byt 69
.byt 14, 64
.byt 0, 0
.byt 14, 64
pattern_268:
.byt 21
.byt 3, 82
.byt 3, 88
.byt 3, 96
pattern_264:
.byt 21
.byt 8, 82
.byt 8, 88
.byt 8, 96
pattern_262:
.byt 21
.byt 10, 96
.byt 10, 96
.byt 10, 96
pattern_261:
.byt 28
.byt 10, 96
.byt 0, 0
.byt 10, 96
pattern_258:
.byt 21
.byt 9, 88
.byt 9, 88
.byt 9, 88
pattern_244:
.byt 81
.byt 8, 86
.byt 8, 96
.byt 8, 92
pattern_239:
.byt 21
.byt 3, 96
.byt 3, 92
.byt 3, 88
pattern_233:
.byt 21
.byt 8, 96
.byt 8, 92
.byt 8, 88
pattern_230:
.byt 21
.byt 8, 100
.byt 8, 102
.byt 8, 100
pattern_408:
.byt 21
.byt 14, 68
.byt 0, 0
.byt 14, 54
pattern_220:
.byt 21
.byt 3, 92
.byt 3, 96
.byt 3, 92
pattern_219:
.byt 84
.byt 3, 82
.byt 3, 88
.byt 3, 82
pattern_318:
.byt 81
.byt 10, 10
.byt 10, 10
.byt 10, 10
pattern_218:
.byt 81
.byt 3, 88
.byt 3, 82
.byt 3, 78
pattern_212:
.byt 69
.byt 5, 58
.byt 5, 54
.byt 0, 0
pattern_208:
.byt 69
.byt 5, 78
.byt 5, 110
.byt 0, 0
pattern_320:
.byt 81
.byt 10, 10
.byt 11, 10
.byt 11, 14
pattern_321:
.byt 81
.byt 10, 16
.byt 10, 16
.byt 10, 16
pattern_322:
.byt 81
.byt 10, 16
.byt 11, 16
.byt 0, 0
pattern_194:
.byt 21
.byt 5, 92
.byt 5, 92
.byt 5, 96
pattern_325:
.byt 81
.byt 11, 34
.byt 11, 34
.byt 11, 34
pattern_355:
.byt 81
.byt 10, 40
.byt 10, 34
.byt 10, 38
pattern_390:
.byt 69
.byt 14, 58
.byt 0, 0
.byt 14, 62
pattern_289:
.byt 16
.byt 7, 76
; size = 255
.align 256
pattern_7:
.byt 176
.byt 1, 28
.byt 0, 0
.byt 1, 34
pattern_92:
.byt 81
.byt 3, 102
.byt 3, 100
.byt 3, 96
pattern_90:
.byt 81
.byt 1, 54
.byt 0, 0
.byt 1, 78
pattern_84:
.byt 148
.byt 3, 110
.byt 3, 124
.byt 0, 0
pattern_9:
.byt 69
.byt 1, 0
.byt 2, 0
.byt 1, 0
pattern_80:
.byt 81
.byt 3, 58
.byt 3, 54
.byt 3, 48
pattern_76:
.byt 148
.byt 3, 62
.byt 3, 76
.byt 0, 0
pattern_21:
.byt 133
.byt 0, 0
.byt 1, 58
.byt 0, 0
pattern_356:
.byt 81
.byt 10, 40
.byt 12, 48
.byt 12, 44
pattern_68:
.byt 148
.byt 3, 86
.byt 3, 100
.byt 0, 0
pattern_365:
.byt 81
.byt 12, 88
.byt 12, 82
.byt 0, 0
pattern_133:
.byt 25
.byt 3, 30
.byt 3, 30
.byt 3, 30
pattern_364:
.byt 81
.byt 12, 88
.byt 12, 96
.byt 12, 92
pattern_363:
.byt 81
.byt 12, 88
.byt 12, 82
.byt 12, 86
pattern_46:
.byt 81
.byt 1, 3
.byt 2, 7
.byt 2, 0
pattern_362:
.byt 69
.byt 12, 88
.byt 0, 0
.byt 12, 92
pattern_95:
.byt 224
.byt 0, 0
.byt 3, 110
.byt 0, 0
pattern_36:
.byt 69
.byt 1, 68
.byt 1, 68
.byt 1, 54
pattern_125:
.byt 21
.byt 4, 22
.byt 5, 12
.byt 4, 12
pattern_407:
.byt 81
.byt 14, 58
.byt 14, 64
.byt 0, 0
pattern_122:
.byt 21
.byt 4, 8
.byt 4, 8
.byt 4, 8
pattern_370:
.byt 81
.byt 6, 64
.byt 6, 64
.byt 6, 64
pattern_4:
.byt 176
.byt 1, 30
.byt 0, 0
.byt 1, 30
pattern_24:
.byt 193
.byt 1, 72
.byt 1, 68
.byt 0, 0
pattern_38:
.byt 76
.byt 1, 68
.byt 1, 54
.byt 2, 92
pattern_110:
.byt 25
.byt 3, 15
.byt 3, 15
.byt 3, 8
pattern_367:
.byt 69
.byt 12, 92
.byt 0, 0
.byt 12, 86
pattern_366:
.byt 69
.byt 12, 92
.byt 0, 0
.byt 12, 88
pattern_352:
.byt 81
.byt 10, 34
.byt 10, 34
.byt 10, 34
pattern_101:
.byt 21
.byt 4, 12
.byt 5, 12
.byt 4, 12
pattern_5:
.byt 176
.byt 1, 34
.byt 0, 0
.byt 1, 34
pattern_97:
.byt 84
.byt 3, 110
.byt 3, 102
.byt 3, 106
macro_19:
.byt .lobyte(176)
.byt .lobyte(182)
.byt .lobyte(125)
.byt .lobyte(124)
.byt .lobyte(123)
.byt .lobyte(122)
macro_18:
.byt .lobyte(176)
.byt .lobyte(182)
.byt .lobyte(127)
.byt .lobyte(126)
.byt .lobyte(125)
.byt .lobyte(124)
macro_34:
.byt .lobyte(49)
.byt .lobyte(56)
.byt .lobyte(53)
.byt .lobyte(51)
.byt .lobyte(49)
.byt .lobyte(48)
pattern_286:
.byt 17
.byt 3, 86
.byt 3, 92
pattern_554:
.byt 96
.byt 0, 0
.byt 3, 92
pattern_444:
.byt 64
.byt 4, 86
; size = 255
.align 256
pattern_551:
.byt 68
.byt 3, 124
.byt 3, 126
pattern_276:
.byt 5
.byt 8, 100
.byt 8, 102
pattern_273:
.byt 17
.byt 3, 102
.byt 3, 110
pattern_228:
.byt 17
.byt 8, 96
.byt 8, 92
pattern_229:
.byt 20
.byt 8, 88
.byt 8, 96
pattern_557:
.byt 192
.byt 3, 86
.byt 3, 82
pattern_241:
.byt 65
.byt 3, 78
.byt 3, 86
pattern_17:
.byt 17
.byt 1, 3
.byt 2, 7
noise_instrument_lo:
.byt .lobyte(noise_instrument_0_arpeggio)
.byt .lobyte(noise_instrument_1_arpeggio)
.byt .lobyte(noise_instrument_2_arpeggio)
.byt .lobyte(noise_instrument_3_arpeggio)
.byt .lobyte(noise_instrument_4_arpeggio)
noise_instrument_hi:
.byt .hibyte(noise_instrument_0_arpeggio)
.byt .hibyte(noise_instrument_1_arpeggio)
.byt .hibyte(noise_instrument_2_arpeggio)
.byt .hibyte(noise_instrument_3_arpeggio)
.byt .hibyte(noise_instrument_4_arpeggio)
pattern_252:
.byt 17
.byt 3, 92
.byt 3, 88
pattern_247:
.byt 17
.byt 8, 92
.byt 8, 88
pattern_14:
.byt 65
.byt 1, 68
.byt 1, 54
pattern_10:
.byt 68
.byt 1, 0
.byt 2, 0
pattern_176:
.byt 17
.byt 5, 78
.byt 6, 64
pattern_130:
.byt 17
.byt 4, 12
.byt 4, 12
pattern_146:
.byt 17
.byt 4, 8
.byt 4, 8
pattern_148:
.byt 17
.byt 2, 32
.byt 2, 32
pattern_154:
.byt 17
.byt 5, 54
.byt 6, 54
pattern_157:
.byt 65
.byt 1, 68
.byt 1, 68
pattern_158:
.byt 17
.byt 1, 68
.byt 1, 68
pattern_159:
.byt 65
.byt 3, 3
.byt 3, 0
pattern_160:
.byt 17
.byt 3, 3
.byt 4, 12
pattern_109:
.byt 17
.byt 1, 78
.byt 1, 78
pattern_98:
.byt 17
.byt 3, 12
.byt 3, 12
pattern_172:
.byt 17
.byt 3, 62
.byt 0, 0
pattern_93:
.byt 17
.byt 3, 100
.byt 3, 106
pattern_173:
.byt 17
.byt 5, 68
.byt 6, 68
macro_20:
.byt .lobyte(63)
.byt .lobyte(63)
.byt .lobyte(63)
.byt .lobyte(63)
.byt .lobyte(48)
pattern_50:
.byt 144
.byt 3, 52
.byt 0, 0
pattern_184:
.byt 17
.byt 5, 20
.byt 5, 14
pattern_185:
.byt 17
.byt 5, 6
.byt 5, 14
macro_6:
.byt .lobyte(53)
.byt .lobyte(60)
.byt .lobyte(63)
.byt .lobyte(61)
.byt .lobyte(57)
pattern_189:
.byt 17
.byt 7, 64
.byt 7, 62
pattern_43:
.byt 144
.byt 3, 100
.byt 0, 0
pattern_191:
.byt 17
.byt 5, 86
.byt 5, 82
pattern_196:
.byt 17
.byt 7, 82
.byt 7, 78
pattern_198:
.byt 17
.byt 5, 92
.byt 5, 78
pattern_200:
.byt 17
.byt 5, 68
.byt 5, 54
pattern_202:
.byt 5
.byt 5, 58
.byt 5, 62
pattern_37:
.byt 12
.byt 1, 68
.byt 1, 54
pattern_319:
.byt 17
.byt 10, 10
.byt 11, 10
pattern_497:
.byt 192
.byt 3, 134
.byt 3, 130
pattern_326:
.byt 17
.byt 11, 34
.byt 11, 34
pattern_324:
.byt 5
.byt 10, 20
.byt 11, 20
pattern_501:
.byt 65
.byt 3, 126
.byt 3, 150
pattern_458:
.byt 17
.byt 3, 30
.byt 3, 30
pattern_323:
.byt 65
.byt 10, 20
.byt 10, 20
pattern_347:
.byt 65
.byt 10, 20
.byt 10, 30
pattern_348:
.byt 80
.byt 4, 54
.byt 4, 44
pattern_506:
.byt 68
.byt 3, 148
.byt 3, 150
; size = 255
.align 256
pattern_349:
.byt 17
.byt 4, 48
.byt 4, 54
pattern_459:
.byt 17
.byt 3, 30
.byt 3, 24
pattern_452:
.byt 17
.byt 16, 54
.byt 16, 68
pattern_511:
.byt 96
.byt 0, 0
.byt 3, 116
pattern_514:
.byt 192
.byt 3, 110
.byt 3, 106
pattern_353:
.byt 17
.byt 10, 34
.byt 10, 38
pattern_515:
.byt 96
.byt 0, 0
.byt 3, 86
pattern_354:
.byt 65
.byt 10, 40
.byt 12, 44
pattern_516:
.byt 65
.byt 3, 88
.byt 3, 78
pattern_310:
.byt 144
.byt 7, 82
.byt 0, 0
pattern_445:
.byt 17
.byt 16, 82
.byt 16, 64
pattern_465:
.byt 17
.byt 3, 86
.byt 3, 96
pattern_468:
.byt 17
.byt 3, 96
.byt 3, 92
pattern_467:
.byt 129
.byt 3, 88
.byt 0, 0
pattern_337:
.byt 17
.byt 5, 68
.byt 5, 68
pattern_335:
.byt 17
.byt 5, 64
.byt 5, 64
pattern_480:
.byt 17
.byt 3, 110
.byt 3, 120
pattern_481:
.byt 24
.byt 0, 0
.byt 3, 116
pattern_483:
.byt 17
.byt 3, 120
.byt 3, 116
pattern_333:
.byt 17
.byt 5, 58
.byt 5, 58
pattern_466:
.byt 24
.byt 0, 0
.byt 3, 92
pattern_288:
.byt 17
.byt 3, 100
.byt 3, 92
pattern_464:
.byt 129
.byt 3, 78
.byt 0, 0
pattern_487:
.byt 65
.byt 3, 112
.byt 3, 102
pattern_489:
.byt 96
.byt 0, 0
.byt 3, 110
pattern_463:
.byt 17
.byt 3, 20
.byt 3, 20
pattern_462:
.byt 17
.byt 3, 16
.byt 3, 20
pattern_330:
.byt 65
.byt 11, 44
.byt 11, 44
pattern_461:
.byt 17
.byt 3, 16
.byt 3, 16
pattern_460:
.byt 17
.byt 3, 24
.byt 3, 24
pattern_494:
.byt 96
.byt 0, 0
.byt 3, 140
pattern_387:
.byt 65
.byt 14, 34
.byt 14, 44
pattern_371:
.byt 17
.byt 6, 64
.byt 7, 58
pattern_369:
.byt 17
.byt 5, 64
.byt 6, 58
pattern_368:
.byt 17
.byt 5, 58
.byt 6, 62
pattern_302:
.byt 17
.byt 7, 110
.byt 7, 106
pattern_537:
.byt 20
.byt 0, 0
.byt 3, 112
pattern_372:
.byt 65
.byt 5, 68
.byt 5, 68
pattern_291:
.byt 17
.byt 7, 86
.byt 7, 82
pattern_298:
.byt 17
.byt 3, 110
.byt 3, 116
pattern_303:
.byt 17
.byt 7, 102
.byt 7, 100
pattern_359:
.byt 65
.byt 10, 44
.byt 12, 38
pattern_297:
.byt 17
.byt 3, 102
.byt 3, 106
pattern_373:
.byt 65
.byt 5, 68
.byt 6, 62
pattern_402:
.byt 65
.byt 14, 58
.byt 15, 58
pattern_383:
.byt 65
.byt 14, 34
.byt 14, 30
pattern_304:
.byt 17
.byt 7, 92
.byt 7, 96
pattern_404:
.byt 17
.byt 15, 58
.byt 15, 64
pattern_305:
.byt 17
.byt 7, 100
.byt 7, 106
pattern_292:
.byt 17
.byt 7, 78
.byt 7, 82
pattern_306:
.byt 17
.byt 3, 102
.byt 3, 96
; size = 245
.align 256
pattern_293:
.byt 17
.byt 7, 86
.byt 7, 88
pattern_358:
.byt 65
.byt 10, 44
.byt 12, 40
pattern_357:
.byt 17
.byt 12, 40
.byt 11, 34
pattern_443:
.byt 65
.byt 4, 82
.byt 16, 82
pattern_535:
.byt 96
.byt 0, 0
.byt 3, 106
pattern_420:
.byt 16
.byt 4, 30
pattern_378:
.byt 64
.byt 1, 58
pattern_377:
.byt 1
.byt 13, 82
pattern_361:
.byt 16
.byt 12, 86
pattern_360:
.byt 1
.byt 12, 82
pattern_0:
.byt 1
.byt 0, 0
pattern_100:
.byt 1
.byt 3, 96
pattern_451:
.byt 1
.byt 1, 58
pattern_450:
.byt 1
.byt 17, 34
pattern_449:
.byt 1
.byt 15, 10
pattern_94:
.byt 1
.byt 3, 110
pattern_448:
.byt 1
.byt 13, 10
pattern_91:
.byt 1
.byt 3, 100
pattern_89:
.byt 64
.byt 1, 44
pattern_296:
.byt 1
.byt 3, 106
pattern_308:
.byt 16
.byt 7, 124
pattern_237:
.byt 16
.byt 3, 106
pattern_307:
.byt 1
.byt 7, 120
pattern_240:
.byt 16
.byt 3, 72
pattern_243:
.byt 1
.byt 8, 92
pattern_249:
.byt 1
.byt 8, 82
pattern_254:
.byt 1
.byt 3, 82
pattern_255:
.byt 1
.byt 8, 88
pattern_257:
.byt 1
.byt 9, 88
pattern_301:
.byt 1
.byt 7, 102
pattern_300:
.byt 16
.byt 7, 100
pattern_259:
.byt 16
.byt 9, 82
pattern_299:
.byt 1
.byt 7, 96
pattern_340:
.byt 16
.byt 4, 54
pattern_560:
.byt 1
.byt 3, 78
pattern_270:
.byt 4
.byt 3, 102
pattern_295:
.byt 1
.byt 3, 102
pattern_294:
.byt 16
.byt 3, 100
pattern_278:
.byt 1
.byt 3, 92
pattern_552:
.byt 64
.byt 3, 76
pattern_549:
.byt 4
.byt 3, 96
pattern_290:
.byt 1
.byt 7, 78
pattern_281:
.byt 1
.byt 8, 64
pattern_282:
.byt 16
.byt 8, 68
pattern_283:
.byt 1
.byt 8, 72
pattern_284:
.byt 1
.byt 8, 78
pattern_285:
.byt 16
.byt 8, 62
pattern_309:
.byt 1
.byt 7, 126
pattern_343:
.byt 1
.byt 4, 48
pattern_339:
.byt 1
.byt 4, 58
pattern_338:
.byt 1
.byt 10, 20
pattern_485:
.byt 1
.byt 3, 126
pattern_179:
.byt 1
.byt 3, 64
pattern_180:
.byt 1
.byt 3, 68
pattern_183:
.byt 1
.byt 5, 82
pattern_490:
.byt 16
.byt 3, 116
pattern_493:
.byt 16
.byt 3, 144
pattern_188:
.byt 1
.byt 7, 68
pattern_190:
.byt 1
.byt 7, 72
pattern_195:
.byt 1
.byt 7, 86
pattern_197:
.byt 1
.byt 7, 92
pattern_503:
.byt 4
.byt 3, 120
pattern_507:
.byt 64
.byt 3, 100
pattern_215:
.byt 1
.byt 7, 38
pattern_227:
.byt 1
.byt 3, 88
pattern_225:
.byt 16
.byt 3, 82
pattern_231:
.byt 16
.byt 8, 106
pattern_221:
.byt 16
.byt 3, 96
pattern_317:
.byt 1
.byt 4, 96
pattern_217:
.byt 1
.byt 7, 58
pattern_216:
.byt 1
.byt 7, 54
pattern_214:
.byt 1
.byt 7, 40
pattern_213:
.byt 1
.byt 7, 44
pattern_510:
.byt 16
.byt 3, 120
pattern_205:
.byt 1
.byt 5, 54
macro_22:
.byt .lobyte(0)
.byt .lobyte(-1)
macro_13:
.byt .lobyte(191)
.byt .lobyte(188)
macro_17:
.byt .lobyte(48)
.byt .lobyte(60)
macro_16:
.byt .lobyte(48)
.byt .lobyte(63)
macro_32:
.byt .lobyte(176)
.byt .lobyte(191)
square1_instrument_0_arpeggio:
    jsr square1_instrument_0_pitch
    .byt $04, $00
@loop:
    nop
    jsr square1_arpeggio_return+2
    jmp @loop
square1_instrument_1_arpeggio:
    jsr square1_instrument_1_pitch
    .byt $04, $00
@loop:
    nop
    jsr square1_arpeggio_return+2
    jmp @loop
square1_instrument_2_arpeggio:
    jsr square1_instrument_2_pitch
    sbc #.lobyte(-14)
    jsr square1_arpeggio_return
    sbc #.lobyte(-8)
    jsr square1_arpeggio_return
    .byt $04, $00
@loop:
    nop
    jsr square1_arpeggio_return+2
    jmp @loop
square1_instrument_3_arpeggio:
    jsr square1_instrument_3_pitch
    .byt $04, $00
@loop:
    nop
    jsr square1_arpeggio_return+2
    jmp @loop
square1_instrument_4_arpeggio:
    jsr square1_instrument_4_pitch
    sbc #.lobyte(-14)
    jsr square1_arpeggio_return
    sbc #.lobyte(-8)
    jsr square1_arpeggio_return
    .byt $04, $00
@loop:
    nop
    jsr square1_arpeggio_return+2
    jmp @loop
square1_instrument_5_arpeggio:
    jsr square1_instrument_5_pitch
    nop
    jsr square1_arpeggio_return
    sbc #.lobyte(-24)
    jsr square1_arpeggio_return
    .byt $04, $00
@loop:
    nop
    jsr square1_arpeggio_return+2
    jmp @loop
square1_instrument_6_arpeggio:
    jsr square1_instrument_6_pitch
    .byt $04, $00
@loop:
    nop
    jsr square1_arpeggio_return+2
    jmp @loop
square1_instrument_7_arpeggio:
    jsr square1_instrument_7_pitch
    .byt $04, $00
@loop:
    nop
    jsr square1_arpeggio_return+2
    jmp @loop
square1_instrument_8_arpeggio:
    jsr square1_instrument_8_pitch
    .byt $04, $00
@loop:
    nop
    jsr square1_arpeggio_return+2
    jmp @loop
square1_instrument_9_arpeggio:
    jsr square1_instrument_9_pitch
    .byt $04, $00
@loop:
    nop
    jsr square1_arpeggio_return+2
    jmp @loop
square1_instrument_10_arpeggio:
    jsr square1_instrument_10_pitch
    .byt $04, $00
@loop:
    nop
    jsr square1_arpeggio_return+2
    jmp @loop
square1_instrument_11_arpeggio:
    jsr square1_instrument_11_pitch
    .byt $04, $00
@loop:
    nop
    jsr square1_arpeggio_return+2
    jmp @loop
square1_instrument_12_arpeggio:
    jsr square1_instrument_12_pitch
    .byt $04, $00
@loop:
    nop
    jsr square1_arpeggio_return+2
    jmp @loop
square1_instrument_13_arpeggio:
    jsr square1_instrument_13_pitch
    .byt $04, $00
@loop:
    nop
    jsr square1_arpeggio_return+2
    jmp @loop
square1_instrument_14_arpeggio:
    jsr square1_instrument_14_pitch
    .byt $04, $00
@loop:
    nop
    jsr square1_arpeggio_return+2
    jmp @loop
square1_instrument_15_arpeggio:
    jsr square1_instrument_15_pitch
    nop
    jsr square1_arpeggio_return
    sbc #.lobyte(8)
    jsr square1_arpeggio_return
    sbc #.lobyte(16)
    jsr square1_arpeggio_return
    .byt $04, $00
@loop:
    sbc #.lobyte(28)
    jsr square1_arpeggio_return+2
    jmp @loop
square1_instrument_16_arpeggio:
    jsr square1_instrument_16_pitch
    .byt $04, $00
@loop:
    nop
    jsr square1_arpeggio_return+2
    jmp @loop
square2_instrument_0_arpeggio:
    jsr square2_instrument_0_pitch
    .byt $04, $00
@loop:
    nop
    jsr square2_arpeggio_return+2
    jmp @loop
square2_instrument_1_arpeggio:
    jsr square2_instrument_1_pitch
    sbc #.lobyte(-14)
    jsr square2_arpeggio_return
    sbc #.lobyte(-8)
    jsr square2_arpeggio_return
    .byt $04, $00
@loop:
    nop
    jsr square2_arpeggio_return+2
    jmp @loop
square2_instrument_2_arpeggio:
    jsr square2_instrument_2_pitch
    sbc #.lobyte(-14)
    jsr square2_arpeggio_return
    sbc #.lobyte(-8)
    jsr square2_arpeggio_return
    .byt $04, $00
@loop:
    nop
    jsr square2_arpeggio_return+2
    jmp @loop
square2_instrument_3_arpeggio:
    jsr square2_instrument_3_pitch
    .byt $04, $00
@loop:
    nop
    jsr square2_arpeggio_return+2
    jmp @loop
square2_instrument_4_arpeggio:
    jsr square2_instrument_4_pitch
    nop
    jsr square2_arpeggio_return
    sbc #.lobyte(-24)
    jsr square2_arpeggio_return
    .byt $04, $00
@loop:
    nop
    jsr square2_arpeggio_return+2
    jmp @loop
square2_instrument_5_arpeggio:
    jsr square2_instrument_5_pitch
    .byt $04, $00
@loop:
    nop
    jsr square2_arpeggio_return+2
    jmp @loop
square2_instrument_6_arpeggio:
    jsr square2_instrument_6_pitch
    .byt $04, $00
@loop:
    nop
    jsr square2_arpeggio_return+2
    jmp @loop
square2_instrument_7_arpeggio:
    jsr square2_instrument_7_pitch
    nop
    jsr square2_arpeggio_return
    sbc #.lobyte(8)
    jsr square2_arpeggio_return
    sbc #.lobyte(4)
    jsr square2_arpeggio_return
    .byt $04, $00
@loop:
    nop
    jsr square2_arpeggio_return+2
    jmp @loop
square2_instrument_8_arpeggio:
    jsr square2_instrument_8_pitch
    .byt $04, $00
@loop:
    nop
    jsr square2_arpeggio_return+2
    jmp @loop
square2_instrument_9_arpeggio:
    jsr square2_instrument_9_pitch
    .byt $04, $00
@loop:
    nop
    jsr square2_arpeggio_return+2
    jmp @loop
square2_instrument_10_arpeggio:
    jsr square2_instrument_10_pitch
    .byt $04, $00
@loop:
    nop
    jsr square2_arpeggio_return+2
    jmp @loop
square2_instrument_11_arpeggio:
    jsr square2_instrument_11_pitch
    .byt $04, $00
@loop:
    nop
    jsr square2_arpeggio_return+2
    jmp @loop
square2_instrument_12_arpeggio:
    jsr square2_instrument_12_pitch
    nop
    jsr square2_arpeggio_return
    sbc #.lobyte(-24)
    jsr square2_arpeggio_return
    .byt $04, $00
@loop:
    nop
    jsr square2_arpeggio_return+2
    jmp @loop
square2_instrument_13_arpeggio:
    jsr square2_instrument_13_pitch
    nop
    jsr square2_arpeggio_return
    sbc #.lobyte(-24)
    jsr square2_arpeggio_return
    .byt $04, $00
@loop:
    nop
    jsr square2_arpeggio_return+2
    jmp @loop
square2_instrument_14_arpeggio:
    jsr square2_instrument_14_pitch
    .byt $04, $00
@loop:
    nop
    jsr square2_arpeggio_return+2
    jmp @loop
square2_instrument_15_arpeggio:
    jsr square2_instrument_15_pitch
    .byt $04, $00
@loop:
    nop
    jsr square2_arpeggio_return+2
    jmp @loop
square2_instrument_16_arpeggio:
    jsr square2_instrument_16_pitch
    .byt $04, $00
@loop:
    nop
    jsr square2_arpeggio_return+2
    jmp @loop
square2_instrument_17_arpeggio:
    jsr square2_instrument_17_pitch
    nop
    jsr square2_arpeggio_return
    sbc #.lobyte(8)
    jsr square2_arpeggio_return
    sbc #.lobyte(16)
    jsr square2_arpeggio_return
    .byt $04, $00
@loop:
    sbc #.lobyte(28)
    jsr square2_arpeggio_return+2
    jmp @loop
triangle_instrument_0_arpeggio:
    jsr triangle_instrument_0_pitch
    .byt $04, $00
@loop:
    nop
    jsr triangle_arpeggio_return+2
    jmp @loop
triangle_instrument_1_arpeggio:
    jsr triangle_instrument_1_pitch
    nop
    jsr triangle_arpeggio_return
    sbc #.lobyte(8)
    jsr triangle_arpeggio_return
    sbc #.lobyte(16)
    jsr triangle_arpeggio_return
    .byt $04, $00
@loop:
    sbc #.lobyte(28)
    jsr triangle_arpeggio_return+2
    jmp @loop
triangle_instrument_2_arpeggio:
    jsr triangle_instrument_2_pitch
    .byt $04, $00
@loop:
    nop
    jsr triangle_arpeggio_return+2
    jmp @loop
triangle_instrument_3_arpeggio:
    jsr triangle_instrument_3_pitch
    .byt $04, $00
@loop:
    nop
    jsr triangle_arpeggio_return+2
    jmp @loop
triangle_instrument_4_arpeggio:
    jsr triangle_instrument_4_pitch
    .byt $04, $00
@loop:
    nop
    jsr triangle_arpeggio_return+2
    jmp @loop
triangle_instrument_5_arpeggio:
    jsr triangle_instrument_5_pitch
    .byt $04, $00
@loop:
    nop
    jsr triangle_arpeggio_return+2
    jmp @loop
triangle_instrument_6_arpeggio:
    jsr triangle_instrument_6_pitch
    .byt $04, $00
@loop:
    nop
    jsr triangle_arpeggio_return+2
    jmp @loop
triangle_instrument_7_arpeggio:
    jsr triangle_instrument_7_pitch
    .byt $04, $00
@loop:
    nop
    jsr triangle_arpeggio_return+2
    jmp @loop
triangle_instrument_8_arpeggio:
    jsr triangle_instrument_8_pitch
    .byt $04, $00
@loop:
    nop
    jsr triangle_arpeggio_return+2
    jmp @loop
noise_instrument_0_arpeggio:
    jsr noise_instrument_0_vol_duty
    .byt $04, $00
@loop:
    nop
    jsr noise_arpeggio_return+2
    jmp @loop
noise_instrument_1_arpeggio:
    jsr noise_instrument_1_vol_duty
    .byt $04, $00
@loop:
    nop
    jsr noise_arpeggio_return+2
    axs #.lobyte(-2)
    jsr noise_arpeggio_return
    jmp @loop
noise_instrument_2_arpeggio:
    jsr noise_instrument_2_vol_duty
    nop
    jsr noise_arpeggio_return
    axs #.lobyte(1)
    jsr noise_arpeggio_return
    axs #.lobyte(-1)
    jsr noise_arpeggio_return
    .byt $04, $00
@loop:
    nop
    jsr noise_arpeggio_return+2
    jmp @loop
noise_instrument_3_arpeggio:
    jsr noise_instrument_3_vol_duty
    nop
    jsr noise_arpeggio_return
    axs #.lobyte(1)
    jsr noise_arpeggio_return
    axs #.lobyte(-1)
    jsr noise_arpeggio_return
    .byt $04, $00
@loop:
    nop
    jsr noise_arpeggio_return+2
    jmp @loop
noise_instrument_4_arpeggio:
    jsr noise_instrument_4_vol_duty
    axs #.lobyte(6)
    jsr noise_arpeggio_return
    .byt $04, $00
@loop:
    axs #.lobyte(13)
    jsr noise_arpeggio_return+2
    jmp @loop
tracks_lo:
.byt .lobyte(track_0)
.byt .lobyte(track_1)
.byt .lobyte(track_2)
.byt .lobyte(track_3)
.byt .lobyte(track_4)
.byt .lobyte(track_5)
.byt .lobyte(track_6)
.byt .lobyte(tracks_end)
tracks_hi:
.byt .hibyte(track_0)
.byt .hibyte(track_1)
.byt .hibyte(track_2)
.byt .hibyte(track_3)
.byt .hibyte(track_4)
.byt .hibyte(track_5)
.byt .hibyte(track_6)
.byt .hibyte(tracks_end)
tracks_speed:
.byt 6
.byt 6
.byt 6
.byt 4
.byt 4
.byt 6
.byt 5
