rad_nt:
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $02, $00, $00, $00, $00
.byt $06, $08, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $01, $03, $00, $00, $04, $05
.byt $07, $09, $0A, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $0B, $0D, $00, $10, $12, $14
.byt $16, $18, $1A, $1C, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $0C, $0E, $0F, $11, $13, $15
.byt $17, $19, $1B, $1D, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $1E, $20, $22, $24, $26, $28
.byt $2A, $2C, $2E, $30, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $1F, $21, $23, $25, $27, $29
.byt $2B, $2D, $2F, $31, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $32, $33, $35, $37, $39
.byt $3B, $3C, $3E, $40, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $34, $36, $38, $3A
.byt $3A, $3D, $3F, $41, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $42, $43, $45, $46
.byt $48, $4A, $4C, $4D, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $44, $3A, $47
.byt $49, $4B, $14, $4E, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $52, $54, $56
.byt $58, $5A, $5C, $5E, $60, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $4F, $50, $51, $53, $55, $57
.byt $59, $5B, $5D, $5F, $61, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $62, $64, $14, $67, $69, $6A, $6B, $6C
.byt $6E, $6F, $70, $72, $74, $76, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $63, $65, $66, $68, $68, $68, $68, $6D
.byt $14, $14, $71, $73, $75, $77, $78, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $7A, $14, $7B, $68, $68, $68, $68, $68
.byt $7D, $7F, $68, $68, $68, $68, $81, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $79
.byt $14, $14, $7C, $68, $68, $68, $68, $68
.byt $7E, $80, $68, $68, $68, $68, $82, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $83
.byt $14, $14, $14, $68, $68, $68, $68, $68
.byt $68, $86, $68, $68, $68, $88, $8A, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $84
.byt $14, $14, $14, $85, $68, $68, $68, $68
.byt $68, $87, $68, $68, $68, $89, $8B, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $8D
.byt $14, $14, $14, $8F, $68, $68, $68, $68
.byt $68, $87, $68, $68, $90, $92, $14, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $8C, $14
.byt $14, $14, $8E, $68, $68, $68, $68, $68
.byt $7E, $87, $68, $68, $91, $14, $14, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $93, $14
.byt $14, $14, $95, $68, $68, $68, $68, $68
.byt $68, $87, $68, $68, $97, $14, $8A, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $94, $14
.byt $14, $14, $96, $68, $68, $68, $68, $68
.byt $68, $87, $68, $68, $98, $14, $8A, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $99, $14
.byt $14, $14, $9A, $68, $68, $68, $68, $68
.byt $68, $87, $68, $68, $9B, $14, $8A, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $00, $14
.byt $14, $14, $9A, $68, $68, $68, $68, $68
.byt $7E, $87, $68, $68, $9C, $14, $9D, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $9E, $14
.byt $14, $14, $A0, $68, $68, $68, $68, $68
.byt $68, $87, $68, $A2, $14, $14, $A4, $00
.byt $00, $00, $00, $00, $00, $00, $00, $00
.byt $00, $00, $00, $00, $00, $00, $9F, $14
.byt $14, $14, $A1, $68, $68, $68, $68, $68
.byt $68, $87, $68, $A3, $14, $9D, $00, $00
.byt $41, $41, $41, $41, $41, $41, $41, $41
.byt $51, $51, $51, $51, $51, $51, $51, $51
.byt $55, $55, $55, $55, $55, $55, $55, $55
.byt $55, $55, $55, $55, $55, $55, $55, $55
.byt $EF, $EF, $EF, $EF, $EF, $EF, $EF, $EF
.byt $EB, $EB, $EB, $EB, $EB, $EB, $EB, $EB
.byt $EB, $EB, $EB, $EB, $EB, $EB, $EB, $EB
.byt $EB, $EB, $EB, $EB, $EB, $EB, $EB, $EB

rad_nt_swaps:
ldx #$2A
ldy #$36
stx PPUADDR
sty PPUADDR
lda #$68
sta PPUDATA

lda #$6D
sta PPUDATA

ldy #$38
stx PPUADDR
sty PPUADDR
lda #$14
sta PPUDATA

sta PPUDATA

ldy #$3A
stx PPUADDR
sty PPUADDR
lda #$71
sta PPUDATA

ldy #$55
stx PPUADDR
sty PPUADDR
lda #$68
sta PPUDATA

sta PPUDATA

ldy #$57
stx PPUADDR
sty PPUADDR
sta PPUDATA

lda #$7D
sta PPUDATA

ldy #$59
stx PPUADDR
sty PPUADDR
lda #$7F
sta PPUDATA

lda #$68
sta PPUDATA

ldy #$5B
stx PPUADDR
sty PPUADDR
sta PPUDATA

ldy #$74
stx PPUADDR
sty PPUADDR
sta PPUDATA

sta PPUDATA

ldy #$76
stx PPUADDR
sty PPUADDR
sta PPUDATA

sta PPUDATA

ldy #$78
stx PPUADDR
sty PPUADDR
lda #$7E
sta PPUDATA

lda #$80
sta PPUDATA

ldy #$7A
stx PPUADDR
sty PPUADDR
lda #$68
sta PPUDATA

sta PPUDATA

ldy #$94
stx PPUADDR
sty PPUADDR
sta PPUDATA

sta PPUDATA

ldy #$96
stx PPUADDR
sty PPUADDR
sta PPUDATA

sta PPUDATA

ldy #$98
stx PPUADDR
sty PPUADDR
sta PPUDATA

lda #$86
sta PPUDATA

ldy #$9A
stx PPUADDR
sty PPUADDR
lda #$68
sta PPUDATA

sta PPUDATA

ldx #$2B
ldy #$5C
stx PPUADDR
sty PPUADDR
lda #$9B
sta PPUDATA

ldy #$72
stx PPUADDR
sty PPUADDR
lda #$9A
sta PPUDATA

lda #$68
sta PPUDATA

ldy #$74
stx PPUADDR
sty PPUADDR
sta PPUDATA

ldy #$7C
stx PPUADDR
sty PPUADDR
lda #$9C
sta PPUDATA

ldy #$90
stx PPUADDR
sty PPUADDR
lda #$14
sta PPUDATA

sta PPUDATA

ldy #$92
stx PPUADDR
sty PPUADDR
lda #$A0
sta PPUDATA

lda #$68
sta PPUDATA

ldy #$94
stx PPUADDR
sty PPUADDR
sta PPUDATA

ldy #$9B
stx PPUADDR
sty PPUADDR
lda #$A2
sta PPUDATA

lda #$14
sta PPUDATA

ldy #$9D
stx PPUADDR
sty PPUADDR
sta PPUDATA

ldy #$B0
stx PPUADDR
sty PPUADDR
sta PPUDATA

sta PPUDATA

ldy #$B2
stx PPUADDR
sty PPUADDR
lda #$A1
sta PPUDATA

ldy #$B7
stx PPUADDR
sty PPUADDR
lda #$68
sta PPUDATA

sta PPUDATA

ldy #$B9
stx PPUADDR
sty PPUADDR
lda #$87
sta PPUDATA

lda #$68
sta PPUDATA

ldy #$BB
stx PPUADDR
sty PPUADDR
lda #$A3
sta PPUDATA

lda #$14
sta PPUDATA

ldy #$BD
stx PPUADDR
sty PPUADDR
lda #$9D
sta PPUDATA

lda #$00
sta PPUDATA

rts


rad2_nt_swaps:
ldx #$2A
ldy #$36
stx PPUADDR
sty PPUADDR
lda #$A5
sta PPUDATA

lda #$A6
sta PPUDATA

ldy #$38
stx PPUADDR
sty PPUADDR
lda #$A7
sta PPUDATA

lda #$A8
sta PPUDATA

ldy #$3A
stx PPUADDR
sty PPUADDR
lda #$A9
sta PPUDATA

ldy #$55
stx PPUADDR
sty PPUADDR
lda #$AB
sta PPUDATA

lda #$AD
sta PPUDATA

ldy #$57
stx PPUADDR
sty PPUADDR
lda #$AF
sta PPUDATA

lda #$3A
sta PPUDATA

ldy #$59
stx PPUADDR
sty PPUADDR
sta PPUDATA

lda #$B1
sta PPUDATA

ldy #$5B
stx PPUADDR
sty PPUADDR
lda #$B3
sta PPUDATA

ldy #$74
stx PPUADDR
sty PPUADDR
lda #$AA
sta PPUDATA

lda #$AC
sta PPUDATA

ldy #$76
stx PPUADDR
sty PPUADDR
lda #$AE
sta PPUDATA

lda #$B0
sta PPUDATA

ldy #$78
stx PPUADDR
sty PPUADDR
lda #$3A
sta PPUDATA

sta PPUDATA

ldy #$7A
stx PPUADDR
sty PPUADDR
lda #$B2
sta PPUDATA

lda #$B4
sta PPUDATA

ldy #$94
stx PPUADDR
sty PPUADDR
lda #$B5
sta PPUDATA

lda #$B6
sta PPUDATA

ldy #$96
stx PPUADDR
sty PPUADDR
lda #$B7
sta PPUDATA

lda #$B8
sta PPUDATA

ldy #$98
stx PPUADDR
sty PPUADDR
lda #$3A
sta PPUDATA

lda #$B9
sta PPUDATA

ldy #$9A
stx PPUADDR
sty PPUADDR
lda #$BA
sta PPUDATA

lda #$BB
sta PPUDATA

ldx #$2B
ldy #$5C
stx PPUADDR
sty PPUADDR
lda #$BF
sta PPUDATA

ldy #$72
stx PPUADDR
sty PPUADDR
lda #$BC
sta PPUDATA

lda #$BD
sta PPUDATA

ldy #$74
stx PPUADDR
sty PPUADDR
lda #$BE
sta PPUDATA

ldy #$7C
stx PPUADDR
sty PPUADDR
lda #$C0
sta PPUDATA

ldy #$90
stx PPUADDR
sty PPUADDR
lda #$C1
sta PPUDATA

lda #$C3
sta PPUDATA

ldy #$92
stx PPUADDR
sty PPUADDR
lda #$3A
sta PPUDATA

lda #$C6
sta PPUDATA

ldy #$94
stx PPUADDR
sty PPUADDR
lda #$C7
sta PPUDATA

ldy #$9B
stx PPUADDR
sty PPUADDR
lda #$68
sta PPUDATA

lda #$CB
sta PPUDATA

ldy #$9D
stx PPUADDR
sty PPUADDR
lda #$CD
sta PPUDATA

ldy #$B0
stx PPUADDR
sty PPUADDR
lda #$C2
sta PPUDATA

lda #$C4
sta PPUDATA

ldy #$B2
stx PPUADDR
sty PPUADDR
lda #$C5
sta PPUDATA

ldy #$B7
stx PPUADDR
sty PPUADDR
lda #$C8
sta PPUDATA

lda #$3A
sta PPUDATA

ldy #$B9
stx PPUADDR
sty PPUADDR
sta PPUDATA

lda #$C9
sta PPUDATA

ldy #$BB
stx PPUADDR
sty PPUADDR
lda #$CA
sta PPUDATA

lda #$CC
sta PPUDATA

ldy #$BD
stx PPUADDR
sty PPUADDR
lda #$CE
sta PPUDATA

lda #$CF
sta PPUDATA

rts
