recip_table_0_lo:
    .byt $AA, $89, $49, $88, $00, $F0, $8E, $94
    .byt $CC, $0C, $2E, $16, $AA, $D7, $89, $B4
    .byt $49, $3D, $88, $21, $00, $3E, $F0, $0E
    .byt $8E, $67, $94, $0D, $CC, $CE, $0C, $82
    .byt $2E, $0B, $16, $4C, $AA, $2F, $D7, $A0
    .byt $89, $90, $B4, $F2, $49, $B8, $3D, $D8
    .byt $88, $4B, $21, $08, $00, $0F, $3E, $89
    .byt $F0, $73, $0E, $C2, $8E, $70, $67, $74
    .byt $94, $C7, $0D, $64, $CC, $45, $CE, $65
    .byt $0C, $C0, $82, $52, $2E, $17, $0B, $0B
    .byt $16, $2C, $4C, $76, $AA, $E8, $2F, $7E
    .byt $D7, $37, $A0, $11, $89, $09, $90, $1F
    .byt $B4, $4F, $F2, $9A, $49, $FD, $B8, $78
    .byt $3D, $08, $D8, $AE, $88, $67, $4B, $34
    .byt $21, $12, $08, $02, $00, $03, $0F, $23
    .byt $3E, $60, $89, $B9, $F0, $2E, $73, $BD
    .byt $0E, $65, $C2, $25, $8E, $FC, $70, $E9
    .byt $67, $EB, $74, $01, $94, $2B, $C7, $68
    .byt $0D, $B6, $64, $16, $CC, $87, $45, $07
    .byt $CE, $98, $65, $37, $0C, $E4, $C0, $A0
    .byt $82, $69, $52, $3E, $2E, $21, $17, $0F
    .byt $0B, $09, $0B, $0F, $16, $1F, $2C, $3A
    .byt $4C, $60, $76, $8F, $AA, $C8, $E8, $0A
    .byt $2F, $55, $7E, $A9, $D7, $06, $37, $6B
    .byt $A0, $D8, $11, $4C, $89, $C8, $09, $4C
    .byt $90, $D7, $1F, $68, $B4, $01, $4F, $A0
    .byt $F2, $45, $9A, $F1, $49, $A2, $FD, $5A
    .byt $B8, $17, $78, $DA, $3D, $A2, $08, $70
    .byt $D8, $42, $AE, $1A, $88, $F7, $67, $D9
    .byt $4B, $BF, $34, $A9, $21, $99, $12, $8C
    .byt $08, $84, $02, $80, $00, $00, $03, $08
    .byt $0F, $18, $23, $2F, $3E, $4E, $60, $74
recip_table_0_hi:
    .byt $AA, $9D, $92, $88, $80, $F0, $E3, $D7
    .byt $CC, $C3, $BA, $B2, $AA, $A3, $9D, $97
    .byt $92, $8D, $88, $84, $80, $F8, $F0, $EA
    .byt $E3, $DD, $D7, $D2, $CC, $C7, $C3, $BE
    .byt $BA, $B6, $B2, $AE, $AA, $A7, $A3, $A0
    .byt $9D, $9A, $97, $94, $92, $8F, $8D, $8A
    .byt $88, $86, $84, $82, $80, $FC, $F8, $F4
    .byt $F0, $ED, $EA, $E6, $E3, $E0, $DD, $DA
    .byt $D7, $D4, $D2, $CF, $CC, $CA, $C7, $C5
    .byt $C3, $C0, $BE, $BC, $BA, $B8, $B6, $B4
    .byt $B2, $B0, $AE, $AC, $AA, $A8, $A7, $A5
    .byt $A3, $A2, $A0, $9F, $9D, $9C, $9A, $99
    .byt $97, $96, $94, $93, $92, $90, $8F, $8E
    .byt $8D, $8C, $8A, $89, $88, $87, $86, $85
    .byt $84, $83, $82, $81, $80, $FE, $FC, $FA
    .byt $F8, $F6, $F4, $F2, $F0, $EF, $ED, $EB
    .byt $EA, $E8, $E6, $E5, $E3, $E1, $E0, $DE
    .byt $DD, $DB, $DA, $D9, $D7, $D6, $D4, $D3
    .byt $D2, $D0, $CF, $CE, $CC, $CB, $CA, $C9
    .byt $C7, $C6, $C5, $C4, $C3, $C1, $C0, $BF
    .byt $BE, $BD, $BC, $BB, $BA, $B9, $B8, $B7
    .byt $B6, $B5, $B4, $B3, $B2, $B1, $B0, $AF
    .byt $AE, $AD, $AC, $AB, $AA, $A9, $A8, $A8
    .byt $A7, $A6, $A5, $A4, $A3, $A3, $A2, $A1
    .byt $A0, $9F, $9F, $9E, $9D, $9C, $9C, $9B
    .byt $9A, $99, $99, $98, $97, $97, $96, $95
    .byt $94, $94, $93, $92, $92, $91, $90, $90
    .byt $8F, $8F, $8E, $8D, $8D, $8C, $8C, $8B
    .byt $8A, $8A, $89, $89, $88, $87, $87, $86
    .byt $86, $85, $85, $84, $84, $83, $83, $82
    .byt $82, $81, $81, $80, $80, $FF, $FE, $FD
    .byt $FC, $FB, $FA, $F9, $F8, $F7, $F6, $F5
recip_table_1_lo:
    .byt $89, $A0, $B9, $D4, $F0, $0F, $2E, $50
    .byt $73, $97, $BD, $E5, $0E, $39, $65, $93
    .byt $C2, $F3, $25, $59, $8E, $C4, $FC, $35
    .byt $70, $AC, $E9, $27, $67, $A8, $EB, $2F
    .byt $74, $BA, $01, $4A, $94, $DF, $2B, $78
    .byt $C7, $17, $68, $BA, $0D, $61, $B6, $0D
    .byt $64, $BC, $16, $71, $CC, $29, $87, $E5
    .byt $45, $A6, $07, $6A, $CE, $32, $98, $FE
    .byt $65, $CE, $37, $A1, $0C, $78, $E4, $52
    .byt $C0, $30, $A0, $11, $82, $F5, $69, $DD
    .byt $52, $C8, $3E, $B6, $2E, $A7, $21, $9B
    .byt $17, $93, $0F, $8D, $0B, $8A, $09, $8A
    .byt $0B, $8C, $0F, $92, $16, $9A, $1F, $A5
    .byt $2C, $B3, $3A, $C3, $4C, $D5, $60, $EB
    .byt $76, $02, $8F, $1C, $AA, $39, $C8, $57
    .byt $E8, $79, $0A, $9C, $2F, $C2, $55, $E9
    .byt $7E, $13, $A9, $40, $D7, $6E, $06, $9E
    .byt $37, $D1, $6B, $05, $A0, $3C, $D8, $74
    .byt $11, $AE, $4C, $EB, $89, $29, $C8, $69
    .byt $09, $AA, $4C, $EE, $90, $33, $D7, $7A
    .byt $1F, $C3, $68, $0E, $B4, $5A, $01, $A8
    .byt $4F, $F7, $A0, $48, $F2, $9B, $45, $EF
    .byt $9A, $45, $F1, $9C, $49, $F5, $A2, $50
    .byt $FD, $AB, $5A, $09, $B8, $67, $17, $C7
    .byt $78, $29, $DA, $8B, $3D, $F0, $A2, $55
    .byt $08, $BC, $70, $24, $D8, $8D, $42, $F8
    .byt $AE, $64, $1A, $D1, $88, $3F, $F7, $AF
    .byt $67, $20, $D9, $92, $4B, $05, $BF, $79
    .byt $34, $EE, $A9, $65, $21, $DC, $99, $55
    .byt $12, $CF, $8C, $4A, $08, $C6, $84, $43
    .byt $02, $C1, $80, $40, $00, $C0, $80, $41
    .byt $01, $C3, $84, $46, $07, $C9, $8C, $4E
recip_table_1_hi:
    .byt $F4, $F3, $F2, $F1, $F0, $F0, $EF, $EE
    .byt $ED, $EC, $EB, $EA, $EA, $E9, $E8, $E7
    .byt $E6, $E5, $E5, $E4, $E3, $E2, $E1, $E1
    .byt $E0, $DF, $DE, $DE, $DD, $DC, $DB, $DB
    .byt $DA, $D9, $D9, $D8, $D7, $D6, $D6, $D5
    .byt $D4, $D4, $D3, $D2, $D2, $D1, $D0, $D0
    .byt $CF, $CE, $CE, $CD, $CC, $CC, $CB, $CA
    .byt $CA, $C9, $C9, $C8, $C7, $C7, $C6, $C5
    .byt $C5, $C4, $C4, $C3, $C3, $C2, $C1, $C1
    .byt $C0, $C0, $BF, $BF, $BE, $BD, $BD, $BC
    .byt $BC, $BB, $BB, $BA, $BA, $B9, $B9, $B8
    .byt $B8, $B7, $B7, $B6, $B6, $B5, $B5, $B4
    .byt $B4, $B3, $B3, $B2, $B2, $B1, $B1, $B0
    .byt $B0, $AF, $AF, $AE, $AE, $AD, $AD, $AC
    .byt $AC, $AC, $AB, $AB, $AA, $AA, $A9, $A9
    .byt $A8, $A8, $A8, $A7, $A7, $A6, $A6, $A5
    .byt $A5, $A5, $A4, $A4, $A3, $A3, $A3, $A2
    .byt $A2, $A1, $A1, $A1, $A0, $A0, $9F, $9F
    .byt $9F, $9E, $9E, $9D, $9D, $9D, $9C, $9C
    .byt $9C, $9B, $9B, $9A, $9A, $9A, $99, $99
    .byt $99, $98, $98, $98, $97, $97, $97, $96
    .byt $96, $95, $95, $95, $94, $94, $94, $93
    .byt $93, $93, $92, $92, $92, $91, $91, $91
    .byt $90, $90, $90, $90, $8F, $8F, $8F, $8E
    .byt $8E, $8E, $8D, $8D, $8D, $8C, $8C, $8C
    .byt $8C, $8B, $8B, $8B, $8A, $8A, $8A, $89
    .byt $89, $89, $89, $88, $88, $88, $87, $87
    .byt $87, $87, $86, $86, $86, $86, $85, $85
    .byt $85, $84, $84, $84, $84, $83, $83, $83
    .byt $83, $82, $82, $82, $82, $81, $81, $81
    .byt $81, $80, $80, $80, $80, $7F, $7F, $7F
    .byt $7F, $7E, $7E, $7E, $7E, $7D, $7D, $7D
recip_table_2_lo:
    .byt $11, $05, $97, $CE, $1F, $97, $A7, $61
    .byt $30, $2A, $BA, $F4, $44, $BF, $D0, $89
    .byt $5C, $54, $EA, $20, $78, $EB, $07, $B7
    .byt $97, $83, $28, $4F, $B9, $1B, $4B, $E8
    .byt $DE, $B5, $72, $82, $07, $50, $9C, $1E
    .byt $32, $EC, $C9, $BA, $61, $88, $F9, $57
    .byt $92, $26, $2C, $F5, $C7, $C4, $62, $94
    .byt $FE, $64, $9A, $34, $38, $04, $D6, $D5
    .byt $74, $A6, $13, $77, $B3, $48, $54, $19
    .byt $F5, $EB, $97, $BD, $3A, $8F, $DD, $61
    .byt $80, $34, $25, $07, $CA, $DA, $6F, $AD
    .byt $15, $80, $BC, $54, $63, $27, $0B, $FB
    .byt $B4, $D0, $5D, $A4, $06, $79, $B0, $4D
    .byt $5B, $22, $06, $F7, $B2, $CD, $5E, $A2
    .byt $0B, $78, $B8, $4E, $66, $24, $14, $FA
    .byt $C3, $D1, $72, $A8, $22, $7E, $D3, $55
    .byt $83, $2D, $35, $04, $E7, $DC, $99, $B3
    .byt $4C, $8B, $FF, $63, $B2, $3C, $67, $14
    .byt $1B, $ED, $D0, $C5, $86, $9E, $3C, $78
    .byt $F2, $51, $A9, $2A, $60, $04, $18, $DE
    .byt $D0, $B8, $88, $92, $41, $6C, $FA, $46
    .byt $B4, $21, $6E, $FC, $29, $D7, $E4, $B2
    .byt $9F, $8D, $5B, $68, $17, $44, $D3, $1F
    .byt $90, $FB, $4D, $D7, $0B, $B3, $C9, $90
    .byt $87, $6C, $46, $49, $05, $25, $C5, $02
    .byt $84, $DF, $45, $BC, $05, $9A, $C6, $77
    .byt $87, $54, $49, $32, $0B, $10, $CD, $EE
    .byt $8F, $CC, $52, $AA, $16, $89, $D9, $67
    .byt $9D, $46, $61, $25, $26, $04, $EA, $E3
    .byt $B0, $C2, $75, $A1, $3B, $81, $01, $60
    .byt $C7, $40, $8E, $20, $55, $00, $1C, $E0
    .byt $E4, $C0, $AB, $A0, $74, $80, $3C, $61
recip_table_2_hi:
    .byt $7D, $54, $7C, $53, $7C, $53, $7B, $53
    .byt $7B, $53, $7A, $52, $7A, $52, $79, $52
    .byt $79, $52, $78, $52, $78, $51, $78, $51
    .byt $77, $51, $77, $51, $76, $51, $76, $50
    .byt $75, $50, $75, $50, $75, $50, $74, $50
    .byt $74, $4F, $73, $4F, $73, $4F, $72, $4F
    .byt $72, $4F, $72, $4E, $71, $4E, $71, $4E
    .byt $70, $4E, $70, $4E, $70, $4E, $6F, $4D
    .byt $6F, $4D, $6F, $4D, $6E, $4D, $6E, $4D
    .byt $6D, $4C, $6D, $4C, $6D, $4C, $6C, $4C
    .byt $6C, $4C, $6C, $4C, $6B, $4B, $6B, $4B
    .byt $6B, $4B, $6A, $4B, $6A, $4B, $6A, $4A
    .byt $69, $4A, $69, $4A, $69, $4A, $68, $4A
    .byt $68, $4A, $68, $49, $67, $49, $67, $49
    .byt $67, $49, $66, $49, $66, $49, $66, $48
    .byt $65, $48, $65, $48, $65, $48, $64, $48
    .byt $64, $48, $64, $48, $63, $47, $63, $47
    .byt $63, $47, $62, $47, $62, $47, $62, $47
    .byt $62, $46, $61, $46, $61, $46, $61, $46
    .byt $60, $46, $60, $46, $60, $46, $60, $45
    .byt $5F, $45, $5F, $45, $5F, $45, $5E, $45
    .byt $5E, $45, $5E, $44, $5E, $44, $5D, $44
    .byt $5D, $44, $5D, $44, $5D, $44, $5C, $44
    .byt $5C, $43, $5C, $43, $5C, $43, $5B, $43
    .byt $5B, $43, $5B, $43, $5B, $43, $5A, $43
    .byt $5A, $42, $5A, $42, $5A, $42, $59, $42
    .byt $59, $42, $59, $42, $59, $42, $58, $41
    .byt $58, $41, $58, $41, $58, $41, $57, $41
    .byt $57, $41, $57, $41, $57, $41, $56, $40
    .byt $56, $40, $56, $40, $56, $40, $56, $40
    .byt $55, $40, $55, $40, $55, $40, $55, $3F
    .byt $54, $3F, $54, $3F, $54, $3F, $54, $3F
recip_table_3_lo:
    .byt $42, $B9, $55, $54, $03, $91, $3A, $3F
    .byt $C6, $69, $1E, $2A, $88, $41, $02, $16
    .byt $4B, $1A, $E7, $02, $0F, $F3, $CB, $EE
    .byt $D3, $CC, $B0, $D9, $98, $A6, $95, $C5
    .byt $5D, $7F, $7A, $B1, $22, $59, $5F, $9E
    .byt $E8, $33, $44, $8A, $AE, $0D, $2A, $76
    .byt $75, $E8, $10, $62, $3C, $C3, $F5, $4F
    .byt $03, $9E, $DB, $3C, $CB, $79, $C1, $28
    .byt $94, $54, $A7, $15, $5C, $30, $8D, $02
    .byt $25, $0C, $74, $EF, $EF, $E8, $5A, $DC
    .byt $B9, $C4, $41, $C9, $83, $A0, $28, $B6
    .byt $4E, $7D, $0F, $A3, $19, $5A, $F6, $90
    .byt $E4, $37, $DD, $7E, $B0, $14, $C4, $6B
    .byt $7C, $F2, $AB, $59, $49, $CF, $93, $46
    .byt $16, $AD, $7A, $34, $E3, $8B, $62, $22
    .byt $B1, $69, $4A, $0F, $7F, $48, $32, $FD
    .byt $4D, $26, $1A, $EB, $1C, $05, $02, $D9
    .byt $EB, $E4, $EA, $C8, $BA, $C3, $D3, $B6
    .byt $89, $A3, $BB, $A4, $59, $82, $A4, $92
    .byt $2A, $62, $8C, $81, $FA, $42, $75, $6F
    .byt $CB, $22, $5E, $5E, $9D, $02, $47, $4D
    .byt $6E, $E3, $30, $3B, $40, $C3, $1A, $2A
    .byt $12, $A4, $03, $19, $E5, $85, $ED, $08
    .byt $B7, $66, $D6, $F7, $8A, $47, $C0, $E6
    .byt $5E, $29, $AA, $D5, $31, $0B, $93, $C4
    .byt $05, $EC, $7D, $B3, $DA, $CE, $68, $A3
    .byt $AE, $B0, $52, $92, $83, $93, $3C, $82
    .byt $58, $75, $26, $71, $2D, $58, $11, $61
    .byt $03, $3A, $FB, $50, $D9, $1D, $E6, $40
    .byt $AF, $00, $D1, $30, $85, $E3, $BC, $20
    .byt $5C, $C7, $A7, $10, $33, $AA, $92, $00
    .byt $0A, $8E, $7D, $F0, $E1, $72, $68, $E0
recip_table_3_hi:
    .byt $3F, $32, $2A, $24, $3F, $32, $2A, $24
    .byt $3E, $32, $2A, $24, $3E, $32, $2A, $24
    .byt $3E, $32, $29, $24, $3E, $31, $29, $23
    .byt $3D, $31, $29, $23, $3D, $31, $29, $23
    .byt $3D, $31, $29, $23, $3D, $31, $29, $23
    .byt $3C, $31, $29, $23, $3C, $31, $29, $23
    .byt $3C, $30, $29, $23, $3C, $30, $28, $23
    .byt $3C, $30, $28, $23, $3B, $30, $28, $23
    .byt $3B, $30, $28, $23, $3B, $30, $28, $23
    .byt $3B, $30, $28, $22, $3A, $2F, $28, $22
    .byt $3A, $2F, $28, $22, $3A, $2F, $28, $22
    .byt $3A, $2F, $28, $22, $3A, $2F, $27, $22
    .byt $39, $2F, $27, $22, $39, $2F, $27, $22
    .byt $39, $2E, $27, $22, $39, $2E, $27, $22
    .byt $39, $2E, $27, $22, $38, $2E, $27, $22
    .byt $38, $2E, $27, $22, $38, $2E, $27, $21
    .byt $38, $2E, $27, $21, $38, $2E, $27, $21
    .byt $37, $2D, $26, $21, $37, $2D, $26, $21
    .byt $37, $2D, $26, $21, $37, $2D, $26, $21
    .byt $37, $2D, $26, $21, $36, $2D, $26, $21
    .byt $36, $2D, $26, $21, $36, $2D, $26, $21
    .byt $36, $2C, $26, $21, $36, $2C, $26, $21
    .byt $36, $2C, $26, $21, $35, $2C, $25, $21
    .byt $35, $2C, $25, $20, $35, $2C, $25, $20
    .byt $35, $2C, $25, $20, $35, $2C, $25, $20
    .byt $35, $2B, $25, $20, $34, $2B, $25, $20
    .byt $34, $2B, $25, $20, $34, $2B, $25, $20
    .byt $34, $2B, $25, $20, $34, $2B, $25, $20
    .byt $34, $2B, $24, $20, $33, $2B, $24, $20
    .byt $33, $2B, $24, $20, $33, $2A, $24, $20
    .byt $33, $2A, $24, $20, $33, $2A, $24, $20
    .byt $33, $2A, $24, $1F, $32, $2A, $24, $1F
recip_table_4_lo:
    .byt $D0, $4C, $7B, $2C, $40, $9F, $39, $03
    .byt $B0, $33, $66, $1B, $32, $93, $2F, $FA
    .byt $91, $1A, $52, $0B, $24, $87, $24, $F1
    .byt $72, $01, $3E, $FA, $16, $7B, $1A, $E8
    .byt $53, $E9, $2A, $EA, $08, $6F, $10, $DF
    .byt $35, $D1, $17, $D9, $FA, $63, $06, $D6
    .byt $16, $B8, $03, $C9, $EC, $57, $FC, $CD
    .byt $F8, $A1, $F0, $B9, $DF, $4C, $F1, $C5
    .byt $DA, $89, $DC, $A9, $D1, $40, $E7, $BC
    .byt $BD, $71, $C9, $99, $C3, $35, $DD, $B3
    .byt $9F, $5A, $B6, $89, $B6, $29, $D3, $AA
    .byt $82, $42, $A3, $79, $A9, $1E, $CA, $A2
    .byt $65, $2B, $90, $69, $9B, $12, $C0, $99
    .byt $48, $14, $7D, $5A, $8E, $07, $B6, $90
    .byt $2C, $FD, $6A, $4A, $81, $FC, $AC, $88
    .byt $0F, $E7, $58, $3B, $74, $F0, $A2, $7F
    .byt $F3, $D0, $45, $2B, $67, $E5, $99, $77
    .byt $D7, $BA, $33, $1C, $5A, $DA, $8F, $6E
    .byt $BC, $A4, $21, $0D, $4D, $CF, $85, $66
    .byt $A0, $8D, $0F, $FD, $40, $C4, $7C, $5E
    .byt $85, $77, $FD, $EE, $33, $B9, $72, $55
    .byt $6A, $62, $EB, $DF, $27, $AE, $69, $4D
    .byt $4F, $4C, $D9, $D0, $1A, $A3, $5F, $45
    .byt $34, $36, $C7, $C2, $0D, $98, $56, $3C
    .byt $19, $21, $B5, $B3, $01, $8E, $4D, $34
    .byt $FF, $0C, $A4, $A4, $F4, $83, $43, $2C
    .byt $E5, $F7, $92, $96, $E8, $78, $3A, $24
    .byt $CB, $E2, $81, $87, $DC, $6E, $31, $1C
    .byt $B1, $CD, $70, $79, $CF, $63, $27, $14
    .byt $97, $B8, $5F, $6A, $C3, $58, $1E, $0C
    .byt $7E, $A3, $4E, $5C, $B7, $4E, $15, $04
    .byt $65, $8F, $3D, $4E, $AB, $43, $0C, $FC
recip_table_4_hi:
    .byt $1F, $1C, $19, $17, $15, $13, $12, $11
    .byt $1F, $1C, $19, $17, $15, $13, $12, $10
    .byt $1F, $1C, $19, $17, $15, $13, $12, $10
    .byt $1F, $1C, $19, $16, $15, $13, $12, $10
    .byt $1F, $1B, $19, $16, $15, $13, $12, $10
    .byt $1F, $1B, $19, $16, $14, $13, $12, $10
    .byt $1F, $1B, $19, $16, $14, $13, $11, $10
    .byt $1E, $1B, $18, $16, $14, $13, $11, $10
    .byt $1E, $1B, $18, $16, $14, $13, $11, $10
    .byt $1E, $1B, $18, $16, $14, $13, $11, $10
    .byt $1E, $1B, $18, $16, $14, $13, $11, $10
    .byt $1E, $1B, $18, $16, $14, $13, $11, $10
    .byt $1E, $1B, $18, $16, $14, $13, $11, $10
    .byt $1E, $1B, $18, $16, $14, $13, $11, $10
    .byt $1E, $1A, $18, $16, $14, $12, $11, $10
    .byt $1E, $1A, $18, $16, $14, $12, $11, $10
    .byt $1D, $1A, $18, $16, $14, $12, $11, $10
    .byt $1D, $1A, $18, $16, $14, $12, $11, $10
    .byt $1D, $1A, $18, $16, $14, $12, $11, $10
    .byt $1D, $1A, $18, $15, $14, $12, $11, $10
    .byt $1D, $1A, $17, $15, $14, $12, $11, $10
    .byt $1D, $1A, $17, $15, $14, $12, $11, $10
    .byt $1D, $1A, $17, $15, $14, $12, $11, $10
    .byt $1D, $1A, $17, $15, $14, $12, $11, $10
    .byt $1D, $1A, $17, $15, $14, $12, $11, $10
    .byt $1C, $1A, $17, $15, $13, $12, $11, $10
    .byt $1C, $19, $17, $15, $13, $12, $11, $10
    .byt $1C, $19, $17, $15, $13, $12, $11, $10
    .byt $1C, $19, $17, $15, $13, $12, $11, $10
    .byt $1C, $19, $17, $15, $13, $12, $11, $10
    .byt $1C, $19, $17, $15, $13, $12, $11, $10
    .byt $1C, $19, $17, $15, $13, $12, $11, $0F
recip_table_5_lo:
    .byt $F4, $04, $2F, $70, $C5, $29, $9C, $1B
    .byt $A5, $38, $D4, $77, $20, $D0, $85, $3E
    .byt $E4, $F6, $22, $65, $BA, $20, $94, $13
    .byt $9E, $32, $CE, $71, $1B, $CB, $80, $3A
    .byt $D4, $E8, $16, $5A, $B0, $17, $8B, $0C
    .byt $97, $2B, $C8, $6B, $16, $C6, $7C, $36
    .byt $C4, $DA, $0A, $4F, $A6, $0E, $83, $04
    .byt $90, $25, $C2, $66, $11, $C1, $77, $32
    .byt $B5, $CC, $FD, $44, $9C, $05, $7B, $FD
    .byt $89, $1E, $BC, $60, $0C, $BC, $73, $2E
    .byt $A6, $BF, $F1, $39, $92, $FC, $73, $F5
    .byt $82, $18, $B6, $5B, $06, $B8, $6E, $29
    .byt $96, $B1, $E5, $2E, $89, $F3, $6A, $EE
    .byt $7B, $11, $B0, $55, $01, $B3, $6A, $25
    .byt $87, $A4, $D9, $23, $7F, $EA, $62, $E6
    .byt $74, $0B, $AA, $50, $FC, $AE, $65, $21
    .byt $78, $96, $CD, $18, $75, $E1, $5A, $DF
    .byt $6D, $05, $A4, $4B, $F7, $AA, $61, $1D
    .byt $69, $89, $C1, $0E, $6B, $D8, $52, $D7
    .byt $67, $FF, $9E, $45, $F2, $A5, $5D, $19
    .byt $5A, $7C, $B5, $03, $62, $D0, $4A, $D0
    .byt $60, $F8, $99, $40, $ED, $A0, $58, $15
    .byt $4C, $6F, $AA, $F8, $58, $C7, $42, $C9
    .byt $59, $F2, $93, $3A, $E8, $9C, $54, $11
    .byt $3D, $62, $9E, $EE, $4F, $BE, $3A, $C1
    .byt $52, $EC, $8D, $35, $E3, $97, $50, $0D
    .byt $2F, $55, $92, $E4, $45, $B6, $32, $BA
    .byt $4C, $E6, $87, $30, $DE, $92, $4B, $09
    .byt $20, $48, $87, $D9, $3C, $AD, $2B, $B3
    .byt $45, $E0, $82, $2B, $D9, $8E, $47, $05
    .byt $12, $3C, $7C, $CF, $33, $A5, $23, $AC
    .byt $3F, $DA, $7C, $25, $D5, $89, $43, $01
recip_table_5_hi:
    .byt $0F, $0F, $0E, $0D, $0C, $0C, $0B, $0B
    .byt $0A, $0A, $09, $09, $09, $08, $08, $08
    .byt $0F, $0E, $0E, $0D, $0C, $0C, $0B, $0B
    .byt $0A, $0A, $09, $09, $09, $08, $08, $08
    .byt $0F, $0E, $0E, $0D, $0C, $0C, $0B, $0B
    .byt $0A, $0A, $09, $09, $09, $08, $08, $08
    .byt $0F, $0E, $0E, $0D, $0C, $0C, $0B, $0B
    .byt $0A, $0A, $09, $09, $09, $08, $08, $08
    .byt $0F, $0E, $0D, $0D, $0C, $0C, $0B, $0A
    .byt $0A, $0A, $09, $09, $09, $08, $08, $08
    .byt $0F, $0E, $0D, $0D, $0C, $0B, $0B, $0A
    .byt $0A, $0A, $09, $09, $09, $08, $08, $08
    .byt $0F, $0E, $0D, $0D, $0C, $0B, $0B, $0A
    .byt $0A, $0A, $09, $09, $09, $08, $08, $08
    .byt $0F, $0E, $0D, $0D, $0C, $0B, $0B, $0A
    .byt $0A, $0A, $09, $09, $08, $08, $08, $08
    .byt $0F, $0E, $0D, $0D, $0C, $0B, $0B, $0A
    .byt $0A, $0A, $09, $09, $08, $08, $08, $08
    .byt $0F, $0E, $0D, $0D, $0C, $0B, $0B, $0A
    .byt $0A, $09, $09, $09, $08, $08, $08, $08
    .byt $0F, $0E, $0D, $0D, $0C, $0B, $0B, $0A
    .byt $0A, $09, $09, $09, $08, $08, $08, $08
    .byt $0F, $0E, $0D, $0C, $0C, $0B, $0B, $0A
    .byt $0A, $09, $09, $09, $08, $08, $08, $08
    .byt $0F, $0E, $0D, $0C, $0C, $0B, $0B, $0A
    .byt $0A, $09, $09, $09, $08, $08, $08, $08
    .byt $0F, $0E, $0D, $0C, $0C, $0B, $0B, $0A
    .byt $0A, $09, $09, $09, $08, $08, $08, $08
    .byt $0F, $0E, $0D, $0C, $0C, $0B, $0B, $0A
    .byt $0A, $09, $09, $09, $08, $08, $08, $08
    .byt $0F, $0E, $0D, $0C, $0C, $0B, $0B, $0A
    .byt $0A, $09, $09, $09, $08, $08, $08, $08
recip_table_6_lo:
    .byt $FD, $BF, $84, $4D, $1A, $E9, $BA, $8E
    .byt $64, $3C, $16, $F2, $CF, $AE, $8F, $70
    .byt $54, $38, $1D, $03, $EB, $D3, $BC, $A6
    .byt $91, $7C, $69, $55, $43, $31, $20, $0F
    .byt $F5, $B7, $7D, $47, $13, $E3, $B4, $89
    .byt $5F, $37, $12, $EE, $CB, $AA, $8B, $6D
    .byt $50, $34, $1A, $00, $E8, $D0, $B9, $A3
    .byt $8E, $7A, $66, $53, $41, $2F, $1E, $0D
    .byt $ED, $B0, $76, $40, $0D, $DD, $AF, $83
    .byt $5A, $32, $0D, $E9, $C7, $A6, $87, $69
    .byt $4C, $31, $16, $FD, $E5, $CD, $B6, $A1
    .byt $8C, $77, $64, $51, $3E, $2D, $1B, $0B
    .byt $E5, $A8, $6F, $3A, $07, $D7, $A9, $7E
    .byt $55, $2E, $08, $E5, $C3, $A2, $83, $65
    .byt $49, $2E, $13, $FA, $E2, $CA, $B4, $9E
    .byt $89, $75, $61, $4E, $3C, $2A, $19, $09
    .byt $DD, $A1, $69, $33, $01, $D1, $A4, $79
    .byt $50, $29, $04, $E0, $BF, $9E, $7F, $62
    .byt $45, $2A, $10, $F7, $DF, $C7, $B1, $9B
    .byt $86, $72, $5F, $4C, $3A, $28, $17, $07
    .byt $D5, $9A, $62, $2D, $FB, $CB, $9E, $73
    .byt $4B, $24, $FF, $DC, $BB, $9A, $7C, $5E
    .byt $42, $27, $0D, $F4, $DC, $C5, $AE, $99
    .byt $84, $70, $5C, $4A, $38, $26, $15, $05
    .byt $CE, $93, $5B, $26, $F5, $C5, $99, $6E
    .byt $46, $1F, $FB, $D8, $B6, $97, $78, $5B
    .byt $3F, $24, $0A, $F1, $D9, $C2, $AB, $96
    .byt $81, $6D, $5A, $47, $35, $24, $13, $03
    .byt $C6, $8B, $54, $20, $EE, $C0, $93, $69
    .byt $41, $1B, $F6, $D4, $B2, $93, $74, $57
    .byt $3B, $20, $06, $EE, $D6, $BF, $A9, $93
    .byt $7F, $6B, $58, $45, $33, $22, $11, $01
recip_table_6_hi:
    .byt $07, $07, $07, $07, $07, $06, $06, $06
    .byt $06, $06, $06, $05, $05, $05, $05, $05
    .byt $05, $05, $05, $05, $04, $04, $04, $04
    .byt $04, $04, $04, $04, $04, $04, $04, $04
    .byt $07, $07, $07, $07, $07, $06, $06, $06
    .byt $06, $06, $06, $05, $05, $05, $05, $05
    .byt $05, $05, $05, $05, $04, $04, $04, $04
    .byt $04, $04, $04, $04, $04, $04, $04, $04
    .byt $07, $07, $07, $07, $07, $06, $06, $06
    .byt $06, $06, $06, $05, $05, $05, $05, $05
    .byt $05, $05, $05, $04, $04, $04, $04, $04
    .byt $04, $04, $04, $04, $04, $04, $04, $04
    .byt $07, $07, $07, $07, $07, $06, $06, $06
    .byt $06, $06, $06, $05, $05, $05, $05, $05
    .byt $05, $05, $05, $04, $04, $04, $04, $04
    .byt $04, $04, $04, $04, $04, $04, $04, $04
    .byt $07, $07, $07, $07, $07, $06, $06, $06
    .byt $06, $06, $06, $05, $05, $05, $05, $05
    .byt $05, $05, $05, $04, $04, $04, $04, $04
    .byt $04, $04, $04, $04, $04, $04, $04, $04
    .byt $07, $07, $07, $07, $06, $06, $06, $06
    .byt $06, $06, $05, $05, $05, $05, $05, $05
    .byt $05, $05, $05, $04, $04, $04, $04, $04
    .byt $04, $04, $04, $04, $04, $04, $04, $04
    .byt $07, $07, $07, $07, $06, $06, $06, $06
    .byt $06, $06, $05, $05, $05, $05, $05, $05
    .byt $05, $05, $05, $04, $04, $04, $04, $04
    .byt $04, $04, $04, $04, $04, $04, $04, $04
    .byt $07, $07, $07, $07, $06, $06, $06, $06
    .byt $06, $06, $05, $05, $05, $05, $05, $05
    .byt $05, $05, $05, $04, $04, $04, $04, $04
    .byt $04, $04, $04, $04, $04, $04, $04, $04
recip_table_7_lo:
    .byt $FF, $EF, $E0, $D1, $C3, $B5, $A7, $9A
    .byt $8D, $81, $75, $69, $5D, $52, $47, $3D
    .byt $32, $28, $1E, $15, $0B, $02, $F9, $F0
    .byt $E8, $DF, $D7, $CF, $C7, $C0, $B8, $B1
    .byt $AA, $A3, $9C, $95, $8F, $88, $82, $7B
    .byt $75, $6F, $69, $64, $5E, $58, $53, $4E
    .byt $48, $43, $3E, $39, $34, $2F, $2B, $26
    .byt $21, $1D, $18, $14, $10, $0C, $07, $03
    .byt $FB, $EB, $DC, $CD, $BF, $B1, $A4, $97
    .byt $8A, $7E, $72, $66, $5A, $4F, $45, $3A
    .byt $30, $26, $1C, $12, $09, $00, $F7, $EE
    .byt $E6, $DD, $D5, $CD, $C6, $BE, $B6, $AF
    .byt $A8, $A1, $9A, $94, $8D, $86, $80, $7A
    .byt $74, $6E, $68, $62, $5D, $57, $52, $4C
    .byt $47, $42, $3D, $38, $33, $2E, $29, $25
    .byt $20, $1C, $17, $13, $0F, $0B, $06, $02
    .byt $F7, $E7, $D8, $CA, $BC, $AE, $A0, $93
    .byt $87, $7B, $6F, $63, $58, $4D, $42, $37
    .byt $2D, $23, $19, $10, $07, $FE, $F5, $EC
    .byt $E4, $DB, $D3, $CB, $C4, $BC, $B5, $AD
    .byt $A6, $9F, $99, $92, $8B, $85, $7F, $78
    .byt $72, $6C, $67, $61, $5B, $56, $50, $4B
    .byt $46, $41, $3C, $37, $32, $2D, $28, $24
    .byt $1F, $1B, $16, $12, $0E, $0A, $05, $01
    .byt $F3, $E4, $D5, $C6, $B8, $AA, $9D, $90
    .byt $84, $78, $6C, $60, $55, $4A, $3F, $35
    .byt $2B, $21, $17, $0E, $04, $FB, $F3, $EA
    .byt $E2, $D9, $D1, $C9, $C2, $BA, $B3, $AC
    .byt $A5, $9E, $97, $90, $8A, $83, $7D, $77
    .byt $71, $6B, $65, $5F, $5A, $54, $4F, $4A
    .byt $45, $3F, $3A, $35, $31, $2C, $27, $23
    .byt $1E, $1A, $15, $11, $0D, $08, $04, $00
recip_table_7_hi:
    .byt $03, $03, $03, $03, $03, $03, $03, $03
    .byt $03, $03, $03, $03, $03, $03, $03, $03
    .byt $03, $03, $03, $03, $03, $03, $02, $02
    .byt $02, $02, $02, $02, $02, $02, $02, $02
    .byt $02, $02, $02, $02, $02, $02, $02, $02
    .byt $02, $02, $02, $02, $02, $02, $02, $02
    .byt $02, $02, $02, $02, $02, $02, $02, $02
    .byt $02, $02, $02, $02, $02, $02, $02, $02
    .byt $03, $03, $03, $03, $03, $03, $03, $03
    .byt $03, $03, $03, $03, $03, $03, $03, $03
    .byt $03, $03, $03, $03, $03, $03, $02, $02
    .byt $02, $02, $02, $02, $02, $02, $02, $02
    .byt $02, $02, $02, $02, $02, $02, $02, $02
    .byt $02, $02, $02, $02, $02, $02, $02, $02
    .byt $02, $02, $02, $02, $02, $02, $02, $02
    .byt $02, $02, $02, $02, $02, $02, $02, $02
    .byt $03, $03, $03, $03, $03, $03, $03, $03
    .byt $03, $03, $03, $03, $03, $03, $03, $03
    .byt $03, $03, $03, $03, $03, $02, $02, $02
    .byt $02, $02, $02, $02, $02, $02, $02, $02
    .byt $02, $02, $02, $02, $02, $02, $02, $02
    .byt $02, $02, $02, $02, $02, $02, $02, $02
    .byt $02, $02, $02, $02, $02, $02, $02, $02
    .byt $02, $02, $02, $02, $02, $02, $02, $02
    .byt $03, $03, $03, $03, $03, $03, $03, $03
    .byt $03, $03, $03, $03, $03, $03, $03, $03
    .byt $03, $03, $03, $03, $03, $02, $02, $02
    .byt $02, $02, $02, $02, $02, $02, $02, $02
    .byt $02, $02, $02, $02, $02, $02, $02, $02
    .byt $02, $02, $02, $02, $02, $02, $02, $02
    .byt $02, $02, $02, $02, $02, $02, $02, $02
    .byt $02, $02, $02, $02, $02, $02, $02, $02
recip_table_8_lo:
    .byt $FF, $FB, $F7, $F4, $F0, $EC, $E8, $E5
    .byt $E1, $DE, $DA, $D7, $D3, $D0, $CD, $CA
    .byt $C6, $C3, $C0, $BD, $BA, $B7, $B4, $B1
    .byt $AF, $AC, $A9, $A6, $A3, $A1, $9E, $9C
    .byt $99, $96, $94, $91, $8F, $8D, $8A, $88
    .byt $85, $83, $81, $7F, $7C, $7A, $78, $76
    .byt $74, $72, $70, $6E, $6B, $69, $67, $66
    .byt $64, $62, $60, $5E, $5C, $5A, $58, $57
    .byt $55, $53, $51, $50, $4E, $4C, $4A, $49
    .byt $47, $45, $44, $42, $41, $3F, $3E, $3C
    .byt $3B, $39, $38, $36, $35, $33, $32, $30
    .byt $2F, $2D, $2C, $2B, $29, $28, $27, $25
    .byt $24, $23, $21, $20, $1F, $1E, $1C, $1B
    .byt $1A, $19, $18, $16, $15, $14, $13, $12
    .byt $11, $0F, $0E, $0D, $0C, $0B, $0A, $09
    .byt $08, $07, $06, $05, $04, $02, $01, $00
    .byt $FD, $F9, $F6, $F2, $EE, $EA, $E7, $E3
    .byt $DF, $DC, $D9, $D5, $D2, $CE, $CB, $C8
    .byt $C5, $C2, $BF, $BC, $B9, $B6, $B3, $B0
    .byt $AD, $AA, $A8, $A5, $A2, $9F, $9D, $9A
    .byt $98, $95, $93, $90, $8E, $8B, $89, $87
    .byt $84, $82, $80, $7E, $7B, $79, $77, $75
    .byt $73, $71, $6F, $6D, $6A, $68, $67, $65
    .byt $63, $61, $5F, $5D, $5B, $59, $57, $56
    .byt $54, $52, $50, $4F, $4D, $4B, $4A, $48
    .byt $46, $45, $43, $41, $40, $3E, $3D, $3B
    .byt $3A, $38, $37, $35, $34, $32, $31, $30
    .byt $2E, $2D, $2B, $2A, $29, $27, $26, $25
    .byt $23, $22, $21, $20, $1E, $1D, $1C, $1B
    .byt $19, $18, $17, $16, $15, $13, $12, $11
    .byt $10, $0F, $0E, $0D, $0B, $0A, $09, $08
    .byt $07, $06, $05, $04, $03, $02, $01, $00
recip_table_8_hi:
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
    .byt $01, $01, $01, $01, $01, $01, $01, $01
recip_and_table:
    .byt $FF, $FF, $FE, $FE, $FC, $FC, $FC, $FC
    .byt $F8, $F8, $F8, $F8, $F8, $F8, $F8, $F8
    .byt $F0, $F0, $F0, $F0, $F0, $F0, $F0, $F0
    .byt $F0, $F0, $F0, $F0, $F0, $F0, $F0, $F0
    .byt $E0, $E0, $E0, $E0, $E0, $E0, $E0, $E0
    .byt $E0, $E0, $E0, $E0, $E0, $E0, $E0, $E0
    .byt $E0, $E0, $E0, $E0, $E0, $E0, $E0, $E0
    .byt $E0, $E0, $E0, $E0, $E0, $E0, $E0, $E0
    .byt $C0, $C0, $C0, $C0, $C0, $C0, $C0, $C0
    .byt $C0, $C0, $C0, $C0, $C0, $C0, $C0, $C0
    .byt $C0, $C0, $C0, $C0, $C0, $C0, $C0, $C0
    .byt $C0, $C0, $C0, $C0, $C0, $C0, $C0, $C0
    .byt $C0, $C0, $C0, $C0, $C0, $C0, $C0, $C0
    .byt $C0, $C0, $C0, $C0, $C0, $C0, $C0, $C0
    .byt $C0, $C0, $C0, $C0, $C0, $C0, $C0, $C0
    .byt $C0, $C0, $C0, $C0, $C0, $C0, $C0, $C0
    .byt $80, $80, $80, $80, $80, $80, $80, $80
    .byt $80, $80, $80, $80, $80, $80, $80, $80
    .byt $80, $80, $80, $80, $80, $80, $80, $80
    .byt $80, $80, $80, $80, $80, $80, $80, $80
    .byt $80, $80, $80, $80, $80, $80, $80, $80
    .byt $80, $80, $80, $80, $80, $80, $80, $80
    .byt $80, $80, $80, $80, $80, $80, $80, $80
    .byt $80, $80, $80, $80, $80, $80, $80, $80
    .byt $80, $80, $80, $80, $80, $80, $80, $80
    .byt $80, $80, $80, $80, $80, $80, $80, $80
    .byt $80, $80, $80, $80, $80, $80, $80, $80
    .byt $80, $80, $80, $80, $80, $80, $80, $80
    .byt $80, $80, $80, $80, $80, $80, $80, $80
    .byt $80, $80, $80, $80, $80, $80, $80, $80
    .byt $80, $80, $80, $80, $80, $80, $80, $80
    .byt $80, $80, $80, $80, $80, $80, $80, $80
recip_or_table:
    .byt $00, $00, $00, $01, $00, $01, $02, $03
    .byt $00, $01, $02, $03, $04, $05, $06, $07
    .byt $00, $01, $02, $03, $04, $05, $06, $07
    .byt $08, $09, $0A, $0B, $0C, $0D, $0E, $0F
    .byt $00, $01, $02, $03, $04, $05, $06, $07
    .byt $08, $09, $0A, $0B, $0C, $0D, $0E, $0F
    .byt $10, $11, $12, $13, $14, $15, $16, $17
    .byt $18, $19, $1A, $1B, $1C, $1D, $1E, $1F
    .byt $00, $01, $02, $03, $04, $05, $06, $07
    .byt $08, $09, $0A, $0B, $0C, $0D, $0E, $0F
    .byt $10, $11, $12, $13, $14, $15, $16, $17
    .byt $18, $19, $1A, $1B, $1C, $1D, $1E, $1F
    .byt $20, $21, $22, $23, $24, $25, $26, $27
    .byt $28, $29, $2A, $2B, $2C, $2D, $2E, $2F
    .byt $30, $31, $32, $33, $34, $35, $36, $37
    .byt $38, $39, $3A, $3B, $3C, $3D, $3E, $3F
    .byt $00, $01, $02, $03, $04, $05, $06, $07
    .byt $08, $09, $0A, $0B, $0C, $0D, $0E, $0F
    .byt $10, $11, $12, $13, $14, $15, $16, $17
    .byt $18, $19, $1A, $1B, $1C, $1D, $1E, $1F
    .byt $20, $21, $22, $23, $24, $25, $26, $27
    .byt $28, $29, $2A, $2B, $2C, $2D, $2E, $2F
    .byt $30, $31, $32, $33, $34, $35, $36, $37
    .byt $38, $39, $3A, $3B, $3C, $3D, $3E, $3F
    .byt $40, $41, $42, $43, $44, $45, $46, $47
    .byt $48, $49, $4A, $4B, $4C, $4D, $4E, $4F
    .byt $50, $51, $52, $53, $54, $55, $56, $57
    .byt $58, $59, $5A, $5B, $5C, $5D, $5E, $5F
    .byt $60, $61, $62, $63, $64, $65, $66, $67
    .byt $68, $69, $6A, $6B, $6C, $6D, $6E, $6F
    .byt $70, $71, $72, $73, $74, $75, $76, $77
    .byt $78, $79, $7A, $7B, $7C, $7D, $7E, $7F
recip_asl_table:
    .byt $07, $07, $07, $07, $07, $0E, $0E, $0E
    .byt $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
    .byt $0E, $0E, $0E, $0E, $0E, $15, $15, $15
    .byt $15, $15, $15, $15, $15, $15, $15, $15
    .byt $15, $15, $15, $15, $15, $15, $15, $15
    .byt $15, $15, $15, $15, $15, $15, $15, $15
    .byt $15, $15, $15, $15, $15, $1C, $1C, $1C
    .byt $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C
    .byt $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C
    .byt $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C
    .byt $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C
    .byt $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C
    .byt $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C
    .byt $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C
    .byt $1C, $1C, $1C, $1C, $1C, $23, $23, $23
    .byt $23, $23, $23, $23, $23, $23, $23, $23
    .byt $23, $23, $23, $23, $23, $23, $23, $23
    .byt $23, $23, $23, $23, $23, $23, $23, $23
    .byt $23, $23, $23, $23, $23, $23, $23, $23
    .byt $23, $23, $23, $23, $23, $23, $23, $23
    .byt $23, $23, $23, $23, $23, $23, $23, $23
    .byt $23, $23, $23, $23, $23, $23, $23, $23
    .byt $23, $23, $23, $23, $23, $23, $23, $23
    .byt $23, $23, $23, $23, $23, $23, $23, $23
    .byt $23, $23, $23, $23, $23, $23, $23, $23
    .byt $23, $23, $23, $23, $23, $23, $23, $23
    .byt $23, $23, $23, $23, $23, $23, $23, $23
    .byt $23, $23, $23, $23, $23, $23, $23, $23
    .byt $23, $23, $23, $23, $23, $23, $23, $23
    .byt $23, $23, $23, $23, $23, $23, $23, $23
    .byt $23, $23, $23, $23, $23, $2A, $2A, $2A
    .byt $2A, $2A, $2A, $2A, $2A, $2A, $2A, $2A
recip_index_table:
    .byt .hibyte(recip_table_0_lo), .hibyte(recip_table_1_lo)
    .byt .hibyte(recip_table_2_lo), .hibyte(recip_table_2_lo)
    .byt .hibyte(recip_table_3_lo), .hibyte(recip_table_3_lo)
    .byt .hibyte(recip_table_3_lo), .hibyte(recip_table_3_lo)
    .byt .hibyte(recip_table_4_lo), .hibyte(recip_table_4_lo)
    .byt .hibyte(recip_table_4_lo), .hibyte(recip_table_4_lo)
    .byt .hibyte(recip_table_4_lo), .hibyte(recip_table_4_lo)
    .byt .hibyte(recip_table_4_lo), .hibyte(recip_table_4_lo)
    .byt .hibyte(recip_table_5_lo), .hibyte(recip_table_5_lo)
    .byt .hibyte(recip_table_5_lo), .hibyte(recip_table_5_lo)
    .byt .hibyte(recip_table_5_lo), .hibyte(recip_table_5_lo)
    .byt .hibyte(recip_table_5_lo), .hibyte(recip_table_5_lo)
    .byt .hibyte(recip_table_5_lo), .hibyte(recip_table_5_lo)
    .byt .hibyte(recip_table_5_lo), .hibyte(recip_table_5_lo)
    .byt .hibyte(recip_table_5_lo), .hibyte(recip_table_5_lo)
    .byt .hibyte(recip_table_5_lo), .hibyte(recip_table_5_lo)
    .byt .hibyte(recip_table_6_lo), .hibyte(recip_table_6_lo)
    .byt .hibyte(recip_table_6_lo), .hibyte(recip_table_6_lo)
    .byt .hibyte(recip_table_6_lo), .hibyte(recip_table_6_lo)
    .byt .hibyte(recip_table_6_lo), .hibyte(recip_table_6_lo)
    .byt .hibyte(recip_table_6_lo), .hibyte(recip_table_6_lo)
    .byt .hibyte(recip_table_6_lo), .hibyte(recip_table_6_lo)
    .byt .hibyte(recip_table_6_lo), .hibyte(recip_table_6_lo)
    .byt .hibyte(recip_table_6_lo), .hibyte(recip_table_6_lo)
    .byt .hibyte(recip_table_6_lo), .hibyte(recip_table_6_lo)
    .byt .hibyte(recip_table_6_lo), .hibyte(recip_table_6_lo)
    .byt .hibyte(recip_table_6_lo), .hibyte(recip_table_6_lo)
    .byt .hibyte(recip_table_6_lo), .hibyte(recip_table_6_lo)
    .byt .hibyte(recip_table_6_lo), .hibyte(recip_table_6_lo)
    .byt .hibyte(recip_table_6_lo), .hibyte(recip_table_6_lo)
    .byt .hibyte(recip_table_6_lo), .hibyte(recip_table_6_lo)
    .byt .hibyte(recip_table_6_lo), .hibyte(recip_table_6_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_7_lo), .hibyte(recip_table_7_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
    .byt .hibyte(recip_table_8_lo), .hibyte(recip_table_8_lo)
