; size = 255
.align 256
square2_sfx_3_arpeggio_pattern:
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(54)
.byt .lobyte(54)
.byt .lobyte(-492)
square1_sfx_3_arpeggio_pattern:
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(30)
.byt .lobyte(30)
.byt .lobyte(-516)
square2_sfx_3_pitch_pattern:
.byt .lobyte(1)
.byt .lobyte(-129)
.byt .lobyte(-45)
.byt .lobyte(314)
.byt .lobyte(3)
.byt .lobyte(-94)
.byt .lobyte(-117)
.byt .lobyte(208)
.byt .lobyte(-140)
.byt .lobyte(-71)
.byt .lobyte(123)
.byt .lobyte(-55)
.byt .lobyte(3)
.byt .lobyte(-27)
.byt .lobyte(52)
.byt .lobyte(-52)
.byt .lobyte(27)
.byt .lobyte(-3)
.byt .lobyte(-123)
.byt .lobyte(-51)
.byt .lobyte(320)
.byt .lobyte(-3)
.byt .lobyte(-88)
.byt .lobyte(-123)
.byt .lobyte(214)
.byt .lobyte(-146)
.byt .lobyte(-65)
.byt .lobyte(117)
.byt .lobyte(-49)
.byt .lobyte(-3)
.byt .lobyte(-21)
.byt .lobyte(46)
.byt .lobyte(-46)
.byt .lobyte(21)
.byt .lobyte(3)
.byt .lobyte(-129)
.byt .lobyte(-45)
.byt .lobyte(314)
.byt .lobyte(3)
.byt .lobyte(-94)
.byt .lobyte(-117)
.byt .lobyte(208)
.byt .lobyte(-140)
.byt .lobyte(-71)
.byt .lobyte(123)
.byt .lobyte(-55)
.byt .lobyte(3)
.byt .lobyte(-27)
.byt .lobyte(52)
.byt .lobyte(-52)
.byt .lobyte(27)
.byt .lobyte(-3)
.byt .lobyte(-123)
.byt .lobyte(-51)
.byt .lobyte(320)
.byt .lobyte(-3)
.byt .lobyte(-88)
.byt .lobyte(-123)
.byt .lobyte(214)
.byt .lobyte(-146)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(-1606)
.byt .lobyte(0)
.byt .lobyte(-1651467325)
square1_sfx_2_pitch_pattern:
.byt .lobyte(-3)
.byt .lobyte(6)
.byt .lobyte(7)
.byt .lobyte(-3)
.byt .lobyte(-3)
.byt .lobyte(-3)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
square1_sfx_4_vol_duty_pattern:
    .byt 63
    .byt 63
    .byt 63
    .byt 63
    .byt 63
    .byt 63
    .byt 63
    .byt 63
    .byt 63
    .byt 63
    .byt 63
    .byt 63
    .byt 63
    .byt 63
    .byt 63
    .byt 63
    .byt 63
; size = 255
.align 256
square1_sfx_3_pitch_pattern:
.byt .lobyte(1)
.byt .lobyte(-253)
.byt .lobyte(-94)
.byt .lobyte(630)
.byt .lobyte(3)
.byt .lobyte(-184)
.byt .lobyte(-238)
.byt .lobyte(419)
.byt .lobyte(-283)
.byt .lobyte(-139)
.byt .lobyte(244)
.byt .lobyte(-108)
.byt .lobyte(3)
.byt .lobyte(-51)
.byt .lobyte(102)
.byt .lobyte(-102)
.byt .lobyte(51)
.byt .lobyte(-3)
.byt .lobyte(-247)
.byt .lobyte(-100)
.byt .lobyte(636)
.byt .lobyte(-3)
.byt .lobyte(-178)
.byt .lobyte(-244)
.byt .lobyte(425)
.byt .lobyte(-289)
.byt .lobyte(-133)
.byt .lobyte(238)
.byt .lobyte(-102)
.byt .lobyte(-3)
.byt .lobyte(-45)
.byt .lobyte(96)
.byt .lobyte(-96)
.byt .lobyte(45)
.byt .lobyte(3)
.byt .lobyte(-253)
.byt .lobyte(-94)
.byt .lobyte(630)
.byt .lobyte(3)
.byt .lobyte(-184)
.byt .lobyte(-238)
.byt .lobyte(419)
.byt .lobyte(-283)
.byt .lobyte(-139)
.byt .lobyte(244)
.byt .lobyte(-108)
.byt .lobyte(3)
.byt .lobyte(-51)
.byt .lobyte(102)
.byt .lobyte(-102)
.byt .lobyte(51)
.byt .lobyte(-3)
.byt .lobyte(-247)
.byt .lobyte(-100)
.byt .lobyte(636)
.byt .lobyte(-3)
.byt .lobyte(-178)
.byt .lobyte(-244)
.byt .lobyte(425)
.byt .lobyte(-289)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(-1179)
.byt .lobyte(0)
.byt .lobyte(-1651467325)
square2_sfx_3_vol_duty_pattern:
    .byt 127
    .byt 191
    .byt 191
    .byt 127
    .byt 255
    .byt 191
    .byt 124
    .byt 188
    .byt 188
    .byt 124
    .byt 124
    .byt 124
    .byt 184
    .byt 184
    .byt 120
    .byt 248
    .byt 184
    .byt 120
    .byt 180
    .byt 180
    .byt 116
    .byt 116
    .byt 116
    .byt 180
    .byt 180
    .byt 116
    .byt 244
    .byt 180
    .byt 116
    .byt 180
    .byt 179
    .byt 115
    .byt 115
    .byt 115
    .byt 179
    .byt 179
    .byt 115
    .byt 243
    .byt 179
    .byt 115
    .byt 179
    .byt 179
    .byt 114
    .byt 114
    .byt 114
    .byt 178
    .byt 178
    .byt 114
    .byt 242
    .byt 178
    .byt 114
    .byt 178
    .byt 178
    .byt 114
    .byt 113
    .byt 113
    .byt 177
    .byt 177
    .byt 113
    .byt 241
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
square1_sfx_3_vol_duty_pattern:
    .byt 127
    .byt 191
    .byt 191
    .byt 127
    .byt 255
    .byt 191
    .byt 124
    .byt 188
    .byt 188
    .byt 124
    .byt 124
    .byt 124
    .byt 184
    .byt 184
    .byt 120
    .byt 248
    .byt 184
    .byt 120
    .byt 180
    .byt 180
    .byt 116
    .byt 116
    .byt 116
    .byt 180
    .byt 180
    .byt 116
    .byt 244
    .byt 180
    .byt 116
    .byt 180
    .byt 179
    .byt 115
    .byt 115
    .byt 115
    .byt 179
    .byt 179
    .byt 115
    .byt 243
    .byt 179
    .byt 115
    .byt 179
    .byt 179
    .byt 114
    .byt 114
    .byt 114
    .byt 178
    .byt 178
    .byt 114
    .byt 242
    .byt 178
    .byt 114
    .byt 178
    .byt 178
    .byt 114
    .byt 113
    .byt 113
    .byt 177
    .byt 177
    .byt 113
    .byt 241
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
square1_sfx_2_arpeggio_pattern:
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
square1_sfx_4_pitch_pattern:
.byt .lobyte(0)
.byt .lobyte(24)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(-24)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
; size = 245
.align 256
square1_sfx_2_vol_duty_pattern:
    .byt 63
    .byt 191
    .byt 63
    .byt 191
    .byt 63
    .byt 191
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
square1_sfx_1_arpeggio_pattern:
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
square1_sfx_1_pitch_pattern:
.byt .lobyte(-3)
.byt .lobyte(12)
.byt .lobyte(14)
.byt .lobyte(-3)
.byt .lobyte(-3)
.byt .lobyte(-3)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
square1_sfx_1_vol_duty_pattern:
    .byt 63
    .byt 191
    .byt 63
    .byt 191
    .byt 63
    .byt 191
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
square1_sfx_4_arpeggio_pattern:
.byt .lobyte(0)
.byt .lobyte(-4)
.byt .lobyte(-4)
.byt .lobyte(-4)
.byt .lobyte(-4)
.byt .lobyte(-4)
.byt .lobyte(-4)
.byt .lobyte(-4)
.byt .lobyte(-4)
.byt .lobyte(-4)
.byt .lobyte(-4)
.byt .lobyte(-4)
.byt .lobyte(-4)
.byt .lobyte(-4)
.byt .lobyte(-4)
.byt .lobyte(-4)
.byt .lobyte(-4)
square1_sfx_4_vol_duty:
    jsr square1_sfx_call_return
    cpy #17
    bcc :+
    jmp end_square1_sfx
:   lda square1_sfx_4_vol_duty_pattern, y
    jmp square1_vol_duty_return
square2_sfx_3_vol_duty:
    jsr square2_sfx_call_return
    cpy #67
    bcc :+
    jmp end_square2_sfx
:   lda square2_sfx_3_vol_duty_pattern, y
    jmp square2_vol_duty_return
square1_sfx_3_vol_duty:
    jsr square1_sfx_call_return
    cpy #67
    bcc :+
    jmp end_square1_sfx
:   lda square1_sfx_3_vol_duty_pattern, y
    jmp square1_vol_duty_return
square1_sfx_2_vol_duty:
    jsr square1_sfx_call_return
    cpy #37
    bcc :+
    jmp end_square1_sfx
:   lda square1_sfx_2_vol_duty_pattern, y
    jmp square1_vol_duty_return
square1_sfx_1_vol_duty:
    jsr square1_sfx_call_return
    cpy #37
    bcc :+
    jmp end_square1_sfx
:   lda square1_sfx_1_vol_duty_pattern, y
    jmp square1_vol_duty_return
; size = 55
.align 256
triangle_sfx_0_vol_duty:
    jsr triangle_sfx_call_return
    cpy #13
    bcc :+
    jmp end_triangle_sfx
:   lda triangle_sfx_0_vol_duty_pattern, y
    jmp triangle_vol_duty_return
triangle_sfx_0_arpeggio_pattern:
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
triangle_sfx_0_pitch_pattern:
.byt .lobyte(-235)
.byt .lobyte(83)
.byt .lobyte(149)
.byt .lobyte(266)
.byt .lobyte(-266)
.byt .lobyte(-3)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
.byt .lobyte(0)
triangle_sfx_0_vol_duty_pattern:
    .byt 191
    .byt 191
    .byt 191
    .byt 191
    .byt 191
    .byt 191
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48
    .byt 48

triangle_sfx_0_pitch:
    jsr triangle_sfx_0_vol_duty
    nop
    nop
    sec
    lda triangle_sfx_0_pitch_pattern, x
    jmp triangle_pitch_return
triangle_sfx_0:
    tsx
    stx sfx_stack_temp
    lax triangle_stack
    axs #.lobyte(-6)
    txs
    ldx #0
    stx triangle_stack_next
    lda #62
    sta triangle_note
triangle_sfx_0_arpeggio:
    jsr triangle_sfx_0_pitch
    sbc triangle_sfx_0_arpeggio_pattern, x
    jmp triangle_arpeggio_sfx_return
square1_sfx_1_pitch:
    jsr square1_sfx_1_vol_duty
    nop
    nop
    sec
    lda square1_sfx_1_pitch_pattern, x
    jmp square1_pitch_return
square1_sfx_1:
    tsx
    stx sfx_stack_temp
    lax square1_stack
    axs #.lobyte(-6)
    txs
    ldx #0
    stx square1_stack_next
    dex
    stx square1_pitch_hi
    lda #78
    sta square1_note
square1_sfx_1_arpeggio:
    jsr square1_sfx_1_pitch
    sbc square1_sfx_1_arpeggio_pattern, x
    jmp square1_arpeggio_sfx_return
square1_sfx_2_pitch:
    jsr square1_sfx_2_vol_duty
    nop
    nop
    sec
    lda square1_sfx_2_pitch_pattern, x
    jmp square1_pitch_return
square1_sfx_2:
    tsx
    stx sfx_stack_temp
    lax square1_stack
    axs #.lobyte(-6)
    txs
    ldx #0
    stx square1_stack_next
    dex
    stx square1_pitch_hi
    lda #102
    sta square1_note
square1_sfx_2_arpeggio:
    jsr square1_sfx_2_pitch
    sbc square1_sfx_2_arpeggio_pattern, x
    jmp square1_arpeggio_sfx_return
square1_sfx_3_pitch:
    jsr square1_sfx_3_vol_duty
    nop
    nop
    sec
    lda square1_sfx_3_pitch_pattern, x
    jmp square1_pitch_return
square2_sfx_3_pitch:
    jsr square2_sfx_3_vol_duty
    nop
    nop
    sec
    lda square2_sfx_3_pitch_pattern, x
    jmp square2_pitch_return
square1_sfx_3:
    tsx
    stx sfx_stack_temp
    lax square1_stack
    axs #.lobyte(-6)
    txs
    ldx #0
    stx square1_stack_next
    dex
    stx square1_pitch_hi
    lda #30
    sta square1_note
square1_sfx_3_arpeggio:
    jsr square1_sfx_3_pitch
    sbc square1_sfx_3_arpeggio_pattern, x
    jmp square1_arpeggio_sfx_return
square2_sfx_3:
    tsx
    stx sfx_stack_temp
    lax square2_stack
    axs #.lobyte(-6)
    txs
    ldx #0
    stx square2_stack_next
    dex
    stx square2_pitch_hi
    lda #54
    sta square2_note
square2_sfx_3_arpeggio:
    jsr square2_sfx_3_pitch
    sbc square2_sfx_3_arpeggio_pattern, x
    jmp square2_arpeggio_sfx_return
square1_sfx_4_pitch:
    jsr square1_sfx_4_vol_duty
    nop
    nop
    sec
    lda square1_sfx_4_pitch_pattern, x
    jmp square1_pitch_return
square1_sfx_4:
    tsx
    stx sfx_stack_temp
    lax square1_stack
    axs #.lobyte(-6)
    txs
    ldx #0
    stx square1_stack_next
    dex
    stx square1_pitch_hi
    lda #78
    sta square1_note
square1_sfx_4_arpeggio:
    jsr square1_sfx_4_pitch
    sbc square1_sfx_4_arpeggio_pattern, x
    jmp square1_arpeggio_sfx_return

